Ben987/Bondage-College

- Drawing.js
By utilizing an object, you actually can reference the images directly, which could be optimized to a Hashmap by the JS VM, resulting in O(1) ;)
Also the source code is less complex, shorter and has a better overview!
> Improve cache

- Actor.js
- C000_Intro/ChapterSelect/Stage_ES.csv
- C000_Intro/ChapterSelect/Stage_RU.csv
- Common.js
Alright, this should make the translated actor names work for all languages in all chapters. Hopefully nothing else is broken, that would be really embarrassing by now. But I tested chapters 1, 2 and 101 in English, German, Spanish and Russian, and everything seemed to be working fine.
While I was at it, I changed the translated chapter list to make it a bit more compact and slightly easier to edit in the future. I was hesitating for a pretty long time if I should do this, because it might cause merge conflicts if someone is currently translating a new chapter and isn't aware of these changes. But I think that would have happened either way because I needed to change the function as a whole. I hope this is okay, if there's anything wrong with it, I can change it back to the previous form …
> Actor Names Fix

- BondageClub/Scripts/Dialog.js
This is a small change requested on Discord. People were pointing out that no matter how gagged you are, you should still be able to hear sentence structure and tone, and I agree. This change makes it so that ".", "!" and "?" characters are always preserved no matter the gag level.
> Gag Effects Tweaks

- BondageClub/Scripts/Dialog.js
- BondageClub/Scripts/Inventory.js
A small fix to the new InventoryItemHasEffect function. The function now only checks an item's Property attribute if you specify it in the function parameters. This should prevent abuse by hackers like using a collar with the "Lock" and "Freeze" effects on a player, which would otherwise trap them in the main hall with no way out.
> InventoryItemHasEffect Fix

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/index.html
Just the changes we talked about on Discord today, I hope this looks okay (and that I didn't make the code too messy). The player IDs are displayed below the timestamps, I wasn't sure how big to make them exactly.
Also, I posted this on Discord too, but just to make sure: Did you see my recent comment about the "player entered" messages not showing up anymore when someone enters a chatroom? I think it's because Players don't get added to the ChatRoomCharacter array until after that message arrives, so the function can't find them and stops.
> Chat style adjustments

- BondageClub/CSS/Styles.css
This turned out to be a much smaller change than I thought it would be. It basically does just 2 things:
- Changes how the text shadow of the character names is calculated (the distance between the text and the shadow was way too large on smaller screens before).
- Applies the left padding to chat messages themselves, rather than the entire box. This gets rid of the white gap on the left side of the chat.
I was originally planning to do some more things. For example, hiding the player id numbers unless you hover over a message (as some players requested) turned out to be incredibly easy to do, but I don't have time to test it on mobile, so I wasn't really comfortable to do something like that right before a release. For the next one though, I'll try adding some preferences for such …
> Minor chat style adjustments

- BondageClub/Scripts/Character.js
Changing a character's expression runs a full graphic update on that character. This check prevents these updates from running unnecessarily and impacting performance when the same expression is applied multiple times in a row.
> Don't apply already active expressions.

- BondageClub/Scripts/Drawing.js
Instead of using per-pixel iteration for characters, use a semi-transparent fill and then fix the alpha channel using the 'destination-in' blend mode.
> Optimise blindfold effect

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Also allow /me command to send emote messages (working exactly like '*') - for those users that have used /me far too often in the old IRC days or with Skype, etc.
> Add /me command to Chat

- BondageClub/Screens/Room/Magic/Magic.js
Fixed bug in the magic show that caused an undefined error in the `MagicRestrainCopyTransfer(FromC, ToC) function`. The cause was the appearance array was trying to be accessed with an index > array length
> Magic.js: changed ToC array to FromC array in the last if statement

- BondageClub/CSS/Styles.css
- BondageClub/Screens/Character/Login/Login.js
- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- BondageClub/Screens/Character/Preference/Text_Preference_DE.txt
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Element.js
A new menu as a preference subscreen that allows players to adjust the look of their chat. To access it, go to the preference menu and click the chat icon on the right. On first use, the settings default to the style that's currently active in the game for all players. These settings can also be changed without issue while you're inside a chat room.
I added a bit of code to allow styling messages differently that inform about players joining or leaving a room, since a few people said those could get annoying sometimes. If possible, maybe this could be changed in the future? So that the server would send them as their own message type, ideally allowing these strings to be translated as well.
I probably didn't test all possible scenarios you can create by playing around with the settings, …
> Chat Display Settings

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Just a quick fix for a problem that was pointed out to me on Discord. If a player hasn't specified a color for their label, the default color for actions and emotes had no transparency and looked strange when using the dark theme.
> Chat Color Fix

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Character/Wardrobe/Wardrobe.js
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Dialog.js
- BondageClub/Scripts/Drawing.js
Adds a height setting for each player and will display so in rooms, chatrooms, dialog and wardrobe
Currently allows to go from 0.9 to 1.0 of maximum size.
Possible to add more place where characters are resized through the call of the DrawCharacter function
untested on mobile version
known issues : 
-No translation support
-Possible to add more lower height settings but might break the suspension rope
> Added a height setting

- BondageClub/Screens/Character/Login/Login.js
-Will check at login that the player has indeed passed the exam and adds stable items in her inventory (bit gag and pony boots), also add lockable pony boots in her inventory if the case.
-Won't remove restraints currently used, but players will still have them deleted from their inventory.
disclaimer : locking pony boots and clothing pony boots can seem a bit redundant for the moment, but it won't be when there will exist some itemboots not hiding shoes.
> Check at login for stable items

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
It has been brought to my attention that when using whispers in the chat, certain character sequences (like a broken heart, `</3`), would mess up the chat's HTML structure. On the senders end, all following messages would appear like whispers and be further indented, even if they exit whisper mode. These lines should fix that, although I wasn't sure if they should only be in effect when whispering, or always.
> Fix breaking whispers when using HTML characters

- BondageClub/Scripts/Speech.js
as the title says, when an item with multiple effects (hoods for example) only their first effect was checked
should work properly now
> Fix for gag effects not being correctly applied

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Added a command in chat to use an emote without the name of the sender in front of it for more diversity in RP and descriptions.
the command is `**` or `/action`
it will still be possible to distinguish different messages as emotes are in italic and actions are in parenthesis.
> Command for alternate emote

- BondageClub/Scripts/Server.js
fixed `C.Appearance[A].Asset.LockedBy` -> `C.Appearance[A].Property.LockedBy `
the timed owner lock is now secure if `EnableRandomInput  == false`
Color == "Default" could still cause missing body since no Default body color exists, moved to Asset.Group.ColorSchema[0] which in the most case "Default" except the body parts
> OwnerLock validation

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Input only refocused if it was focused before or the user comes back to the ChatRoom Screen
ElementContent => appendChild, with the previous change, allow an easy way to select and copy text from the TextAreaChatLog while new messages are incoming, slightly better performance on extra long chat logs
ElementRemove => style.display == "none", the InputChat is not cleared when the user views a character or another screen and come back to the room
ChatRoomLog become obsolete so it got removed
> ChatRoom Input better focus and text is not cleared

- BondageClub/Screens/Inventory/ItemPelvis/LoveChastityBelt/LoveChastityBelt.js
ItemVulvaPiercings is now blocked,
if ItemVulvaPiercings as `Block:["ItemVulva"]` vibe or shock type can no longer be selected
> Fix LoveChastityBelt blocking

- BondageClub/Scripts/Common.js
`Date.now()` is faster than `new Date().getTime()` and works abolutaly the same
(the old one create an object each time with a frozen Date of the Date.now())
> Date.now()

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Character/Player/Dialog_Player.csv
- BondageClub/Scripts/Inventory.js
Allows short chain to be used with petsuits again and new Prerequisite so it cannot be used with items such as the fullLatexSuit which cannot be used while kneeling.
> Fix for short chain

- BondageClub/Scripts/ColorPicker.js
- BondageClub/Scripts/Dialog.js
TestCase Passed:
- Pick color for next item
- Pick color for current item on the fly
- Send action messages upon item color change in chatroom
Tested using: 
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18362
Google Chrome 79.0.3945.130
> BUGFIX: Edge compatibility of color picker

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Scripts/ColorPicker.js
Way to reproduce the bug:
1. An android chrome browser (or desktop chrome with mobile mode turned on in devtools)
2. Enter appearance screen
3. Tap on any one of 2nd - 7th color picker button
4. Color positioned exactly under the tap position will be selected immediately
This will make it hard to copy existing clothing color
> Bugfix android copy colorcode

- BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
* Ensures that collar accessories are removed when removing a collar during the kidnap minigame (this would occurr when entering a minigame whilst already wearing a collar with accessories).
> Bugfix: Collar removal in kidnap minigame

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
when a character enters or leaves everyone gets updated this mess up appearance edition and slows down the update process, this pull request makes is so that only one character is updated
> ChatRoom enter leave

- BondageClub/Scripts/GLDraw.js
- BondageClub/index.html
Previously GLDraw used 2 canvases with double amount of texture, this has been fixed.
Normal and blink characters are drawn side by side on the same canvas.
> GLDraw Single Canvas

- BondageClub/Scripts/Dialog.js
restores the unlock button on self after my PR #741 while disabling unlocking lock on others while bound.
Known issue : Lovers and Owners can still remove every lock on their Lover/Sub while bound
> Hotfix unlock-struggle

- BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
This is the same issue as #744 - ensures leashes and other collar restraints are removed at the same time as the collar.
> Bugfix: Collar restraint removal in kidnap minigame

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
- BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
Added an OverridePriority setting for appearance item properties that will be checked first before the Asset's DrawingPriority and the Group's DrawingPriority.
In the case of the RopeCuffs and ChainCuffs options, the override priority will be set to 30 similar to MetalCuffs, instead of the default ItemArms' 32, so that the item is hidden behind clothes.
> #755 Fix: Override Priority setting to fix Rope/Chain Cuff clipping

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Character/Login/Login.js
- BondageClub/Screens/Inventory/ItemNeck/SlaveCollar/SlaveCollar.js
- BondageClub/Scripts/Dialog.js
- latex full lockdown now hides all ItemFeet
- When accepting the full collar, subs weren't updated properly, also reverted some unnecessary lines I added in a previous PR
- added color preview on slavecollar
- when choosing last expression of the list then relogging, some double expressions were built to the list, not cycling properly over the length of it, now fixed.
all those fixes have been partially tested
> More fixes

- BondageClub/Screens/Room/Magic/Magic.js
Allowing the gag to be applied in any of the three ItemMouth slots instead of only the leftmost one when required for tricks.
> Magic Theatre room gag slot fix

- BondageClub/Assets/Female3DCG/Female3DCG.csv
- BondageClub/Screens/Character/Player/Dialog_Player.csv
- BondageClub/Scripts/Dialog.js
Including the group/zone name in the text at the top right of the character interaction screen. 
E.g. "Select an item to use on the arms." or "Select an activity to use on the mouth."
This was intended to help #774 when a selected zone disappears offscreen, but could be useful to have in its own right.
> Body part names in the "Select item/activity" text

- BondageClub/Screens/Online/GameLARP/GameLARP.js
The item name for the RestrainLegs chat message is showing as "N/A" because it's checking ItemLegs instead of ItemFeet.
> LARP - Restrain legs item name fix

- BondageClub/Screens/Character/Player/Dialog_Player.csv
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
This adds the `/help` command and the `PgDn`/`PgUp` shortcuts to the text displayed when using the `/help` command. This is complimentary to a pull request in the server code that will send a `ChatRoomHelp` message whenever a player joins or creates a chatroom.
Complimentary server PR: Ben987/Bondage-Club-Server#28.
> Adds chatroom help text for /help command and PgUp/PgDown shortcuts

- BondageClub/Screens/Character/Appearance/Appearance.js
The default character in the New Character screen was mimicking the pose of the last shown sample character in the welcome screen, despite not wearing the items. Setting it to the default pose.
> New Character pose fix

- BondageClub/Scripts/Dialog.js
Applying an item to a kneeling/hogtied/etc player then clicking the Up button left the player hovering in the chat room screen. The position was only being reset when clicking out of the menu, but will now be reset when exiting due to item progress completing as well.
> Up Button Fix

- BondageClub/Screens/Inventory/ItemMisc/LoversTimerPadlock/LoversTimerPadlock.js
- BondageClub/Screens/Inventory/ItemMisc/MistressTimerPadlock/MistressTimerPadlock.js
- BondageClub/Screens/Inventory/ItemMisc/OwnerTimerPadlock/OwnerTimerPadlock.js
- BondageClub/Screens/Inventory/ItemMisc/TimerPadlock/TimerPadlock.js
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
An error occured whenever a player was wearing an item that has different type options, selected another character to open the character viewing screen, clicked on themselves on the left, and changed the type of their item. The item change would appear on the player's screen but not anyone else's, because the code was referencing the other character instead of the one actually affected.
> Item Type Change Fix

- BondageClub/Screens/Inventory/ItemArms/LeatherArmbinder/LeatherArmbinder.js
Colouring the extra straps in ItemHidden the same as the leather armbinder, checking whether it's been left at the default.
> Leather Armbinder Straps Colouring

- BondageClub/Screens/Inventory/ItemFeet/SpreaderVibratingDildoBar/SpreaderVibratingDildoBar.js
Load function was incompatible with locks. Should prevent all the reported menu crash/locks disappearing. (tested and it works fine with locks)
> Fix: inventory screen crash

- BondageClub/Screens/Room/MainHall/MainHall.js
- BondageClub/Scripts/Character.js
Certain assets which are lockable but are not restraints can effectively be permanently locked on right now using the combination lock. Management can remove some of these but not all of them. For example corsets and collars.
The main hall maid will not remove these and if they're locked by a combination lock by someone who won't share the code, they player is effectively stuck locked into the item unless they use the console.
With this change the maid will remove remaining combination locks after untying the player.
> Maid Combination Lock Removal

- BondageClub/Scripts/Drawing.js
When rendering the suspension pose in a chatroom containing more than 5 people, if the character is on the bottom row of the chatroom, their feet will "overflow" and be rendered above portions of the top row.
This change crops the image to prevent this overflow. Visually, it looks like the image below. 
Tested in single player & multiplayer with rope/chain suspension, as well as the water torture cell. Also tested that the cropping only affects the "Suspension" pose - no other poses are rendered differently.
> Bugfix: Prevents vertical overflow when rendering the suspension pose

- BondageClub/Screens/Inventory/ItemVulva/FullLatexSuitWand/FullLatexSuitWand.js
Fixed a bug where  locks and vibrations on the lockdown suit would collide and make the inventory crash (Like the spreader bar was fixed a couple days ago)
> Fix: Wand crash

- BondageClub/Scripts/Dialog.js
- Fixed how the lock menu is displayed so that the unusable locks are clearly labeled in gray like the other items (it used to send the lock at the back, but did not display the color so you could think you can use it but the click never registered)
This was caused because of how the sort order could never reach 3 which is what defines an item as blocked. Test with all types of items, locks, etc. with various permissions and now it all displays ok
> Fix: Locks inventory menu

- BondageClub/Screens/Character/Appearance/Appearance.js
Prevents the text from "sticking" making it so the appearance always keeps the first player's name when you inspect their appearance
> Fix: appearance text menu

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Scripts/Dialog.js
If viewing one character with the Up button, and other characters refresh during that time, those other characters are also moved up and then left hovering in the chat room (for the viewing player only) until refreshed again.
Now the variable tracks the currently viewed character's number, so that only that character is moved up.
> Up Button Refresh Fix

- BondageClub/Screens/Room/Prison/Dialog_NPC_Prison_Police.csv
An issue occured if a player fought the prison guard, was gagged in the fight and then lost. One of the dialog stages had entirely speech-only answers, and since none could be selected the game was softlocked. Now every possible path should have a silent/action option included.
> Prison Gagged Fix

- BondageClub/Assets/Female3DCG/Female3DCG.csv
After running a script (done by noname) to check which items were missing their description in the CSV, 8 were found and corrected in this PR. All of them had the wrong name/id in the file so they were properly replaced to make sure they were not missing.
> Fix: Wrong csv ids for assets

- BondageClub/Screens/Inventory/ItemArms/Web/Web.js
- BondageClub/Screens/Inventory/ItemHead/WebBlindfold/WebBlindfold.js
- BondageClub/Scripts/Common.js
- BondageClub/Scripts/ExtendedItem.js
- BondageClub/index.html
The motivation behind this PR is to make it simpler to create new extended items (specifically for items and restraints with multiple variations), and to make the extended item selection interface more consistent throughout the game. This has been done by refactoring the common functionality of extended item scripts into a single place, with some capacity for customisation.
This PR:
* Adds a new `ExtendedItem.js` script. This script contains a handful of functions useful for handling drawing and clicks for extended item selection
* Adds a new common function `CommonCallFunctionByName` in `Common.js` - this allows an arbitrary named global function to be called dynamically with any number of parameters. Similar to `CommonDynamicFunctionParams` but this function is intended to be called …
> Adds a new extended item script for consistency and ease of development

- BondageClub/Screens/Character/Login/Login.js
Due to my PR #882, lovers were unable to engage or marry after relogging.
Fixed that bug, but will require two relog (one in the new client, and another once the data has been updated).
The Multiple Lovers Server also fixes the problem.
This PR is intended as a hotfix, it will be useless once [#30](https://github.com/Ben987/Bondage-Club-Server/pull/30) is accepted
> hotfix : lovers stuck

- BondageClub/Scripts/Inventory.js
- BondageClub/Scripts/Server.js
when using a lover/owner lock on self, only possible if the player has a lover/owner, it will now use the memberNumber of the player.
to make it clear for owners/lovers when someone unlocked themselves behind their backs and so on
> Fix : Owner/Lover Lock on self

- BondageClub/Screens/Character/Login/Login.js
The slave collar check would cause infinite refreshes if the collar was invalid (something coming from NPCs) when in chatrooms. This only syncs the slave collar to make sure the whole character does not keep being refreshed back and forth. This way people don't have to break with a NPC if they want to go in a chatroom
Tested with someone who had the "can't kneel or do anything" bug and it fixed it.
> Fix: Infinite refreshes

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Inventory/ItemHead/OldGasMask/OldGasMask.js
Made it so the mask addons do not block the mask itself, allowing you to lock both independently and to remove the mask while wearing an addon to avoid confusion 
We'll see, if there is more confusion during beta I'll think of what else can be done, for now I'm just thinking of a text message on the item menu to say x rectangle contains addons. This change is already much better regardless 
Only reason I did not add a "remove addon" button on the mask itself is because the lock for removing the item would need to be handled there and it's less future-proof and way messier. 
Maybe a button "go to addons" ? It would change the focus to null and display the addon section like if you clicked on it yourself. Let me know what you think.
> Change: Remove addon on remove

- BondageClub/Scripts/ExtendedItem.js
There was a small bug in the way the new extended item script was attempting to retrieve the previously selected type, meaning the web action text would always say "loosens" instead of toggling between "loosens" and "tightens" as appropriate.
> Bugfix: Fixes chatroom action text when changing web type

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
Made it so instead of removing items, it will simply not allow the owner to send their sub to the maid quarters.  It will also prevent unusual items with a gagging effect from causing problems in the future. I also think it's an improvement to let the players decide whether or not they should remove the gagging items.
The added check sub-side is to prevent an owner from soft locking their sub through the console by bypassing the check
> Improvement: Forced labor

- BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
Like we spoke It's been a frequently raised concern that the ban list only allows +/- 42 banned players considering the growing list of trolls. This has led many to use console to ban players to bypass this restriction caused by the UI.
I think it is a needed quality of life  change, and it will also be safer for people who are not familiar with the console.
> Ban list size

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
If "/me" or "\*" is followed immediately by a "'" or "," no blank is inserted in front of the emote.
So "*'s tail swishes" will now result in "Sandrine's tail swishes" instead of "Sandrine 's tail swishes"
> New emote behaviour

- BondageClub/Screens/Inventory/ItemFeet/HempRope/HempRope.js
- BondageClub/Screens/Inventory/ItemLegs/Chains/Chains.js
- BondageClub/Screens/Inventory/ItemLegs/HempRope/HempRope.js
- Fixed the displayed text for hemp rope feet 
(It said "required level null" instead of "no requirement" like everything else does)
> Fix: null text

- BondageClub/Screens/Character/Player/Dialog_Player.csv
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Dialog.js
This is linked to the server PR [#33](https://github.com/Ben987/Bondage-Club-Server/pull/33)
This allows the administrator of a chat room to click on themselves and perform the Swap, Move Left or Move Right admin actions.
This prevents the fairly regular occurence of admins who disconnect and want to move back to the top-left having to move every other character to the right to do so.
> Admin Actions on Self

- BondageClub/Assets/Female3DCG/Female3DCG.js
This was causing toe tape type changes not to be propagated to other users in a chatroom.
> Beta Bugfix: Missing AllowType property in toe tape asset definition

- BondageClub/Scripts/Dialog.js
When the struggle screen is exited, either by escaping or hitting the Exit icon, any audio that's playing ends. However this didn't cover the case where the screen was exited by hitting the Esc key. This currently only occurs for hemp & nylon ropes which have a 37 second long audio file that would play in full. The call to end the audio has been moved and now all 3 exit methods are covered.
> Struggle Audio Fix

- BondageClub/Scripts/Dialog.js
As reported by Ace in discord [here](https://discordapp.com/channels/554377975714414605/554378725916147722/722614848374046792).
1. Inside a chatroom, click a character
2. Click an item slot on that character
3. Click the color picker, but **do not** click inside the color picker square or otherwise select a color
4. Hit the escape key
5. You should now be back in the character dialog menu - click **anywhere** on the screen
6. The following will be printed in the console every frame:
```
Uncaught TypeError: Cannot read property 'Name' of null
at DialogChangeItemColor (Dialog.js:992)
at Dialog.js:1056
at ColorPickerNotify (ColorPicker.js:128)
at HTMLDocument.ColorPickerPickSV (ColorPicker.js:114)
```
This is due to the color picker mouse event listeners not being removed when it is closed …
> Bugfix: Exception and potential game crash when cancelling out of the color picker

- BondageClub/Assets/Female3DCG/Female3DCG.js
Setting the bed straps addon in the ItemArms group to have Random off so that it's not selectable in LARP games. Otherwise it appears in mid-air with no bed to attach to!
> Bed Strap LARP Fix

- BondageClub/Screens/Character/InformationSheet/InformationSheet.js
Fixes a slightly unintuitive behaviour of the new character information sheet.
Steps to reproduce:
1. View a player's character information sheet
2. Change to page 2
3. Exit
4. View a different (or the same) player's information sheet
5. Notice that the information sheet is still on page 2
6. Change back to page 1
7. Exit and view a different (or the same) player's information sheet
8. Notice that the information sheet is back on page 1
I'd expect the information sheet to reset to page 1 each time, which is what this PR does.
> Resets character information sheet to page 1 upon exit

- BondageClub/Assets/Female3DCG/Female3DCG.js
Removed LegsOpen from the AllowPose for both these items as the assets for them are not different (LegsOpen is the same as the base pose) which caused those two items to disappear when used with one bar, saddle stand and several other items that set the pose to LegsOpen due to more 404s in a folder which doesn't (and should not) exist
> Fix: AllowPose for ball and shackles

- BondageClub/Scripts/Character.js
- Made it so the description is refreshed when someone updates their description
This has been a major inconvenience for a while, you cannot see someone's new description until you relog because it was never a flag for a character refresh. This makes it so each time someone changes the description, everyone else will see it without having to relog. No need the desync is also quite confusing when people expect you to see (or not to see) certain information
To test how inconvenient it is right now, you can have two characters in a room, #1 changes their description and #2 will never see it, no matter how many rooms you go in with them, unless you relog.
> Improvement: Description refresh

- BondageClub/Scripts/Character.js
- Fixed a bug where the client would crash when trying to click on an online player's dialog options
Due to how functions in the dialog sheet is built, online characters **entering a room you are in for the first time while you are logged in** while you are in a screen other than the chatroom screen (like your friend list) will build the dialog with the wrong function names, causing the dialog options to crash. This fix ensures that any Online character is loaded with the ChatRoom prefix instead of the CurrentScreen.
Tested with self dialog, NPCs and online characters with no apparent side effects.
See [issue 878282](http://www.hostedredmine.com/issues/878282)
> Fix: online dialog builder crash

- BondageClub/Screens/Inventory/ItemMisc/OwnerTimerPadlock/OwnerTimerPadlock.js
if a sub applies an owner lock on herself, her owner should be able to modify it and not the sub
bug introduced due to the member of the sub on any locks self applied
> fix : owner locks check for member number

- BondageClub/Screens/Room/Stable/Stable.js
- Fixed a typo in a stable.js function that caused the dialog to crash when it was called
https://discord.com/channels/554377975714414605/554378725916147722/725455652196974672
> Fix: pony training dialog crash

- BondageClub/Screens/Inventory/ItemHead/WebBlindfold/WebBlindfold.js
The web blindfold publish function was missing a parameter, resulting in "((You can use or remove items by selecting specific body regions on yourself.))" messages when its type was changed.
> Bugfix: Missing action text when changing web blindfold type

- BondageClub/Scripts/NPC.js
Since every trait pair for new NPCs in the private room has an independent chance of being generated, there's a very low but non-zero possibility (0.07%) that no traits are generated at all. This can look like a bug to players and one such instance has been raised as an error.
Perhaps this is intended and a trait-less NPC is an acceptable possibility. But in case not, I've added a check so that the trait loop will repeat until at least one trait is assigned.
> NPC Trait Guarantee

- BondageClub/Scripts/Character.js
- BondageClub/Scripts/Speech.js
Unlike the various gagging items, multiple layers of deafening items do not add up. This PR changes this and solves issue [#877137](http://www.hostedredmine.com/issues/877137).
This PR does two things
**`Character.js`**
* adds a function `GetDeafLevel` to the Character this function loops through the Appearance of the character and sums up the various deafening level. The function returns the current level of deafness
* The values are defined in constants:
* `CCharacterDeafLevelFactorLight = 1`
* `CCharacterDeafLevelFactorNormal = 2`
* `CCharacterDeafLevelFactorHeavy = 3`
* `CCharacterDeafLevelFactorTotal = 4`
**`Speech.js`**
* replaces the various calls of `IsDeaf` by `GetDeafLevel` and compares the result with the appropriate level of deafness. If a certain level is reached, the …
> Feature: Levels of deafness add up

- BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
- BondageClub/Screens/Online/ChatAdmin/Text_ChatAdmin.csv
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- added the ability to manually ban your ghostlist and blacklist after a room was created.
- improved the logic of autoban/quickban to remove duplicate numbers
- extracted it into a function
- changed the "selection" button so it is now properly grayed out like the rest for non-admins
As pointed out to me by others after adding auto-ban, this is useful when you recently ghosted/blacklisted someone, but it is especially useful for when there are more than 1 admin. It concatenates new numbers to the list to avoid duplicates and provides for an easier way to ban. Truly removing the need to maintain a separate list of member numbers for trolls.
> Improvement: Quickban

- BondageClub/Screens/Character/Appearance/Appearance.js
- made it so the amount of page is tied to the amount of groups you see, not the total amount of groups
Currently, if you go to change someone else's clothes, you will cycle through pages until you end up on a blank page because the body parts are not rendered. This removes any blank page(s) created by the non-rendered groups
> Improvement: Removed appearance blank pages

- BondageClub/Screens/Character/Creation/Creation.js
Currently, the server uses the following regex to validate account names:
```js
/^[a-zA-Z0-9]+$/
```
Whereas the client uses this regex:
```js
/^[a-zA-Z0-9 ]+$/
```
This means that users can attempt to create an account with a space in the account name, receive a "Creating your character..." message, but the server will silently reject the account creation, making the screen appear to hang.
This changes the client-side regex to line up with the server-side one, so users will now receive the "Invalid character, account name, password or email" message instead.
> Bugfix: Client-side check for spaces in account name during account creation

- BondageClub/Scripts/Audio.js
This PR does two things:
1. Prevents javascript errors in audio playback that would occur under certain circumstances
2. Reworks the audio playback level calculation a little for slightly finer-grained audio level differences, and also to incorporate the new stackable character deafness levels
This requires 2 characters in a chatroom: A and B (have the console open on character A's browser tab/window).
1. Apply any item that has the `DeafHeavy` effect (e.g. heavy duty earplugs) to character A
2. As character B, equip a vibrating item on yourself
3. As character B, set the vibrating item to "Low"
4. Observe that no sound plays for character A, and character A's console displays the following error:
```
Uncaught DOMException: Failed to set the 'volume' property on 'HTMLMediaElement': The …
```
> Bugfix: Prevents errors in audio playback

- BondageClub/Scripts/Speech.js
With the new stackable deafness levels, it is now relatively easy to stack deafness levels of 5 or over. This is a simple change that adds additional levels of speech garbling for deafness levels of 5 or more.
I've tested this with all levels of deafness currently attainable in the game, and garbling looks like this:
| Deafness Level | Speech |
| ---------------- | -------- |
| 0 | T-The quick b-brown f-fox jumped over the lazy dog |
| 1 | e-ehe kuiek b-baown h-hok aumpem ovea ehe aasy mom |
| 2 | e-ehe kuiek e-eaoan m-mok aumfem oeea ehe aaha mon |
| 3 | e-ehe keeka f-faeam m-mek aemfem efea ehe aehe mem |
| 4 | m-mmm mmmmm m-mmmmm m-mmm mmmmmm mmmm mmm mmmm mmm |
| 5 | m-mmm mmm m-mmmmm m-mm mmmmm m mm mmm mm m mmm |
| 6 | m-mmm mmm m-mm m-m m mm mm m mm mmm mm mm |
| 7 | m-m m m-m m-m …
> Feature: Adds additional levels of speech garbling for very heavy deafness

- BondageClub/Scripts/Drawing3D.js
Many of the game's keyboard event listeners are added to the main game canvas element (i.e. anything added through `CommonKeyDown()` - the A/S key in the struggle dialog being a prime example). Because the new 3D canvas is rendered on top of the existing game canvas, it essentially traps keyboard events and prevents them triggering on the main canvas.
This is a simple fix that adds `visibility: hidden` to the 3D canvas when it is not being used, so that it will no longer capture events. It's not a particularly sophisticated fix, but I'm aware that the 3D stuff is very liable to change as it's so new, so this should be good enough to keep the main game working in the meantime.
1. Equip/remove any item with a moderate wear/remove time
2. Attempt to speed up the process by pressing the A/S …
> Bugfix: Prevents the 3D canvas from blocking keyboard events on the main canvas

- BondageClub/Screens/Inventory/ItemDevices/BondageBench/BondageBench.js
- BondageClub/Screens/Inventory/ItemHead/OldGasMask/OldGasMask.js
- BondageClub/Scripts/Inventory.js
There was an issue with the bondage bench straps and old gas mask addons that meant that if the player had the items set to limited permissions, then nobody would be able to use those addons (even if they were owner/lover/on the player's whitelist). This fixes that.
Requires 2 characters: character A, and character B
1. As character A, set global item permissions to "Everyone", "Everyone, except blacklist" or "Owner, Lover, whitelist & Dominants"
2. As character A, set item permissions for the bondage bench straps in the addon slot to limited
3. As character A, add character B to your whitelist
4. As character B, add the bondage bench to character A
5. As character B, attempt to add the bondage bench straps to character A
6. Notice that character B is unable to add the straps, despite …
> Bugfix: Fix to limited item permissions for bondage bench/gas mask addons

- BondageClub/Screens/Character/BackgroundSelection/BackgroundSelection.js
This fixes a small issue with the behaviour of the previous button in the background selection code, where clicking on the button when on the first page would take the user to the penultimate page rather than the last page.
1. Enter the background selection screen
2. Immediately press the "previous" button
3. Notice that the backgrounds displayed are not the last page of backgrounds, but the second last
> Bugfix: Behaviour of previous button in background selection

- BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- fixed a bug where the chatroom limit would be reset to 10
Currently there is a bad check at line 855 on the server. Because the server sends back the data as an int and the check contains `(typeof data.Room.Limit !== "string")` The already correctly formatted value is reset to 10. I assumed you prefer the fix client side which is contained in this PR (see ChatRoom.js file), but thought I should inform you of that regardless
- improved the chatroom admin screen so that it does not forget the input values when going in background selection (ChatAdmin.js)
> Improvement/Fix: Chatroom admin

- BondageClub/Scripts/GLDraw.js
- fixed WebGL draw canvas missing relevant listeners for context lost/restoration which caused the club to be broken if your GPU runs out of resources
Tested and it works as intended. I also verified and the 3D Draw already properly listens for these events.
Note: if you test with the .loseContext() method, you need to use the .restoreContext() method on the same context afterwards as it won't come again by itself when you trigger it manually. (Otherwise you can always run a VM and crash the GPU on it to test in a real scenario.)
On this note, we should probably think about limiting the texture cache for those who stay on the club for a while. The more assets we had, the more often this will occur.
See issue [878403](http://www.hostedredmine.com/issues/878403)
> Fix: WebGL context

- .gitignore
Not personally a problem for me, as I don't use VS Code, but I did just have to walk someone through some git to work around the fact that the directory isn't ignored. This should make life a little easier for some VS Code users.
> Adds .vscode directory to .gitignore

- BondageClub/Scripts/Skill.js
- added JSDoc comments to Skill.js
Let me know if any description can be improved.
I also removed the `SkillModifierReset` because it is actually never called anywhere in the whole project, it's also not very useful at the moment.
Allso, I knew about this but never quite realized how frequent these occured: `for-if-return loops` are less optimal than using `.find`, on top of `.find` taking less space for smaller operations. There could be a meaningful performance gain for core functions handling very large arrays like Dialogs and Assets
> Improvement: JSDoc comments added to Skill.js

- BondageClub/Scripts/Reputation.js
- added JSDoc comments to Reputation.js
Let me know if any description can be improved.
- cleaned up the `ReputationSave` method
I also did a quick refactor to remove the `ReputationSave` method. It dates back from a long time ago as seen in the git history. It's essentially useless, you can see the parameter was not even taken into account. So the two spots it was used for were changed in favor of a direct call to `ServerPlayerReputationSync`
> Improvement: JSDoc comments added to Reputation.js + Refactor

- BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
When selecting a chatroom background via the back/forward buttons, the button hover displays underneath the ban list textarea. As it's currently impractical to display the hover text over the textarea (this would probably need another canvas to be temporarily rendered), this change adjusts the layout of the screen slightly to ensure that the hover doesn't overlap by slightly reducing the size of the background preview image. See screenshots below.
*Current layout:*
*Adjusted layout:*
> Bugfix: Adjusts the chatroom admin screen to prevent hover overlap with textarea

- BondageClub/Screens/Inventory/ItemButt/ButtPlugLock/ButtPlugLock.js
Removed the seemingly uneeded check for "StraitDressOpen" and replaced it with "BlockKneel" as it made more sense and still prevents the Mermaid Suit from having issues.
> Fixes for the Short Chain to allow use with Bitchsuits & Strait Dresses 

- BondageClub/Screens/Inventory/ItemArms/Web/Web.js
The new web cocoon type doesn't currently hide the `ItemBoots` slot. This fixes that, and also hides a few other slots that shouldn't be visible.
> Bugfix: Hides boots (and some other items) with the new web cocoon

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Scripts/Inventory.js
A recent change to have assets inherit the Effect property from their asset group caused an issue with handheld toys. They're getting effects such as Prone on legs, which is preventing the message/activity from being sent to the chat.
The effect check will now look at the length so that the asset-group-level setting can be overridden at asset-level with an empty array.
> Handheld Toy Effect fix

- BondageClub/Scripts/Dialog.js
- BondageClub/Scripts/Inventory.js
Unlike regular items, locks don't show as 'worn' in the inventory permissions screen at the moment, so they can always be changed. Since the lock validation removes locks the user has blocked, players can remove locks they're currently wearing by changing its permissions.
Now if a player is wearing a given lock anywhere, that lock will be greyed out in the permissions screen.
> Lock Permissions Blocking

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
- fixed an issue where item prerequisites were not taken into account when using the save state
The save state function did not reset the active pose. This means that many items were broken when they required the character to be kneeling/standing. Instead of bloating the asset files and creating a bunch of conflicts, and to be more futureproof, I've added the pose to the list of things it. This means all items will work retroactively, and new items won't need to worry about this feature.
To reproduce the current bug. You can wear a vacbed/stock/bed and many more in the main hall, go into a room, then remove the item, then kneel, then use your safeword. You'll be stuck
https://discord.com/channels/554377975714414605/731199817111568384/731478171349811230
> Fix: Active pose

- BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
Follow-on fix to #1047 -  I moved the buttons, but forgot to move the click handlers for them! This fixes that.
This also removes a declaration of the `ChatAdminPrivate` variable, as it was being declared in two places (lines 4 and 7).
> Bugfix: Corrects the coordinates for click handlers in the chatroom admin screen

- BondageClub/Assets/Female3DCG/Female3DCG.js
As suggested, I've moved the two new latex leotards into the same BuyGroup - speaking with Cecilia, they were intended to effectively be two views of a "reversible" leotard - one worn backwards, and one forwards, so I think this makes sense (and will help players out financially).
> Moves the two new latex leotards into the same BuyGroup

- BondageClub/Scripts/ExtendedItem.js
This updates the JSDoc for `ExtendedItem.js` in line with the agreed JSDoc conventions. No code has been changed.
> Improvement: Updates JSDoc for ExtendedItem.js

- BondageClub/Scripts/Character.js
- fixed an issue with `Player.GetDeafLevel` that caused extended item effects to be overlooked
The get deafness method never took extended properties into account which prevented headphones from working properly (both old and new ones) This will make it more futureproof
> Fix: Player get deaf level

- BondageClub/Assets/Female3DCG/Female3DCG.js
This fixes the gag clipping issues, reported here:
https://discord.com/channels/554377975714414605/731199817111568384/732414436240785500
To achieve this, the following priorities were altered:
- `HairFront`: 51 (was 44)
- `Hat`: 52 (was 46)
- `Emoticon`: 53 (was 50)
Tested this on my local instance with various combinations of gags, hairs and hats.
> Fix: Gag clipping issues

- BondageClub/Screens/Inventory/ItemMouth/DildoPlugGag/DildoPlugGag.js
- BondageClub/Scripts/ExtendedItem.js
This pull request does a few things:
* Fixes a bug where the incorrect `Effect` was being added to the Dildo Plug Gag in its extended item load function
* Updates the Dildo Plug Gag to use the extended item script
* Updates the extended item script to not reassign properties of extended item option objects
* Updates the extended item script to handle locked items
> Improvement/Bugfix: Refactors the Dildo Plug Gag to use the extended item script

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
- BondageClub/Scripts/Character.js
- optimized how online characters are saved to removed instances of characters that are no longer present within your room. 
A few functions require to loop through the character array, and it would quickly grow over several hundreds easily the longer you stayed online and the more rooms you went in.
There was also an oversight where if you log back in, a new entry would be created for you in everyone's character array since your online ID changed.
There are a few ways to go on about it, I thought about just fixing the duplication problem, but then I thought about saving only X amount max and get rid of the old ones, but in the end, I found no good reason as to why we would need to keep online characters that are not within the room so I went with trimming as much as possible to optimize …
> Improvement: Character array optimizations

- BondageClub/Screens/Inventory/ItemArms/BitchSuit/BitchSuit.js
- BondageClub/Screens/Inventory/ItemArms/FullLatexSuit/FullLatexSuit.js
- BondageClub/Screens/Inventory/ItemArms/MermaidSuit/MermaidSuit.js
- fixed an issue where the suits would not load with their intended effects
The normal petsuit, the latex lockdown suit and the mermaid suit currently render the zip state first but do not block the zones until we unzip/zip them again. This fixes the issue
> Fix: zipped suits behavior

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Character/Preference/ActivityDictionary.csv
This PR does two things (based on occasional requests I've seen around discord and the club):
* Allows the `FrenchKiss` activity to be used with open gags (e.g. ring gags, etc.)
* Enables the `Lick` activity on the `ItemVulva` zone
> Feature: Minor mouth activity enhancements

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
When a player changes clothes, applies a restraint or activates the whisper function (for example), the text input field looses its focus and the player has to actively click into it, before entering their chat message.
This change catches the keyDown event and activates the text area before sending the key there, thus helping the game flow.
* added an if statement to `ChatRoomKeyDown` in the `ChatRoom` script that transfers focus to the text area
* tested it locally with one player, as this only changes the client behavior
> Improvement: Auto focus text area in chat

- BondageClub/Scripts/ExtendedItem.js
This PR makes a few small improvements to the extended item script:
* Adds handling for when an extended item has a `Property` but not `Property.Type` - this fixes a bug with the dildo plug gag (reproduction steps below)
* Replaces usages of `MouseX`/`MouseY` bounds checking with the `CommonIsClickAt` function
* Updates some of the JSDoc to clarify the script's behaviour
1. Add a dildo plug gag to a character (can be yourself or another character)
2. Exit the extended item menu (do not select an option)
3. Lock the dildo plug gag
4. Enter the extended item menu and attempt to select an option
5. Note that selecting the option doesn't work
The following error is shown in the console:
```
ExtendedItem.js:126 Uncaught TypeError: Cannot read property 'Property' of undefined
at …
```
> Bugfix: Fix for the extended item script when a Property is present without a Type

- BondageClub/Scripts/Dialog.js
This change applies a color code on restraints that cannot be used on a character, at the moment, either because of worn clothes or other restraints that are currently in use. The items in the inventory are additionally sorted in the following order
1. The worn item
2. Items that can be used (white)
3. Items that cannot be used (gray)
4. Items that are blocked (red)
This solves the issue [#881151](http://www.hostedredmine.com/issues/881151) and is based on a proposal by [Senken](https://discord.com/channels/554377975714414605/554378904308023297/732294616182816831)
All changes were done in file `Dialog.js`
* changed the hard coded sort order of different groups to constants so that additional groups can be added later more easily
* added a distinction of cases in function …
> Improve: Coloring of unusable restraints

- BondageClub/Scripts/Dialog.js
The step to remove items that are no longer worn is an issue for locks since they don't actually occupy the ItemMisc slot. It prevents the extended screen from opening on hitting the Inspect Lock menu button.
> Inspect Lock Fix

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
This change was mostly prompted by the comments on #1115.
This makes some minor optimisations to the `ChatRoomCharacterItemUpdate` function by setting fields to `undefined` rather than `null` if they should not be set. This will prevent the field from being sent in the websocket message. I've tested this in as many ways as I can think of and not seen any unexpected behaviour. I've included before/after examples of the websocket message changes below - these are all recorded from the actual websocket messages being sent by my browser. As you can see, this reduces the message size on item additions, removals and updates, and as far as I've seen, doesn't cause any issues with gameplay.
Note that the changes in #1115 will only send the `Property` field when the `CharacterRestricted` is …
> Improvement: Prevents null fields from being sent in chatroom item updates

- BondageClub/Screens/MiniGame/Tennis/Tennis.js
- BondageClub/Scripts/Timer.js
- fixed an issue with 144hz monitor and the tennis minigame
The current tennis minigame moves the ball forward with every frame, causing it to move WAY too fast on 144hz monitors. I dont have one myself but I've tested with a 30FPS  cap on 60FPS, and the ratio method makes it so the ball moves smoothly. This makes the minigame playable when the current  FPS is higher than ~60.
At first I wanted to skip a frame, but that actually didn't look smooth. Capping the club to 60FPS would have been an option, but I don't think it would have been needed.
If there are other games affected by this, a similar fix should work. I'm not knowledgeable in singleplayer stuff, so if anyone mentions them, I can have a look.
> Fix: Framerate in the tennis mini game

- BondageClub/Scripts/Character.js
- BondageClub/Scripts/Dialog.js
Lover-only locks will now only appear as options for a player on herself if she has at least one non-NPC lover.
This is in response to a player reporting in the discord server that they'd self-locked themselves, and both the NPC and maid could not remove it.
I suspect there are still potential cases for self-bondage irreversible-locking where a player has only NPC lovers or owners, but this would require investigation.
> Self Lover Locking Fix

- BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
- BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
This fixes a minor issue in the cuff variants of the hemp rope and chains arm items to ensure they are drawn below the `Cloth` slot.
1. Equip any piece of clothing with the default priority of 30 which would clip with the aforementioned cuff variants (the teacher outfit works well)
2. Equip the hemp rope/chains arm item
3. Select the rope cuffs/chain cuffs type
4. Note that the rope/chains render above the clothes rather than below
> Bugfix: Fixes for the OverridePriority of hemp rope and chains cuff variants

- BondageClub/Scripts/Dialog.js
The step to rebuild the item/activity menu whenever the target character's appearance changes has been corrected to account for when the player focuses on themselves on the left instead. The menu wasn't appearing before.
> Self Target Menu Fix

- BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
This fixes a bug where equipping a spanking toy on another player would not initially draw the toy (the crop in the case of initial equip).
1. Enter a chatroom with another character
2. Equip a spanking toy on the other character, but do not select another toy type
3. Note that the toy does not get drawn
> Bugfix: Ensures spanking toys are always drawn on initial equip

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- changed how the wait time was handled to avoid the club from freezing
currently, changing your lists freezes your club for a second on purpose which was a quick fix for item permissions. This increases the time to avoid conflicts and will remove the freeze to make it a lot less annoying. I still believe we should have some kind of response sent back to the server to do a proper async callback, but this can do for now.
> Improvement: CommonWait

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Scripts/Asset.js
- BondageClub/Scripts/Dialog.js
This moves equipped handheld items to the front of the inventory list, since the players will likely want to use it more than the other options and currently have to often trawl through multiple pages to find it.
> Handheld Item Order

- BondageClub/Screens/Character/OnlineProfile/OnlineProfile.js
- BondageClub/Screens/Character/OnlineProfile/Text_OnlineProfile.csv
- added JSDoc to OnlineProfile.js
- added the option to leave without saving
When viewing your own profile, you have to logout if you need to revert your changes, this change allows you to exit without saving.
JSDoc wise, it seems like we have finished /Scripts , /Character, /Cutscene. On top of that, /Online, /Room and /MiniGame are fairly advanced to so we're getting closer to be done with this. 
We'll just have to comment properly from now on to avoid having to play catch up like we're doing right now. We're probably also going to do some guides on how to add basic things like items and such. Hopefully this will be enough to get people started and understand everything better
> Improvement: OnlineProfile.js

- BondageClub/Scripts/Inventory.js
- made NPCs listen to the player's permissions
Currently, NPCs bypass blocked items which some players have complained about in the past. Any specific case can't necessarily be fixed, but at least all calls to the randomwear function will properly check and remove blocked items from the random pool which solves nearly all cases. 
Due to how the limited system works, I can't factor in limited items for NPCs.
This makes it so any blocked item will not be used UNLESS, there is nothing BUT a blocked item that can be used. This is not necessary, but I made it this way to prevent someone from cheating by blocking all restraints. If you think it is not needed, I can remove that concept and always remove blocked items from the pool. The odds that someone blocked all the basic items that could be …
> Improvement: Thoughtful NPCs

- BondageClub/Screens/Character/Relog/Relog.js
- BondageClub/Screens/Room/MainHall/MainHall.js
- preloaded the CSV for the reconnection screen in the main hall
- removed the possibility to show duplicate messages
- replaced click conditions to use MouseIn
Currently, the "Enter your password..." message displays twice if this is what the server sent back, so I added a check to avoid this from happening. 
Also, if you actually disconnect, the screen is just 3 white boxes because you fail to fetch the CSV, this fix makes it so when you run the main hall, it will fetch the CSV and cache it so you will have the text available if you DC later which will make sure the page displays properly in all cases of disconnections.
> Improvement: Relog screen

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Character.js
This changes all checks against the `DeafLight`, `DeafNormal` and `DeafHeavy` effects in the code to use`Character.GetDeafLevel` instead for consistency. This also fixes a small bug that has come about with the recent deafness changes where a player would not be counted as being in sensory deprivation if deafened with three items with the `DeafLight` effect rather than a single item with the `DeafHeavy` effect (which sum to the same deafness level of 3).
The easiest way to see the bug is to set sensory deprivation levels to "Total", then equip three `DeafLight` items, and notice that total sensory deprivation effects aren't applied. For example, the following three items reproduce the effect:
* Light earplugs
* Polished Steel Hood
* Display Case
> Bugfix: Changes deafness and sensory dep definitions to use GetDeafLevel

- BondageClub/Scripts/Dialog.js
- made it so the eye toggle actually maintains the same eye expression
I purposefully made it so you can't mix and match expressions because they don't work well together in the first place, but forgot the toggle would re-open this possibility. This fix makes it so instead of opening the eye, it just sets it to the same expression.
If both eyes are closed, it will just open them as normal to be a lot more user friendly and keep the intended design.
> Fix: winking matching eyes

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
When an applied item is updated through ChatRoomCharacterItemUpdate, the difficulty is refreshed using the player's bondage skill. However this player may not have applied the item originally and will often be just adding a lock or changing the colour, making the base escape difficulty quietly increase or decrease when we'd expect it to stay the same. (Note: difficulty increases from locks are not stored in this number).
You can recreate this easily by having A tie B, then having C with a different bondage skill to A make any trivial change to the item. The escape difficulty changes.
I couldn't see any cases where we actually want this difficulty change to happen. I've changed the formula to be the difference between the asset difficulty and applied difficulty (original skill + asset …
> Difficulty Consistency Fix

- BondageClub/Scripts/Character.js
- fixed a crash with character release total when the slave collar had no property object
This caused the safeword to break when your collar had no property. It's an edge case, but it is possible. Usually this happens when the collar is replaced by the client through validation.
> Fix: Character Release Total

- BondageClub/Screens/Character/Login/Login.js
- BondageClub/Scripts/Asset.js
- BondageClub/Scripts/Dialog.js
- added login validation to remove non-valid data from the permission arrays to maintain data integrity
currently you can push anything to those arrays and it will be saved permanently, moreover, with items changing slots and the likes, it's important to make sure we don't keep a lot of data we do not need in the db. 
For example, all the hoods being moved will require people to re-blacklist them, but the old entries would stay in their array forever unless this change is approved. The server sync will only be triggered to remove bad data someone may have pushed through console, or when changing club version to clean up from changes.
I extracted it into a separate function in case we ever have more things we wish to cleanup that follow the same pattern
> Improvement: Clean up permissions

- BondageClub/Scripts/Drawing.js
- fixed the arousal meter being drawn before the suspension offset is applied which caused its hitbox to be in the wrong place
Currently, if you are suspended, the thermometer is drawn in the wrong spot so your clicks don't register like they should.
I also moved the online dynamic draw function in case there is ever a click handler on those as it would cause the same issues. For now, that one line being moved does not change LARP
As reported here -> https://discord.com/channels/554377975714414605/554378725916147722/739203452449587220
> Fix: Thermometer + Suspension

- BondageClub/Screens/Character/Login/Login.js
- reduced the amount of inventory sync calls on login to 1 max.
Currently, every login triggers 2 inventory sync, and has the odds of triggering even more, This removes all of them in favor of only one sync. This singular sync only occurs if the player actually had something changed in their inventory.
I also have two questions:
1- The following line seems useless to me, but I saw you added it so I thought I would ask. I understand this was added when a new maid outfit was available, but with the buy group validation, this item will be earned automatically for anyone with the base maid outfit since they share the same buygroup. I tested and had no problem without this line.
`if (LogQuery("JoinedSorority", "Maid") && !InventoryAvailable(Player, "MaidOutfit2", "Cloth")) InventoryAdd(Player, …
> Improvement: Reduced inventory sync calls

- BondageClub/Screens/Room/KidnapLeague/KidnapLeague.js
- BondageClub/Screens/Room/MainHall/Dialog_NPC_MainHall_Maid.csv
- BondageClub/Screens/Room/MainHall/MainHall.js
- BondageClub/Screens/Room/Management/Dialog_NPC_Management_Mistress.csv
- BondageClub/Screens/Room/Management/Management.js
- BondageClub/Scripts/Inventory.js
Up to now, most NPCs pay no real respect for lover locked items and mostly ignore them. This fix tries to change that.
This has been reported as [#877698](http://www.hostedredmine.com/issues/877698).
Six files were changed to achieve that. The changes are as follows
* Added a new function `InventoryCharacterHasLoverOnlyRestraint` that checks for lover restrained items, similar to `InventoryCharacterHasOwnerOnlyRestraint`
* At the end of a battle, the lover locked items are not removed, likewise to the owner locked ones
* Added a new function to check, if the player wears either lover or owner locked items
* The rescue maid now asks the player, if she really wants to get rid of her lover locked items, but if the player agrees, she will not get punished
* Added a new function to check for …
> Fix: Respect for lover lover locks

- BondageClub/Screens/Character/Appearance/Appearance.js
This PR fixes a minor bug where the appearance screen text would not be reset after accepting changes to a character's appearance.
1. Change character A's appearance and accept the changes - note that while in the appearance screen the text should say "Select Character A's appearance"
2. Enter the appearance screen for character B - note that the text still says "Select Character A's appearance", rather than "Select Character B's appearance" (or "Select your appearance" if character B is yourself)
> Bugfix: Resets character appearance text when accepting appearance changes

- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
- BondageClub/Screens/Room/MainHall/MainHall.js
- fixed a visual stutter when re-entering a chatroom caused by a desync in the activepose
It took me a while to pin point what was going on here, but here goes:
Currently, going back to the mainhall changes your active pose without syncing with the server, this means that if you were kneeling before going in the main hall from a chatroom, it was not saved on the server.
This caused a visual stutter when entering a room -> the character is refreshed with the old pose (kneeling) then refreshed again with the right pose (standing). causing unnecessary redraws.
This fix makes sure to sync with the server only if necessary, so it will not trigger a bunch of active pose syncs for no reason.
> Fix: chatroom visual stutter

- BondageClub/Scripts/Dialog.js
- optimized the interruption message to not send any if the player never progressed through the action (this prevents a message from being sent if a character was sitting on it.)
- improved how changes are handled while refreshing the screen to retain the current page and to take every possible changes into consideration.
With the new inventory colors change, I wanted to improve the new refresh system ahead of the beta so that is is more consistant. This means that it takes into account changes in the blocklist, limited list and active pose to always reflect the correct status.
This prompted me to change the inventory build function to take a possible offset. This means you will stay on the given page when rebuilding the screen to avoid having to scroll back constantly. This greatly …
> Improvement: Inventory screen refresh

- BondageClub/Scripts/Server.js
- fixed a scope issue when validating combo locks
We were testing the for let change and we already identified several code issues where it was already not working or broke because the code relied on bad practices. After fixing 2-3 of them, all the code runs fine after switching the 900 for-var loops as far as I can see for now, and each frame is drastically faster. I can publish my test branch if you want to see.
This bug was found while doing tests, the regex used the same var as the loop which caused scoping issues. After verifying the combination, it breaks out of the loop because `regex++ = NaN` and `NaN < anything = false`. This causes combo locked items to be "unsafe" and is a clear reason why `let` and `const` should  be used over var in 99% of cases.
> Fix: Lock verification

- BondageClub/Scripts/Dialog.js
- fixed an edge case where items could not be extended while focused on a NPC
Nina's previous fix was correct, but did not apply to extended items, so they were broken when targeting yourself while in the middle of a dialog with a NPC.
This fix should cover all cases.
> Fix: Dialog extended with NPCs

- BondageClub/Scripts/Dialog.js
The new free-item source for the item inventory didn't have the DynamicAllowInventoryAdd check that the other ones do, meaning the handheld toy would appear as an option everywhere even if the player wasn't holding one.
> Handheld Item Free Fix

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Inventory/ItemMouth/DildoPlugGag/DildoPlugGag.js
This PR is just a small modification to the gag level of the dildo plug gag following #1123 (the gag level consistency fix). Upon examining the previous code, I realised that the intention was actually probably to make the open version of the gag have the `GagEasy` effect for a gag level of 3 (rather than 6 which is how it behaved before that fix), which would line up with the gag level on the ring gag. This PR makes that change, bringing the open version of the dildo gag in line with the ring gag.
> Bugfix: Gag level tweak for the dildo plug gag

- BondageClub/Screens/Character/Appearance/Appearance.js
- fixed a bug where leaving the new wardrobe mode caused the focus group to stick
Right now, if you go to the wardrobe mode and cancel the focus group is kept so the next character to inspect will be in the inventory with the cloth category selected. (Since that button leaves the dialog now, it needs FocusGroup = null like the save changes checkmark)
> Fix: new appearance mode

- BondageClub/Screens/Room/AsylumEntrance/AsylumEntrance.js
- BondageClub/Screens/Room/CollegeDetention/CollegeDetention.js
- BondageClub/Screens/Room/CollegeTheater/CollegeTheater.js
- BondageClub/Screens/Room/Introduction/Introduction.js
- BondageClub/Screens/Room/MaidQuarters/MaidQuarters.js
- BondageClub/Screens/Room/Nursery/Nursery.js
- BondageClub/Screens/Room/Sarah/Sarah.js
- BondageClub/Screens/Room/Shop/Shop.js
- BondageClub/Screens/Room/Stable/Stable.js
- BondageClub/Scripts/Inventory.js
- added a new `InventoryAddMany` function to add several items at once
- refactored existing calls to `InventoryAdd` to use the new `InventoryAddMany`. 
- reduced the amount of inventory syncs in the shop
This new function allows to add many items at once without spamming the server with the inventory array which is a large one. This function replicates the existing behavior of `InventoryAdd`. Meaning singleplayer areas that had the potential of triggering 0-6 syncs now only sync up to 1 time. 
Also, the shop spammed inventory syncs when an item has a buy group, this makes it so the inventory is synced after everything was added. Reducing any item bought from 1+ syncs to a singular one.
There is also a huge drop in performance in shopping mode, I'll have a look at that eventually.
> Improvement: More Inventory Sync Optimisation

- BondageClub/Scripts/Inventory.js
- fixed a crash with items containing a RemoveItemOnRemove item.
ways to reproduce -> Char1 and Char2 are in the same room, Char2 uses a leather armbinder with straps or a suspension hogtie , Char2 changes the color of it, Char2 tries to remove it -> Char1 has an error and the item stays
https://discord.com/channels/554377975714414605/554378725916147722/742716102185844796
> Fix: InventoryRemove crash

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Scripts/Inventory.js
- moved the item remove on remove to the asset level to prevent the addons from sticking when swapping from one hood to the other
> Fix: Gask mask remove

- BondageClub/Scripts/Speech.js
This PR fixes an oversight in the new `SpeechGetGagLevel` function where the `Property.Effect` array would be used to calculate a non-extended item's gag level when it was locked (and hence it's `Effect` array would be `["Lock"]`, causing a gag level of 0 to be returned).
The function now checks for `Property.Effect` arrays containing only the `Lock` effect, and falls back to `Asset.Property` if the item isn't an extended item with allowed types.
* Equip any non-extended gag
* Talk - note that speech is garbled as expected
* Lock the gag (with any lock)
* Talk - note that speech is no longer garbled
> Beta Bugfix: Fix for gag level returning 0 on locked items

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
The group name was not being passed into the arousal activity call successfully, meaning the check for whether it allows an orgasm never returned true and an orgasm could never be reached.
> Fix: Orgasm Group Check

- BondageClub/Assets/Female3DCG/Female3DCG.js
The AssetSpankingToys (the non-ItemHands version), LeatherCrop and LeatherWhip assets have been given fetishes that call ActivityFetishItemFactor, but these have no effect. This is because since they are "Wear: false", they'll never occupy a spot in Appearance and therefore can never affect arousal for these fetishes.
Leaving the fetishes there wouldn't break anything but it is a bit misleading, so this removes them.
> Minor Fix: Unusable Fetishes

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
This is the change that was discussed in PR #1277.
The item visibility preference screen now includes a Block checkbox under the Hide one, which allows the player to set whether they want the item blocked. This will not appear as an option if the item is currently being worn or is already set to Limited.
> Hidden Items - Block Option

- BondageClub/Screens/Character/Preference/Preference.js
A small QoL change: clicking the Hide checkbox will now automatically change the Block checkbox to match it.
Sorry for the continuous trickle of PRs. Should be the last thing!
> Hidden Items - Block Auto-Tick

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
This PR fixes an issue where equipping wearable items with an `Activity` defined would cause incorrect chatroom action messages to be shown. This was happening because the equip action would be caught by the checks on line 631 of `ChatRoom.js` rather than the intended check on line 632. I've modified the check on line 631 to only include non-wearable items (handheld toys, etc.).
1. Character A equips a wearable item with an `Activity` on character B (e.g. Shock Dildo, Anal Beads XL) - note that this doesn't work for swapping, only equipping when the slot is already empty
2. Note that the chatroom message has no correct translation (see example image from discord)
> Beta Bugfix: Fixes chatroom messages for equipping wearable items with a defined Activity

- BondageClub/Assets/Female3DCG/Female3DCG.js
- moved the cross to layer 1 like any other background item (bench/bed/etc) which prevents conflicts with rear items as well as a few head items
- adjusted the butt/pussy area as it was slightly off (see [discord msg](https://discord.com/channels/554377975714414605/743491048352907355/744269196048990288))
Currently working with Sybil to allow going up to the XCross and being attached being separate for more flexibility which exposed the fact the priority was off compared to existing items
> Beta Fix: XCross priorities

- BondageClub/Screens/Character/Appearance/Appearance.js
This PR fixes a small issue with layer sorting between layers that belong to the same asset. If two layers belonged to the same asset with different priorities, the layer sorting algorithm would respect the position of the layers inside their parent asset's `Layer` array, rather than respecting their priorities. This meant that the sort order could become inconsistent, causing the layers to be rendered incorrectly (see image below).
This PR changes the sorting algorithm so that priority is most important, and position within the asset is used as a fallback in the case of equal priorities.
> Beta Bugfix: Minor issue with layer sorting for layers belonging to the same asset

- BondageClub/Screens/Character/Appearance/Appearance.js
- fixed a case where going in the wardrobe revealed restraints extended menus
some items do not reset DialogFocusItem under certain circumstances, this makes sure to reset any of them if they were still active.
> Beta Fix: extended leave

- BondageClub/Assets/Female3DCG/Female3DCG.js
Part of the PR #1302 fix for the duplicate Necklace rows seemed to be lost in merge conflict resolution. This fixes that up.
> Fix: Conflict Cleanup

- BondageClub/Assets/Female3DCG/Female3DCG.csv
- BondageClub/Assets/Female3DCG/Female3DCG.js
Moving the Hands group down below the customizable groups so that it doesn't leave a gap and disabling AllowColorize again.
> Inherit Colours - Hands Fix

- BondageClub/Scripts/AfkTimer.js
If a user has the "Auto AFK Setting" enabled and does nothing for 5 minutes, the "AFK" emoticon is shown over her head. As soon as she returns to the game, the Emoticon disappears, instead of resetting to the Emoticon, she had defined before.
This fix saves the old emoticon, before the "AFK" is displayed and reverts back to the old emoticon, when the player returns to the game.
* Select an emoticon, e.g. "Read"
* Wait until the "AFK" emoticon is shown
* Click with your mouse in the game screen ==> The emoticon disappears
* Added lines to save the old emoticon to a global variable in `AFKTimer.js`
Did the above described steps on my local instance of the game and the behavior is as expected.
> Fix: Reset to old emoticon after afk

- BondageClub/Assets/Female3DCG/Female3DCG.csv
Changing the web gag name in mouth slot 1 to match the other two mouth slots.
> Fix: Web Gag Name

- BondageClub/Scripts/Timer.js
There was a small bug with the way timer locks interact with the new gag level calculation code which meant that when the timer expired, it would leave the gag's `Property` with an empty `Effect` array, causing the calculated gag level to be 0.
1. Equip a (non-extended) gag
2. Attach a timer padlock (any kind) - don't set the padlock to remove the item upon expiry
3. Wait for the timer padlock to expire
4. Note that when the padlock expires, the player can talk normally (no speech garbling)
> Bugfix: Fix for timer locks removing gag effects upon expiry

- BondageClub/Scripts/AfkTimer.js
fixed the exception when the emoticon asset was in its initial state (often when loading from wardrobe or randomized character)
I also simplified the check to use InventoryGet
> Fix: afk timer

- BondageClub/Screens/Character/Appearance/Appearance.js
- made it so canceling out reverts the extended properties 
Cancelling out a change did not save extended properties, this applies them properly when applicable.
> Improvement: wardrobe restore properties

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Scripts/ExtendedItem.js
- added explicit support for clothes in the extended script
This will allow an extended item to prevent being refreshed/sending messages so that changing an item will not change the appearance for others in the room. This will also allow us to tweak things based on restraints vs clothes in the future
Talked with Ellie to make this change as best as it could be.
> Improvement: Extended script support for clothes

- BondageClub/Scripts/Character.js
- BondageClub/Scripts/Translation.js
This attempts to fix a commonly reported bug where the text for chatroom is not loaded properly (https://discord.com/channels/554377975714414605/554378725916147722/748049560705695754)
The only area this can come from is `TextLoad `which listens to `CurrentScreen`. The lines I've removed are an old trick to get around the parsing restrictions which is the only area in the code where `CurrentScreen `can be altered. (Besides relog which is unrelated). Since the online load is a callback on the socket, if you leave a screen and return to the chatroom while a chatroom sync is triggered... There is a slim change `TextLoad` will be called while the `CurrentScreen `is not `ChatRoom`. The reason for the lack of 404s would be that the Module/Screen combo loaded is still valid which would also make …
> Fix: online dialog building

- BondageClub/Screens/Inventory/ItemArms/DuctTape/DuctTape.js
- fixed the text alignment for the duct tape in the arms slot
The text wasn't aligned properly unlike the other slots
> Fix: text alignment for the duct tape

- BondageClub/Assets/Female3DCG/Female3DCG.js
When a club slave has been fitted with collar cuffs and then goes to the club management to have her contract fulfilled, the management removes only the collar, leaving the player with the cuffs that cannot be removed.
This PR fixes that by adding the collar cuffs to the `RemoveItemOnRemoval` attribute of `ItemNeck` assets
> Fix: Remove collar cuffs with the collar

- BondageClub/Scripts/Dialog.js
- fixed locks still being able to be blacklisted while worn as a check was missing in the click handler
Steps to reproduce: wear a lock, go in lock permissions and click the gray icon.
> Fix: Lock Permissions

- BondageClub/Scripts/Timer.js
- fixed a rare edge case where the CurrentTime is altered while wearing a timed lock which makes them think they should be unlocked in the future.
This uses commontime to make sure it is checked every 1.7seconds consistantly regardless of how we manipulate CurrentTime
> Fix: timer lock

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- Fixed a problem where safeword in the asylum was enough to be freed
Instead of safewording into the main hall, I made it so it goes to chatsearch. This keeps the exact same behavior and ensures we do not skip the chatroom space. In the case of LARP, it does not matter, but for the asylum, it makes it so a patient does not have a free pass.
> Fix: safewording in spaces

- BondageClub/CSS/Styles.css
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
When a player is in sensory deprivation, all actions and activities are anonymized, but activities are still displayed with a colored background, so the target is still able to guess, who did what to her.
This fix removes that background color from the message before it is displayed.
> Fix: Remove background colour from activity messages for sensory deprivation

- BondageClub/Scripts/Server.js
This disables the initial long polling call that seems to be triggering the 404
> Azure tests

- BondageClub/Screens/MiniGame/Tennis/Tennis.js
The speed of the opponent's racket in the tennis minigame was still framerate-dependent, making the game much more difficult at higher framerates. This fix should make the opponent's racket move at a consistent speed regardless of framerate.
Thanks to MrBondt on discord for helping to actually test it out on a 144Hz monitor.
> Bugfix: Fixes framerate-dependent tennis racket speed

- BondageClub/Scripts/Dialog.js
This fixes a bug that would make it much harder to struggle out of items at higher framerates. `TimerRunInterval` was being used to calculate the amount of struggle progress on each keypress. This meant that at higher framerates it would take many more keypresses to struggle out of the same item. Note that the framerate is still used (correctly as far as I can see) to calculate the amount of progress decay/growth. Note that the 42 multiplier was calculated (and rounded up) using the expected value of `TimerRunInterval` at 60Hz, so this change should keep the struggling experience consistent with the current behaviour at 60Hz regardless of framerate.
> Bugfix: Makes struggle progress per keypress independent of framerate

- BondageClub/Scripts/ExtendedItem.js
The extended item script's click function had a reference to InventoryItemArmsWebOptions instead of the options passed in. This hasn't matter so far since the Web is the only item currently using the extended scripts with enough options to use a second page.
> Fix: Extended Items Next Page

- .gitignore
- BondageClub/Tools/ESLint/package.json
npm scripts now can be run from `BondageClub/Tools/ESLint/` directly no need to copy or anything extra
.gitignore updated so npm modules can be installed to that path
> fix eslint so it is more simple to run

- BondageClub/Screens/Room/AsylumTherapy/AsylumTherapy.js
When in the therapy room as a patient, the click handler was too large so most clicks registered as touching the nurse (typo from the MouseIn conversions)
> Fix: Asylum therapy click handler

- BondageClub/Scripts/Inventory.js
- added a check to make sure InventoryLock is called with a lock
There was a report of a NPC locked by an item which is not a lock. I could not reproduce it or find any obvious reason why it happened. However, I checked and it is easily possible to call InventoryLock with an asset object which is not a lock.. this causes soft locks, especially in the case of NPCs who have no validation.
This makes the InventoryLock function safer to use, and will likely lead us to find the cause of the problem if we ever get reports of people not being able to lock a NPC under certain circumstances.
> Fix: InventoryLock verification

- BondageClub/Scripts/ExtendedItem.js
This makes some notable changes to the common ExtendedItem functions around how extended item options are displayed in the selection screen. Namely:
- The name of the option will now be displayed within and at the bottom of the white rectangle, to be more consistent with other selection menus and leave more space for more options.
- Items will show 8 options per page by default. A developer can configure a specific item to show fewer options per page if they wish by passing the number into the Draw & Click functions. (If enough time passes and no-one uses this option we could probably remove it for simplicity).
- The options will be laid out based on pre-configured positions in order to fill the space evenly.
- There are now Previous and Next buttons, instead of just a cyclic Next button.
> Extended Item Option Layout Enhancement

- BondageClub/Scripts/Drawing.js
This removes a duplicated version of the `DrawCanvas` function that was probably leftover from a merge with the recent dynamic assets changes.
> Bugfix: Removes a duplicate DrawCanvas function

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Scripts/Asset.js
- BondageClub/Scripts/Dialog.js
- removed duplicate properties
- fixed dialog sound
So, I was totally unaware ropes were the only item with sounds in singleplayer, so I adapted it with the new system.
This also means now that items will have sound in singleplayer as well, so that's a nice suprise upgrade!
> Hotfix for audio.js

- BondageClub/Screens/Inventory/ItemTorso/NylonRopeHarness/NylonRopeHarness.js
After converting the ItemTorso hemp rope to the extended script, these two functions were missing
> Fix: Rope conversion.

- BondageClub/Scripts/CommonDraw.js
- this makes it so an asset where we marked the type as irrelevant won't try to look for extra locks.
This will prevent having to rename locks with the items being moved over to the extended script and will make them more uniform
This has to be merged before more refactors are introduced.
(This currently fixes some that already have been merged such as the chastity belts)
> Asset has type: lock

- .gitmodules
- BondageClub/Screens/Character/Preference/Preference.js
- fixes the submodule linking that were incorrect which caused issues when checking out. (I just removed it, since no one other than reviewers have push access anyway. If we want, we could add a wiki folder we can copy paste)
- moved the preference migration under the gameplay settings as it caused crashes when creating accounts (because gameplaysettings was undefined)
> Important fixes

- BondageClub/Screens/Inventory/ItemLegs/Chains/Chains.js
Refactored ItemLegs Chains to use the extended item scripts.
~~@ace-1331 has a change incoming to integrate a setting to block type changing for locked items into the extended scripts. I'll replace the Validate function with that when it's in.~~
> Refactor: Chains for Legs

- BondageClub/Screens/Room/Nursery/Dialog_NPC_Nursery_Nurse.csv
A small bug when joining the nursery after the first time while already wearing a diaper.
The following dialog path doesn't actually cause you to wear mittens due to attempting to equip it on arms instead of hands
* I'm ready to join the nursery again
* I am already diapered and ready to enter
* Can I have some restraints please?
* I've been a good girl honest. My hands are cold.
> Fix when given mittens in the nursery

- BondageClub/Screens/Room/Cafe/Cafe.js
Clicking the maid in the cafe while not having anything equipped in the ItemMisc slot causes an error and no dialog.
Steps to reproduce:
* Start maid online drink job
* Remove the tray
* Talk to the maid in the cafe
> Fix tray check when talking to cafe maid

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Screens/Room/Magic/Magic.js
- BondageClub/Screens/Room/Stable/Stable.js
- BondageClub/Scripts/Character.js
- BondageClub/Scripts/Dialog.js
- BondageClub/Scripts/NPC.js
- BondageClub/Scripts/Server.js
- BondageClub/Scripts/Translation.js
The code uses the following pattern at several places:
```JavaScript
for (A = 0; A < array.length; A++)
if (something) {
doSomething();
array.splice(A,1);
A--;
}
```
As it is a bad idea in general to modify a loop variable within the loop, this PR changes this and transfers the above mentioned pattern to:
```JavaScript
for (A = array.length - 1; A >= 0; A--)
if (something) {
doSomething();
array.splice(A,1);
}
```
> Improvement: Remove loop variable modification

- BondageClub/Scripts/Inventory.js
If enclose is stored in Property, it does not work (item blocks itself when others try to interact)
This problem was brought up by someone currently working on an item that toggles the enclose state and it might eventually be required by more items, like closing cages
> Fix enclose in item properties

- BondageClub/Scripts/Dialog.js
- BondageClub/Scripts/Inventory.js
SelfUnlock wasn't actually preventing you from unlocking your own item if you were not blocked from interacting. Currently, all selfunlock: false item seem to block interactions which hid this problem.
> Change: SelfUnlock

- BondageClub/Scripts/Activity.js
- BondageClub/Scripts/Server.js
This PR removes all string compares to determine wether a Character is an NPC and replaces them with the new `IsNpc` function. That way, it's easier to change that check, if need arises one day...
> Refactor: Use IsNpc instead of string compares

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Screens/Character/Login/Login.js
The recent change to reduce CharacterRefresh calls passed in False to the ClothOnly parameter of the Full Random Appearance function. This revealed a long-standing bug where True and False were both being treated as True, and only undefined was treated as False.
This should fix the appearance of both the Login NPCs and the Shopkeeper after doing a job, to randomise the body as well as the clothes.
> Login Random Character Fix

- BondageClub/Assets/Female3DCG/Female3DCG.js
Made it so the seamless versions of the normal and see-through catsuits now expose the same zones as their zipper having equivelents. 
While I am aware it isn't "realistic" for them to allow access to these slots. In this case I think it is justified in having it. Mainly since all them not exposing these zones does is make it annoying to add or remove items from people wearing them, And since clothing can't be locked it doesn't prevent people getting access simply requires more time and messages. 
Which also has the side effect of either potentially ruining peoples outfits, since some people don't take note of what they are changing.
I also changed the Fetish of the suits from Nylon to Latex. It might just be me and if that is the case feel free to change it back, but the suits do not …
> Seamless suits expose same slots as the zipper versions

- BondageClub/Screens/Character/Appearance/Appearance.js
- fixed inappropriate pose handling
since  ["Kneel"] == "Kneel" is true but  ["Kneel"] === "Kneel" is false, you can console poses in arrays and mess up your character as only these 2 parts of the code understood this invalid data.
This can cause terrifying results! https://cdn.discordapp.com/attachments/748952474018250810/759160857804013568/Capture.PNG
Might be interesting to hotfix this to R60 before the beta
> Fix for pose handling

- BondageClub/Assets/Female3DCG/Female3DCG.js
Now that we have priority based layers, this fixes all gags that replace the mouth with their own so that layer 2 and 3 have visible mouths, but also to make sure the mouth is on the same layer has the base mouth to allow proper layering overall (more futureproof this way)
This means #967 is no longer needed and can be closed.
Fixes #1492
> Gags with mouths

- BondageClub/Scripts/Character.js
- improved the reset to null to include cases when active pose only contains either one of the base poses
(when clicking on the kneel icon, you wont "stand up" when already standing with BaseLower)
This was the intended behavior
> Improvement: Active pose behavior

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Character/ItemColor/ItemColor.js
- BondageClub/Scripts/Asset.js
* Adds a new `AllowColorizeAll` attribute at the asset level, which can be used to toggle the "Whole Item" option when colouring a multi-colourable item. Defaults to `true`
* Adds a new `HideColoring` attribute at the layer level, which can be used to hide a particular layer from the multi-colouring UI. Defaults to `false`
* Updates the shock collar and collar shock unit to prevent the light layer from showing in the colouring UI using the new `HideColoring` attribute
> Improvement: Adds AllowColorizeAll & HideColoring attributes

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
This adds a user preference for colouring activities in the chat log to bring the message type in line with the other available message types. This also fixes the following bug:
1. Have sensory deprivation settings set to "Total"
2. Enter full sensory deprivation (so that activities are no longer coloured)
3. Exit full sensory deprivation
4. Note that activities have not bee re-coloured
> Feature/Bugfix: Adds a chat preference for colouring activities

- BondageClub/Scripts/Character.js
- fixed a crash when the character is refreshed while in the multicolor picker (if the item is removed or changed, it crashes because the menu is not closed as expected)
> Fix multicolor picker crash

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Scripts/ExtendedItem.js
- fixed a problem where if character refresh is called while browsing to an extended item with more than one page, the page was reset to 0
- fixed the red box in the appearance menu (Again) as the refresh is no longer needed since CharacterRefresh now handles the reload. It actually caused problems because the index changes now
> Fix refresh weirdness

- BondageClub/Screens/Inventory/ItemAddon/BondageBenchStraps/BondageBenchStraps.js
- BondageClub/Screens/Inventory/ItemArms/DuctTape/DuctTape.js
- BondageClub/Screens/Inventory/ItemArms/SturdyLeatherBelts/SturdyLeatherBelts.js
- BondageClub/Screens/Inventory/ItemArms/Web/Web.js
- BondageClub/Screens/Inventory/ItemFeet/Chains/Chains.js
- BondageClub/Screens/Inventory/ItemFeet/SturdyLeatherBelts/SturdyLeatherBelts.js
- BondageClub/Screens/Inventory/ItemLegs/Chains/Chains.js
- BondageClub/Screens/Inventory/ItemLegs/DuctTape/DuctTape.js
- BondageClub/Screens/Inventory/ItemLegs/SturdyLeatherBelts/SturdyLeatherBelts.js
- BondageClub/Screens/Inventory/ItemNose/NoseRing/NoseRing.js
- BondageClub/Scripts/ExtendedItem.js
The following small changes have been made for ExtendedItem:
- The character variable C is being passed to other ExtendedItem functions and into the Validate functions, mainly to help avoid the risk of the extended clothes error noted in #1463 occurring in future. #1493 will need to be changed to fit this, so I'll make the change in whichever of the two PRs is merged second.
- When a Web option failed the prerequisite checks, it was exiting the options screen instead of staying in it. I think due to #1386.
- For extended items with multiple pages of options, both the Previous and Next buttons will now always be visible and going past the first or last page will wrap around. They've been repositioned to avoid overlapping the item preview image at the top.
>  Extended Item - Miscellaneous Improvements part 2

- BondageClub/Scripts/Server.js
- fixed a crash in the preference screen when switching account too fast.
If you went to email, then changed screen faster then the query, you crashed with 
```
Server.js:615 Uncaught TypeError: Cannot set property 'placeholder' of null
at ServerAccountQueryResult (Server.js:615)
```
because the input no longer exists. This prevents it
> Preference screen crash

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Scripts/Skill.js
- removed a piece of code that has been unused for nearly 2 years in appearance ready
- removed an unnecessary expose property from the bunny collar cuffs in the accessory group
- removed a duplicated var declaration in skill.js
- added a line to re-center text while drawing the preference screen to avoid compatibility problems (its the only subscreen that didnt reset the text to left after drawing checkboxes)
> Code cleanup

- BondageClub/Scripts/Dialog.js
Removes the colour picker button from the dialog menu buttons when the item is locked and the player is unable to unlock the item.
> Bugfix: Prevents players from colouring items they shouldn't be able to

- BondageClub/Scripts/Character.js
- BondageClub/Scripts/Drawing.js
To avoid looping through `GhostList` and the characters' appearance every frame, I've made it so the CharacterRefresh handles it.
This should help slower devices as now there won't be any performance penalty whatsoever.
Now any character without scripted assets wont even reach that code.
The only small downside is that the preferences based on scripted assets will require a character refresh to be taken into account, but that's rare and barely noticeable.
I have some other improvements in mind, but that's the simplest for now
> Optimized Scripted Assets

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- added a confirmation prompt to the safeword checkbox to prevent misclicks
It was raised as a concern that it was too easy to misclick it and get stuck while bound, so now it requires a double click to enable/disable.
> Confirm safeword

- BondageClub/Screens/Character/Preference/Preference.js
- properly hid the fetish controls when Sexual activities are disabled
The controls were visible when they shouldn't have been while sexual activities are disabled. (The click handlers were already properly disabled)
> Fix fetish in arousal screen

- BondageClub/Scripts/Dialog.js
- added leaving the focus item when leaving the overall dialog as a safety net
Places that forcefully get you out of your menu had problems with extended items with cleanup functions. This fixes all of them. (For example, try being in a padlock, custom tag, etc. while having an orgasm, it leaves the input on screen)
> Fix dialog leave

- BondageClub/Screens/Room/KidnapLeague/KidnapLeague.js
Currently only owner items are off-limits to random kidnappers. This change prevents random kidnappers from removing items with lover locks, which matches the inability of players to remove lover locks.
> Random kidnappers can't remove lover items

- BondageClub/Screens/Character/Login/Login.js
When a collar is equipped to the Login screen's random NPC, all random NPCs from then on will have that same collar (provided other assets don't hide it). This can be seen by simply waiting for a while on the screen.
The reason for this is that `CharacterFullRandomRestrain` has a chance to add a random asset from ItemNeck, but since nearly every asset in the group is not a restraint, `CharacterRelease` does not remove it for the next NPC. 
This has been fixed by removing the ItemNeck asset each loop. I don't think there's anywhere else in the game repeatedly applying full restraints and releasing like this so this is the simplest fix.
> Fix: Login NPC Collar

- BondageClub/Screens/Room/AsylumEntrance/AsylumEntrance.js
- BondageClub/Screens/Room/Cafe/Cafe.js
- BondageClub/Scripts/Asset.js
- BondageClub/Scripts/ExtendedItem.js
This replaces several calls to several extended item `SetPose` functions that have now been removed with the transition to the extended item scripts. These can cause the game to crash inside the Asylum and Cafe.
> Beta Fix: Replaces calls to removed extended item functions

- BondageClub/Screens/Room/MovieStudio/MovieStudio.js
Tiny bug (or at least weirdness) in the movie studio. The cross and drawers have `AllowItem` set to true allowing you to add restraints to them.
This simply sets it to false on both.
> Beta bugfix: Disallow items on movie studio props

- BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
The Simple Hogtie option for Hemp Rope on arms never had Prerequisites allowing it to be combined with incompatible poses like suspension and horse. The standard Hogtie prereqs have been copied over.
> Fix: Simple Hogtie Prerequisites

- BondageClub/Screens/Inventory/ItemEars/BluetoothEarbuds/BluetoothEarbuds.js
The Bluetooth Earbuds extended option functions were redirected into the Headphone Ear Plugs ones, but some parameters were missing resulting in nothing happening on clicking an option. Now fixed.
> Fix: Bluetooth Earbuds option selection

- BondageClub/Scripts/AfkTimer.js
The automatic AFK emoticon does not get cleared if
1. Starting without an emoticon active
2. Going AFK for two or more "cycles" of the AFK check (>10 minutes)
On the second check `if (InventoryGet(Player, "Emoticon") && InventoryGet(Player, "Emoticon").Property && AfkTimerOldEmoticon == null)` will be true which sets the `AfkTimerOldEmoticon` to the AFK emoticon making the reset ineffective.
The fix checks `AfkTimerIsSet` to avoid setting it again. From what I can tell everything for auto AFK should be set by that point so it doesn't need to set anything again.
> Beta bugfix: Don't set auto AFK if it's already set.

- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
The 'Friend in room' hovering text for chat room buttons is mispositioned sometimes. 
When the room button is low enough, currently if below Y = 352 i.e. row 4, then the hovering text is positioned at row 4. This is presumably to ensure there's enough space to display a long list of friends without overlapping the bottom buttons and/or running offscreen. However for a short list of friends, the text often appears far above the room button and looks incorrect.
Now the height of this text is calculated so that it's only moved up when it will go too low, and ends up still beside beside the room button.
> Chat Search Friends Position fix

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Scripts/Dialog.js
Prevents the colour picker buttons from being displayed for items that have no colourable layers.
> Bugfix: Hide colour picker buttons for non-colourable items

- BondageClub/Screens/Character/ItemColor/ItemColor.js
- BondageClub/Scripts/Character.js
- BondageClub/Scripts/Element.js
This makes 2 changes which can cause errors on character update within the colour picker:
* Refines the conditions upon which `ItemColorExit` is called upon character refresh so that it is only called when needed
* Updates the `ItemColorExit` function to be more resilient to in cases where `ItemColorLoad` has never been called
These changes should fix errors like this from occurring:
> Beta bugfix: Makes ItemColorExit more resilient

- BondageClub/Screens/Character/Appearance/Appearance.js
- fixed a bug where you would be softlocked on the sybian when relogging in the asylum
This basically happens to things that have IsRestraint set to false and RemoveAtLogin set to true while you have the check to keep everything on you when logging WHILE you log into the asylum and that item needs to have something that conflicts with clothes in general (patient clothes) or you have >50 rep and cant use your arms.
After verification, it only happens to the sybian currently, however to prevent this from happening ever again, I added a check to bypass "keep all" in the login process if you are about to be sent to the asylum.
This change will only make it so you no longer keep teddy bears or the sybian when relogging in the asylum
> Fix: asylum bedroom softlocks

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
* Fixes an issue where the `GagLight` effect on the futuristic panel gags wouldn't persist across server updates due to `AllowEffect`
* Adds the `BlockMouth` effect to the default effects of the gag to prevent french kissing through it
* Also changed the gags to have no gagging effect in the default "Padded" configuration, as discussed with @Ada18980.
> Bugfix: Fixes effect consistency on the futuristic panel gags

- BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
Bug would happen if you applied another item and then focused on the belt. Now DialogProgress must be >= 0 to indicate that the user is in the struggle menu.
> Fixed a bug where the futuristic belt would shock you for tampering

- BondageClub/Scripts/Drawing.js
Fixes ReferenceError: DialogLeaveDueToItem is not defined by adding var DialogLeaveDueToItem in globals
> Fix reference error

- BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
- BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js
Fixes an issue where if the user uses '/me' to do an emote rather than '*', the auto shock unit and futuristic panel gag would punish them even though it's not supposed to punish emotes. Now it filters on '/' as well, which should avoid punishing the player for emotes, actions, and commands.
> Voice activated items emote fix

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Inventory/ItemNipples/TapedVibeEggs/TapedVibeEggs.js
- BondageClub/Screens/Inventory/ItemVulvaPiercings/TapedClitEgg/TapedClitEgg.js
Replaces the current code for the taped egg vibrators (nipples and clit) with the new vibrator mode code.
As an added consequence this removes an error when going between some of the settings in the old code (Described in a bit more detail in https://discord.com/channels/554377975714414605/557728347468070912/768195145891053578).
> Convert taped egg vibes to new vibrator modes

- BondageClub/Scripts/ColorPicker.js
This fixes an issue that would cause the colour picker callback to be called continuously due to a rounding error in the conversion between CSS RGB values and HSV values, which would result in errors on attempting to leave the colour picker when certain colour picker values were entered into the colour picker input.
The reason this happens is that the colour picker does an internal colour equality check between it's stored HSV value (which was converted from the input value) and the current input value. For some colours, converting from CSS --> HSV --> CSS would not return the exact same CSS colour due to rounding errors. For example, converting the CSS value `#3b1866` to HSV and back would return the CSS value `#3b1766`, causing the equality check to fail every time, meaning the colour …
> Bugfix: Colour picker error

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
When a character had a self-applied pose in a chatroom, the dialog option to help them kneel would always make them stand even if they were already standing. 
This is because it still held the old assumptions where ActivePose being null was equivalent to standing and ActivePose being non-null was equivalent to kneeling. This has been updated.
> Help Kneel/Stand Fix

- BondageClub/Assets/Female3DCG/Female3DCG.js
The alpha masks for the Bolero Straitjacket were overlapping the open space in the centre a bit, which meant a slice of clothes & suits being worn were cut off at the left and right in this space. The mask zones have been tweaked slightly to avoid this.
> Bolero Alpha Masks fix

- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
The latest changes to ChatSearchNormalDraw will have minor issues in a full page of rooms.
The initial setting of ListY needs to be aware of every text row to come so that it can start high enough to give them all space. At the moment it's based solely on Friends, so an additional Block row near the bottom will overflow too far down.
I've tweaked the logic a little bit so that:
1) The BlockCategory length is considered in ListHeight so that the starting ListY position is higher if necessary.
2) ListHeight properly handles the case where there's a Block row and no Friends.
2) ListY is incremented after each DrawTextWrap by one row height, to avoid messy calculations to determine each row's position.
> Block Category Hovertext fix

- BondageClub/Assets/Female3DCG/Female3DCG.csv
- BondageClub/Assets/Female3DCG/Female3DCG.js
The NPCs were getting mismatched colours for the front and back because while HairBack had HairFront as its parent, HairBack appeared first in the asset group list, so there was no parent colour picked yet to be copied.
The simple solution to this was to swap HairFront and HairBack in the group list order.
> Hair Mismatch Fix

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Scripts/Character.js
The Edge feature of TapedClitEgg wasn't working for two reasons:
- AllowEffect wasn't updated to include 'Edged' when the new vibrator modes were added to two items.
- The IsEdged check only looked at items belonging to groups which allowed orgasms. It instead needs to check the settings of vibrating items' ArousalZone group, which usually defaults to the item's group but could be different. In this case, TapedClitEgg is in `ItemVulvaPiercings` which does not have arousal settings, but it has an ArousalZone of `ItemVulva` which does.
> Vibrators Edged Fix

- BondageClub/Assets/Female3DCG/Female3DCG.js
The Metal Leg Spreader and Wooden Cuffs in ItemFeet both had issues when the target is kneeling.
If the character was kneeling but not forced into the position (e.g. by collar & short chain), then the NotKneeling prerequisite passed and the item could be applied. However the item could not be removed again because it had an AllowedActivePose of Kneel which failed the NotKneeling prerequisite.
The AllowedActivePose setting has been removed. This does mean that applying the item forces the character to stand up, but that's at least consistent with other items that have the NotKneeling prerequisite.
> Spreading Items Kneel Fix

- BondageClub/Scripts/Dialog.js
When a player tries to use a handheld toy on a target who has blocked that specific toy, the item still appears as the first option in the group with a white background, as if usable. Clicking on it does nothing.
A fix has been put in so that the item now moves to the end of the list highlighted red, the same as other items.
> Blocked Handheld Toy - Inventory Order fix

- BondageClub/Scripts/VibratorMode.js
This fixes an issue where a lockable item that also uses the new vibrator mode script could have locks removed by updating the vibrator mode (or via automatic vibrator updates). This happened because the `Effect` array was being overwritten, effectively removing any lock on the item. This is currently only an issue with the mermaid tail as far as I'm aware, as that is the only lockable item that uses the new vibrator script.
1. Equip a mermaid tail
2. Lock the mermaid tail
3. Change the vibrator mode on the mermaid tail
4. Note that the lock has been removed
> Bugfix: Fix for vibrators removing locks from an item

- BondageClub/Scripts/ExtendedItem.js
A small fix to #1449 to prevent an error when a lockable extended item doesn't have an effect. To see this apply Leather Ankle Cuffs on feet and try to change the option.
I also removed an unneeded C declaration that could actually cause issues for extended clothes.
> Extended Items Lock fix

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Audio.js
- BondageClub/Scripts/Character.js
- BondageClub/Scripts/Drawing.js
While being blind is great, seeing your character blindfolded can be as well.
This PR adds new sensory deprivation setting level: Light
Effects of this setting are:
- `BlindHeavy` effect is treated as `BlindNormal`
- Character's names are not hidden
Technical details:
- Adds `Character.GetBlindLevel` function, that works like `Character.GetDeafLevel`
> Sensory deprivation setting: Light

- BondageClub/Scripts/Speech.js
- BondageClub/Scripts/Timer.js
This is a part 2 for the fix from #1274. When a non-extended item gag is locked then unlocked, it no longer garbles text. 
The original PR restored the garbling while the gag was still locked, but not when it was unlocked again.
Now Property.Effect, which will always be non-garbling for non-extended gags, will only override Asset.Effect if Type is undefined, which ensures this will only happen for extended gags.
> Unlocked Gag Garble fix

- BondageClub/Screens/Inventory/ItemDevices/BondageBench/BondageBench.js
- BondageClub/Scripts/ExtendedItem.js
When an extended item type has no SelfBondageLevel setting, it defaults to 0. This allows some types to be easier to apply to oneself than to someone else which isn't very consistent. The ItemArms HempRope options being a prime example.
Now the self-bondage type difficulty copies the Asset's overall self-bondage setting or the type's BondageLevel, whichever is higher, when a SelfBondageLevel has not been set.
Also includes a fix to the BondageBench settings.
> Self-Bondage Difficulty for Extended Types

- BondageClub/Scripts/VibratorMode.js
This fixes an issue where the vibrator mode script would cause an error when opening the vibrator menu on several of the vibrators using the `VibratorMode` script while not locked.
This is the stack trace of the error in question, as reported on Discord:
> Bugfix: Vibrator mode error

- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Similar to part 1 of #1614, this considers the Game label in the chatroom button popup's start position to avoid going too far down when near the bottom.
> Chat Search - Game Label fix

- BondageClub/Screens/Inventory/ItemDevices/BondageBench/BondageBench.js
- BondageClub/Scripts/Dialog.js
- BondageClub/Scripts/ExtendedItem.js
- BondageClub/Scripts/Inventory.js
- BondageClub/Scripts/Server.js
As an unintentional result of #1449, it is not possible to change the type of items that are locked without unlocking them unless they explicitly set `Property.AllowLock = true`. After discussing with @Nina-1474, it seems like more often than not, this doesn't make sense as a default behaviour (for example, the plug gags, latex leotards, inflatable body bag, etc.). This change therefore reverses that default behaviour so that by default `Property.AllowLock` is presumed to be `true` unless it is explicitly set to false. This maintains the behaviour of the bondage bench as defined in #1449 but reverts any other extended item back to the way it was before that change. 
There may be some items for which this behaviour makes sense, but I'm not going to change any items now. I will work through …
> Bugfix: Locks blocking type switching

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Scripts/Dialog.js
- BondageClub/Scripts/Inventory.js
- BondageClub/Scripts/Server.js
This is a follow-up fix to #1657, which broke the adding/removing of non-lockable items. I've tested this one pretty thoroughly now and I'm pretty sure it covers all bases.
1. Character A applies a non-lockable item (eg. duct tape) to player B
2. When the progress bar is full, the game crashes, and an error is displayed in the console (see below)
> Bugfix: Issue with non-lockable items

- BondageClub/Assets/Female3DCG/LayerNames.csv
The layer names for the Futuristic Armbinder were missing.
> Futuristic Armbinder Layer Names

- BondageClub/Screens/Room/CollegeEntrance/CollegeEntrance.js
The adding of multicolouring to the college uniform meant the College Entrance conditions were no longer working for the default colour check, blocking entrance altogether. This has been corrected.
> College Entrance Colour Check fix

- BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
- BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js
This fix makes the auto shock collar and the futuristic panel gag no longer have the "Automatic" tag, since players reported it as a bug when the messages got filtered. It may also hinder communication in RP. So the solution, I think, is to make them no longer automatic since they are triggered by intentional actions
> Automatic shock collar and futuristic panel gag trigger fix

- BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
When you click "lock" it will lock the futuristic collar as well with the selected type of lock. unlock functionality is unchanged as you can always take the collar off manually, and most doms might prefer to keep the collar owner-locked permanently.
> Futuristic Collar now locks itself

- BondageClub/Screens/Character/Login/Login.js
- BondageClub/Screens/Character/Wardrobe/Wardrobe.js
- BondageClub/Scripts/Character.js
Multiple players sometimes get assigned the same ID by the client and when they are in the same room they can interfere with each other causing items and activities to dissapear.
It can probably cause other issues too but that is the one I noticed that caused me to investigate this.
Reselecting the area will show the activities again but in actual online situations this can be triggered in quick succession making the activities unusable.
1. Log in with three characters (let's call them A, B and C)
2. Create a room with A
3. Have B and C join the room in order
4. Their character IDs in A's client should now be A: 0, B: 2, C: 3 (1 is taken by the main hall maid)
5. Log out with B, log back in and join the room.
6. IDs will be A: 0, B: 3, C: 3.
7. Have A select an area with activities on C …
> Fix: Duplicate character IDs causing disappearing activities

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
When the player's sensory deprivation settings are set to maximum (no whispers while blind) and the player also cannot examine other players while blind, only the player will be rendered in a chat room regardless of the number of players in the room.
> Tweak: Room size while blind

- BondageClub/Scripts/Character.js
If the character closes both eyes, the maximum blind level is applied, so that the room gets dark.
This does not happen, when the character blinks, but only if the eyes are closed on purpose.
A simple if statement added to `GetBlindLevel`in `Character.js
This was tested on my local copy of the game and works in the single player, as well as the multi player rooms.
If the player keeps one eye open, by winking, the effect does not trigger.
> Feature: Darken room if both eyes are closed

- BondageClub/Screens/Room/Nursery/Nursery.js
Fixes that only the plain diaper count as being diapered when it comes to enter the nursery.
Changed the `PlayerDiapered`Check in `Nursery.js`
Tested that on my local instance of the game. The nurses accept other diapers now as well, when the player wants to enter the nursery for a second time.
> Fix: All diapers count as being diapered in the nursery

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
1) Player leashing is on by default
2) Changed the text to reflect RP better
3) Moved the checkbox so it's not way off
4) Fixed a bug in HoldLeash that required the dom to leash a player twice before leashing would work
5) Added logic to ping players joining the room that are on the leashlist to make sure they are still leashed, removing from dom side if they are not (in case something happened in a different room or they got unleashed.
> Leashing option default and dialog

- BondageClub/Scripts/Character.js
This fixes a bug that was introduced with #1702 
When a new character is created, the check in `GetBlindLevel` raised a null pointer exception. This is now prevented.
> Fix: New characters and blindness check

- BondageClub/Scripts/Drawing.js
Hides the focus zones grid while in item-coloring mode to avoid it interfering visually with the item being colored, and also somewhat cleaner look.
Not sure if this would be better as an option instead but I'm happy to turn it into one if that's the case.
> Hide focus zones grid while coloring an item

- BondageClub/Scripts/Drawing.js
This is to stop the blue blinking from blinking all the time
> Arousal bar animation disappears when progress = 0

- BondageClub/Screens/Room/MaidQuarters/MaidQuarters.js
Adds `MaidOutfit2` ("Maid Exposed") to the valid uniforms to start maid work.
Also skips replacement of the currently worn uniform slots when starting (some) jobs which allows this to work and has the added benefit of keeping custom colors of your currently worn maid outfit when the work starts.
> Allow starting maid work with the exposed uniform version

- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Because looping through the ignored rooms that are not in the latest search results starts at `ChatSearchResultOffset`, which is 24 on page 2, they do not get drawn in the filter list when they get pushed to page 2 or higher.
Changes the initial offset to be calculated based on page offset, already shown rooms and total rooms in the search results (`ChatSearchResultOffset + shownRooms - ChatSearchResult.length`).
> Fix: Missing ignored rooms in chat room filter

- BondageClub/Screens/Character/InformationSheet/InformationSheet.js
Removes difficulty from NPC information sheets which is currently shown and overlaps their lover info:
(also, since I had to move the `OnlinePlayer` declaration anyway I moved it a bit further up to reuse it in the previous check)
> Fix: Don't show difficulty for NPCs.

- BondageClub/Scripts/Server.js
Unfortunately I've not been able to identify the root cause of this, as I've only seen it once, and can't reproduce it, but I've had the same issue reported to me by others before. This fixes a rare issue where the `ServerAppearanceLoadFromBundle` function throws an error on relogging inside a chatroom and re-syncing the chatroom characters. This results in a strange visual glitch where the player enters the chatroom, and is visible to everyone else, and can interact normally and be interacted with, but is actually invisible to themselves, as the error results in them not being added to the `ChatRoomCharacter` array, even though they are present in the chatroom data.
I've added a null-check which should alleviate the issue (and probably should be there anyway), but I'm still unsure what …
> Bugfix: Fixes a rare issue on chatroom relog

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Common.js
- BondageClub/Scripts/CommonDraw.js
This adds some extra checks to `CommonDrawAppearanceBuild` and `ChatRoomSyncItem` to validate that an item's `Color` is defined properly (either `null`, `undefined`, a string or an array of those types). This isn't something that should be possible through normal gameplay, but players can currently use the console to set an item's `Color` to anything they like, for example an object like `{}`, which results in the error below (screenshot taken from discord, where players have been reporting someone's console usage causing these issues):
This check should prevent people from breaking other people's games via this particular loophole.
Character 1 and Character 2 in the same chatroom.
1. Character 2 applies an item (e.g. something in `ItemArms`) to Character 1
2. Character 2 then runs the …
> Bugfix: Item colour resilience

- BondageClub/Screens/Inventory/ItemNeckAccessories/CollarShockUnit/CollarShockUnit.js
The shock trigger function on the shock collar (`InventoryItemNeckAccessoriesCollarShockUnitTrigger()`; which is also used for the dildo, clamps and plug) calls `ChatRoomPublishCustomAction()` with `LeaveDialog` set to `true` which causes it to clear `DialogFocusItem` and in turn throw an exception when trying to update arousal if the player shocks themself resulting in no arousal or facial expression updates.
Changes `LeaveDialog` to `false` in the call and to call `LeaveDialog()` manually later if in a chat room.
> Fix: Exception when triggering shocks on self

- BondageClub/Assets/Female3DCG/Female3DCG.js
The `Wiggle` activity had dialogue and for `ItemButt`, but hadn't been added to the group's activity array. This fixes that.
> Bugfix: Adds the Wiggle activity to the ItemButt group

- BondageClub/Screens/Room/MainHall/MainHall.js
The setting to remove single-player rooms when the new 'Cannot enter' setting is enabled was added to the Run function but not the Click function.
> Single-Player Room Hide fix

- BondageClub/Screens/Inventory/ItemMisc/PasswordPadlock/PasswordPadlock.js
- BondageClub/Scripts/Server.js
This change was requested by players who said they can't fit anything meaningful into 6 letters. I cant remember the reason it was set to 6, but I think it had to do with the possibility of trolls setting one to random letters and being unable to figure it out. However, bruteforcing 6 letters is still hard, and in Extreme mode password padlocks are blocked for non-whitelist anyway. Hardcore players can block the locks if they are worried about it.
> Increases max password length to 8 (for the password padlock)

- BondageClub/Assets/Female3DCG/Female3DCG.js
I'd say this one is subjective whether it's a bug or not but MouseEars1, MouseEars2 and ElfEars ear items have a value of 20 instead of -1 like other items in the HairAccessory2 (Ears) item group causing them to show up twice when you ask to see items you don't already own.
Changes them to behave in the same way as the rest of the group by setting their values to -1.
> Bring MouseEars1/2 and ElfEars values in line with other ear items

- BondageClub/Assets/Female3DCG/Female3DCG.js
Moved tickle and rub toys to the slot that is actually named "head" to prevent strange messages like "tickles x eyes". This brings them back to the way they were before
> fix activity

- BondageClub/Screens/Character/Preference/Text_Preference.csv
Small followup fix to #1763: Since ItemHood now has arousal activities it needs a line in the Preferences screen text file for the Arousal menu.
> ItemHood in Arousal menu

- BondageClub/Assets/Female3DCG/Female3DCG.js
Enabled the upperbody pose menu with mittens by no longer considering it to be a pose that force the arms in one way or the other.
No side effect was found
> Mittens with pose menu

- BondageClub/Scripts/Dialog.js
This fixes a bug which leaves characters floating in the air after using the "up" button to show all of the zones on a character that is kneeling/hogtied/etc and then leaving the dialog screen via the escape key.
1. Enter a chatroom and kneel
2. Click on the kneeling character and hit the ^ button to show all of the character's zones
3. Hit the escape key on your keyboard
4. Note that the character is left floating in the air
> Bugfix: Fixes floating characters when leaving the dialog screen via the escape key

- BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
The futuristic gags were producing incorrect chatroom messages when the "Trigger Inflation" button was pressed.
Two characters: "Character 1" and "Character 2".
1. Add a Futuristic Panel Gag/Futuristic Harness Panel Gag to Character 1
2. As Character 2, enter the extended item menu for the gag and hit the "Trigger Inflation" button
3. Note that the chatroom message says "Character 2's gag inflates into a mouth-filling ball.", and expression changes are applied to the wrong character as well.
> Bugfix: Fixes chatroom messages on the futuristic gags

- BondageClub/Scripts/Inventory.js
The function that automatically removes certain items when certain others are removed has the ability to check the type of extended assets, currently only used to remove round nipple piercings with the chain or weighted chain when removing a collar. 
This wasn't working and always removed the item regardless of type, i.e. it removed the piercings even without a chain.
The function has been fixed so now it won't remove the item if it does not have the type matching the type configuration.
> Remove On Remove - Type fix

- BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
Chatroom messages for the futuristic collar were being sent using `DestinationCharacter` when the text in the CSV uses `DestinationCharacterName`. This was resulting in messages like "Character'sName bindings tighten around her body with a hiss as they lock themselves automatically."
> Bugfix: Fixes chatroom messages for the futuristic collar

- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
- BondageClub/Scripts/Server.js
When the player holding a leash fails to enter a room, either because it's full or because they try to create a room with a name that already exists, the leashed player gets sent a `Leash` beep with no room set, causing `ChatRoomJoinLeash` to be set to null and in turn cause an error in `ChatSearchQuery()` until `ChatRoomJoinLeash` is changed again.
Adds checks both in `ChatSearchQuery()` which fixes the resulting error and in `ServerAccountBeep()` which avoids causing it in the first place.
> Fix: Error for leashed player when leash holder fails to enter a room

- BondageClub/Scripts/Dialog.js
Moves the fix to `DialogLeave` to allow "Show all zones" to work properly
> Bugfix: Allow selection of legs/feet, while keeping floating character fix

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
The leashing code checks for the `Enclosed` effect instead of `Enclose` which items like boxes, cages and lockers use so leash actions are not blocked while in those items.
Might conflict with #1790 since it changes a line that's moved in that PR.
> Fix: Leash actions on character in boxes/cages/lockers

- BondageClub/Screens/Character/Login/Login.js
I've now obtained a 144Hz monitor, so I can test out framerate-based differences in behaviour across the game. I've noticed that the credits on the login screen whizz past substantially faster at 144Hz than at the standard 60Hz. This change makes the credit roll speed independent of framerate.
> Bugfix: Makes the login credits independent of framerate

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Scripts/Inventory.js
As @Ayesha-678 has a new medical bed item on the way, this PR adds an `OnBed` effect and changes the `OnBed` prerequisite to check for that effect, rather than just checking for the current bed item. This will allow existing bed restraints to work with the medical bed, and any other future items that want to use the effect.
> Feature: Changes the "OnBed" prerequisite to use a new "OnBed" effect

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/index.html
Allowing the Escape key to move the chat scroll position to the end similar to Discord, as an alternative to lengthy page-downs or scrolling.
> Scroll Chat Down with Esc Key

- BondageClub/Screens/Character/Login/Login.js
When a login crashes, it's possible on successfully logging in later to find that the character's appearance and bindings are completely changed.
This is because the Player variable is used as a placeholder for the randomly generated login screen NPC, and ends up keeping that appearance. This uses a dedicated character for the NPC instead to avoid the issue.
I'm holding this change back from this release given that we're late in the beta period, the bug is not critical if it occurs, and if there's any hidden issues with this change it could potentially be quite disruptive.
> Login NPC Overwrite fix

- BondageClub/Screens/Character/Creation/Creation.js
`Player.FriendNames` and `Player.SubmissivesList` are initialised for players on login, but are not initialised for players on character creation. This means that interacting with other players or the friends list straight after character creation can cause the friends list not to work properly, with the following errors:
```
FriendList.js:146 Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
at Function.from (<anonymous>)
at FriendListLoadFriendList (FriendList.js:146)
at ServerAccountQueryResult (Server.js:664)
at r.<anonymous> (Server.js:51)
at r.emit (index.js:83)
at r.onevent (index.js:83)
at r.onpacket (index.js:83)
at r.<anonymous> (index.js:83)
at r.emit (index.js:83)
at r.ondecoded (index.js:83)
```
```
Server.js:216 Uncaught TypeError: …
```
> Bugfix: Ensures FriendNames & SubmissivesList are initialised on character creation

- BondageClub/Scripts/Dialog.js
Enabling the pose-changing menu in the Photographic room as unlike other single-player rooms, there's a clear benefit and no apparent issues with enabling it.
> Pose Menu in Photography room

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
The "Character Actions" dialogue option would not always show up when the character was leashed, as the leash condition was missing from the `ChatRoomCanPerformCharacterAction` function.
1. Apply wooden cuffs (or any item that prevents kneeling), and a leashing item to a character
2. Note that the (Character Actions) dialogue option does not appear
> Bugfix: Fixes condition for the character actions dialogue option

- BondageClub/Screens/Inventory/ItemBreast/FuturisticBra2/FuturisticBra2.js
- BondageClub/Screens/Inventory/ItemHands/FuturisticMittens/FuturisticMittens.js
This fixes some validation function calls on the Futuristic Mittens and Breast Harness, whose validation functions weren't changed by #1511 (likely due to merge order). This causes these items to appear locked when they aren't, and blocks access to their extended item screens.
1. Equip Futuristic Mittens or Breast Harness.
2. Note that the extended item screen for the items declares that they are locked.
3. Note that clicking the unlock button denies access
> Bugfix: Fixes validation functions on futuristic mittens and breast harness

- BondageClub/Scripts/Character.js
- BondageClub/Scripts/Server.js
`C.GetLoversNumbers()` was being called on NPCs in the player's private room when entering it. However, NPCs at this point are just data objects, rather than full `Character` instances, and therefore don't have the `GetLoversNumbers` method. I've moved that method out into a separate character function so that it can be reused on pure data objects, and corrected the offending line in `ServerAppearanceLoadFromBundle`.
> Bugfix: Fix for ServerAppearanceLoadFromBundle for private room NPCs

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Screens/Room/CollegeCafeteria/CollegeCafeteria.js
- BondageClub/Screens/Room/CollegeDetention/CollegeDetention.js
- BondageClub/Screens/Room/CollegeTeacher/CollegeTeacher.js
- BondageClub/Screens/Room/CollegeTennis/CollegeTennis.js
- BondageClub/Screens/Room/CollegeTheater/CollegeTheater.js
- BondageClub/Screens/Room/Sarah/Sarah.js
- BondageClub/Scripts/CommonDraw.js
- BondageClub/Scripts/Inventory.js
At the moment it's possible to set an invalid colour on another user's item via console and cause an error on the item for them when it's being rendered.
The drawing code now checks that any named colour (currently only White/Asian/Black) is in the group's colour schema and otherwise replaces the invalid colour with Default. Some additional changes were needed for inherited colours as they can pass down a named colour not in the target group's schema. The head & hands settings for preset NPCs were also updated to use the Default colour inheriting to pass this validation.
> Colour Name Validation

- BondageClub/Scripts/Server.js
As a result of some of the changes in #1387, items marked as `LoverOnly` or `OwnerOnly` get removed on login, due to a check in `ServerAppearanceLoadFromBundle` against the source member number (which is undefined when logging in). This PR reinstates the missing checks for a login.
1. Equip either the Lovers Vibrator or Love Chastity Belt on a character
2. Have that character log out and log back in
3. Note that the vibrator/belt has been removed by the appearance bundle load
> Bugfix: LoverOnly/OwnerOnly items getting removed on relog

- BondageClub/Assets/Female3DCG/Female3DCG.js
Fixes alpha masks for the open crotch straitdress. Previously the masks were only being applied to the lower body group, which caused clipping issues when the lower body size was larger than the upper body size. See the screenshot below for an example.
> Bugfix: Fixes alpha masks for the open crotch straitdress

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
- BondageClub/Scripts/Common.js
This is something of a follow up to #1799. I was originally going to request some changes on that PR, but it got merged before I did. This PR makes some refinements to the font system which should make it a bit more resilient and performant generally, and should also make it more likely that players will see distinct font options as they click through the available choices (rather than half of them displaying as the browser default). A summary of changes:
* Adds appropriate fallback font stacks for each font, so that the chosen font more closely resembles what the user requested if their chosen font is not available on their device. This means, for example, that if "Courier New" is not available on someone's machine, it will still fall back to a monospace font, rather than the browser …
> Improvement: Font system refinements

- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
- BondageClub/Scripts/Server.js
If a player is viewing a subscreen in a chat room (wardrobe, profile, etc) and gets kicked or banned, on exiting the subscreen they still see the chat room despite no longer being in it. This fix re-uses the disconnect check so that they properly jump to the chat search page regardless of what subscreen they're in.
> Kicked in Chatroom Subscreen Fix

- BondageClub/Scripts/Character.js
- BondageClub/Scripts/VibratorMode.js
This fixes some cases where the Deny and Edge vibrator modes were not working as intended:
1. Adds stricter checks for vibrating items in the `CharacterIsEdged` function to prevent items like shock toys from counting as "vibrating"
2. Adds a `CharaterLoadEffect` call to the `VibratorMode` code to ensure the player's effect array is up to date on vibrator changes
> Bugfix: Vibrator mode fixes

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
- BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
- BondageClub/Screens/Inventory/ItemArms/Web/Web.js
- BondageClub/Screens/Inventory/ItemBoots/FuturisticHeels/FuturisticHeels.js
- BondageClub/Screens/Inventory/ItemBreast/FuturisticBra2/FuturisticBra2.js
- BondageClub/Screens/Room/Shibari/Shibari.js
- BondageClub/Screens/Room/Shop/Shop.js
- BondageClub/Scripts/Asset.js
- BondageClub/Scripts/Character.js
- BondageClub/Scripts/CommonDraw.js
- BondageClub/Scripts/Dialog.js
- BondageClub/Scripts/Drawing.js
- BondageClub/Scripts/GLDraw.js
This makes a number of changes around the code that determines a character's vertical height and position. In two key ways in particular:
- Allowing assets to be drawn in space that's opened up when the character is shorter or in a low pose, which in the current system is unsuable.
- Refactoring many of the height/position calculations for easier re-use and expansion in upcoming developments.
I have a feature nearing completion to allow suspension hogties to be set at variable heights built using this, but I'm only pushing the core system rework for now to keep it (relatively) digestible. There should be **no noticeable changes to the game** from this PR, other than a few fixes. The new stuff will all follow separately.
The height of the character canvas (Canvas and CanvasBlink) will be …
> Height System Rework

- BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
- BondageClub/Scripts/Common.js
This fixes two font issues:
1. Fonts were not cached correctly when calling `CommonGetFont()` due to a bug with number arguments in `CommonMemoize`
2. The Kidnap minigame used to use the "Arial Narrow" font, which is a completely separate font, meaning `CommonGetFont()` would have " Narrow" appended to its result, which would not work. I've emulated this for generalised fonts as well as possible by changing the font weight to 300 (light) for those instances. It won't reproduce the previous look when using Arial exactly, but it will be consistent with the player's preferred font choice.
> Bugfix: Fixes some font issues

- BondageClub/Assets/Female3DCG/Female3DCG.js
A handful of small fixes to some asset definitions:
* Removes a duplicate `Clothing: true` property on the Corset asset group
* Removes duplicate `Random: false` properties from the Futuristic Cuffs, Ankle Cuffs and Leg Cuffs
* Removes the explicit `Priority` property from the Reverse Bunny Suit in the socks group - this was causing it to render above most items in the `ClothLower` group, and there don't seem to be any issues with it simply inheriting the socks group's priority
> Bugfix: Minor asset definition fixes

- BondageClub/Scripts/Server.js
Properly clears the `LoginSubmitted` flag on server disconnect to avoid softlock when server crashes during player's (re)login.
( Also server disconnects are properly shown instead of "Validating name and password" )
> Fix softlock when disconnected during login

- BondageClub/Screens/Room/Photographic/Dialog_NPC_Photographic_Sub.csv
The 'Relax your arms' option to make the Photography NPC return her arms to normal position was referencing the wrong thing.
> Photography NPC Pose fix

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Room/Shop/Shop.js
- BondageClub/Scripts/Dialog.js
- BondageClub/Scripts/Drawing.js
- BondageClub/Scripts/GLDraw.js
1. In rare cases when a character is particularly tall (for example is max height, wearing tall boots and has a ponytail), a portion of the top of their head would not be displayed. This cutoff was intentional so that ceiling restraints in the lower row of a chatroom would not spill up onto the upper row. However outside of chatrooms, there are cases where there is no 'ceiling' and we'd rather always display the character in full. The DrawCharacter calculations have been enhanced to make sure it only applies this cutoff where it needs to.
2. The asset zones in the arousal preferences screen were sometimes not lining up with the character. The zone functions have been corrected and further refactored.
3. Full-body alpha masks for WebGL drawing were misaligned. Now corrected.
I've redone …
> Height Rework Fixes

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Inventory/ItemMouth/BallGag/BallGag.js
- BondageClub/Screens/Inventory/ItemMouth/WiffleGag/WiffleGag.js
The new extended gag types were missing gagging effects, causing them not to gag when applied.
> Beta Fix: Fix for extended gags not gagging

- BondageClub/Screens/Character/Preference/Preference.js
Fixes a typo on setting the last chat room which causes the option to be forced on players whenever they open the preference screen. Should only affect Extreme mode now.
> Fixes LastChatRoom being forced on hardcore players

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Scripts/CommonDraw.js
Adding the colour schema in for Hands, so that they pass validation and don't disappear.
While this shouldn't be necessary, since they're hidden from the player and should only need Default + InheritColor from BodyUpper, all saved wardrobe outfits created back when Hands were editable will have them saved as Color = White/Asian/Black, meaning the schema is needed.
> Hands Missing Fix

- BondageClub/Scripts/Character.js
- BondageClub/Scripts/Dialog.js
There was previously no easy way to reset expression item colors. I've added this functionality into the expression reset button for now. In the future, we might want to look at integrating "reset to default" functionality into the color picker itself.
> Bugfix: Expression reset button now resets expression colors as well (where applicable)

- BondageClub/Scripts/Drawing.js
A small fix to the new drawing method for how the width is calculated so that the height ratio is applied to the destination width instead of the source width. It worked fine on most browsers but on iOS using a source width greater than the canvas width failed to draw.
> DrawCharacter on iOS fix

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Due to this:
https://cdn.discordapp.com/attachments/797897462694019093/798246477809057872/unknown.png
It became pretty clear that remaking private rooms as public will lead to a lot of spam (and also players being separated!). So instead of remaking them as public, they are instead remade as private with the caveat that the remaker is now an admin. So they can change the room parameters if they want to make it public, or choose to stay private, respecting people's wishes.
This has the side effect of making players less helpless, as the admin player can always make a private room public, wait for people to join, lock the room, and then F5 (since players cannot rejoin a locked room), but this was always possible if you were the room creator in the first place. It was also possible to use an …
> Auto-Remake rooms now remakes private, adding player as admin

- BondageClub/Assets/Female3DCG/Female3DCG.js
Boots and feet go wonky when spread-eagle tied by the legs to the bed. 
The setting to hide boots has been moved from X-Cross (which was the only Spread applying item before) into the pose itself.
> Spread Legs Boot fix

- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Adding back in the function to clear the room data when kicked to prevent immediately re-entering it.
> Kicked Room Rejoin fix

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Screens/Character/ItemColor/ItemColor.js
- BondageClub/Scripts/ColorPicker.js
- BondageClub/Scripts/Dialog.js
This is something of a follow-up to #1882, as I feel that fully resetting a character's expression to reset their expression color to default doesn't fully meet the needs of players. This does two things:
* Adds support for the special "Default" keyword to the color picker - typing "Default" into the input box will reset an item (or layer) to its default color
* Adds support for a new reset button to the color picker which will reset an item (or layer) to its default color (by auto-filling the input with "Default")
Below is an image of the updated color picker with the default button:
> Feature/Beta Fix: Adds a "reset to default" button to the color picker

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
When the 'Block OOC when gagged' setting is on, messages like "(OOC talk)" would be blocked but "something (OOC talk)" would not. Fixed the check to block the latter as well.
> Blocked OOC Gagged Workaround Fix

- BondageClub/Scripts/Server.js
This took longer than I care to admit to track down. As part of #1387, the chunk of code which removes lock member numbers from invalid sources got moved from `ServerAppearanceLoadFromBundle` into `ServerValidateProperties`. In the process, part of it was mis-translated, causing an issue where any appearance bundle load from someone that was neither an owner nor a lover of the player would strip any lover or owner locks from their appearance (because `NA.Asset` is always defined).
Needs 3 characters:
* Character A
* Character B - owner and/or lover of Character A
* Character C - neither owner nor lover of Character A
1. Character B applies an item to Character A and owner/lover locks the item
2. Character C then applies an extended item to Character A (or anything that will trigger a …
> Beta fix: Vanishing lover/owner locks

- BondageClub/Scripts/Timer.js
Not strictly a bug with the current beta, but when timer locks expire, they won't trigger chatroom messages if the player is in their wardrobe, information sheet, etc. This fixes that.
> Bugfix: Allows timer locks to trigger chatroom messages in other chatroom subscreens

- BondageClub/Assets/Female3DCG/Female3DCG.js
The Suspension pose doesn't actually affect the arms or legs, as that's always determined by another pose it's paired with (e.g. LegsClosed). So it doesn't need to belong to the BodyFull category which makes it block arms/leg pose changing.
> Suspension Pose fix

- BondageClub/Screens/Inventory/ItemArms/FullLatexSuit/FullLatexSuit.js
I'm not quite sure if this is specifically a beta problem, or when exactly this broke (probably due to a change in the behaviour of `CharacterRefresh`), but the full lockdown suit's wand was not being properly updated in chatrooms when added. This adds a `ChatRoomCharacterItemUpdate` call to ensure that it is updated properly for other players.
1. Character A adds a Full Lockdown Suit to Character B
2. Character A adds a wand attachment to the lockdown suit
3. Notice that the wand is not added on Character B's screen
> Bugfix: Ensures an item update when the full lockdown suit's wand gets added

- BondageClub/Screens/Character/ItemColor/ItemColor.js
I just noticed that I'd left in a `console.log` statement that I was using to debug the recent color picker change which is no longer necessary.
> Bugfix: Removes an unneeded console.log call

- BondageClub/Screens/Inventory/ItemFeet/HempRope/HempRope.js
The new bed spread eagle pose for the feet hemp rope did not include a `LegsOpen` prerequisite. In order to add this I needed to add a validate function (similar to the web in the arms group), to prevent the rope from conflicting with itself.
1. Add a toe-binding item (e.g. hemp rope in `ItemBoots`)
2. Add hemp rope to the `ItemFeet` group
3. Select the bed spread eagle type
4. Note that the player is forced into the legs spread pose, but the toe tie is still applied
> Bugfix: Prevents the bed spread eagle hemp rope type from ignoring toe ties

- BondageClub/Assets/Female3DCG/LayerNames.csv
The name of the ceiling cuffs layers was starting with 'ItemLegs' instead of 'ItemArms'. This PR fixes that.
> Hotfix: Correct a naming error on the ceiling cuffs layers

- BondageClub/CSS/Chess.css
- BondageClub/index.html
This fixes an issue where the squares of the chessboard overflow the rows at certain window widths in Firefox (see image below). This is likely due to some internal rounding error in the way Firefox calculates the widths/positions of floated elements. I've added a new `Chess.css` file, separate from the existing library file, which modifies the CSS on certain chessboard elements to make it a bit more robust. It also moves the file letterings over to the right of the squares so that they don't overlap with the rank numbers. Tested and working on Firefox, Chrome and Edge. I've not tested Safari, as I don't have a Mac, but there shouldn't be anything in the added CSS that should cause issues.
Before fix:
After fix:
> Bugfix: Fix for chess square overflow in Firefox

- BondageClub/Assets/Female3DCG/LayerNames.csv
Fixes missing layer names for Futuristic Cuffs in `ItemArms`. Also removes 2 unused layer name entries.
> Bugfix: Fixes the layer names for the Futuristic arm cuffs

- BondageClub/Assets/Female3DCG/Female3DCG.csv
As part of #1794, the strict posture collar and the latex posture collar got moved in `Female3DCG.js`, but their names weren't moved inside `Female3DCG.csv`, causing some of the collar names to show up incorrectly in game. This moves the names in the CSV to match their order in `Female3DCG.js`.
> Bugfix: Fixes posture collar name orderings

- BondageClub/Assets/Female3DCG/Female3DCG.js
The alpha masks on the open straitdress were being applied to all layers, resulting in visual issues with some items (see image). This changes the masks to target specific groups, and also revises the `Hide`/`HideItem` arrays. This should remove any bad combinations, for now.
> Bugfix: Fixes alpha mask issues with the open straitdress

- BondageClub/Scripts/Character.js
For extended items with custom elements created in the Load function, such as the wooden sign or custom name tag, if the item is removed while the player is viewing the item's screen these elements were still left behind. E.g. the wooden sign's text input would stay stuck on the screen.
This is because the item's exit function never gets called. Now it will be.
> Fix: Extended item removal while viewing

- BondageClub/Assets/Female3DCG/Female3DCG.js
The PetSuit was missing an `AllowBlock` entry for `ItemVulva`, meaning that the item never blocked the vulva zone, even when zipped.
> Bugfix: Adds a missing AllowBlock entry to the Pet Suit

- BondageClub/Scripts/Common.js
This PR adds retry logic to the `CommonGet` function. Occasionally, GET requests (usually for CSVs) will fail, usually due to an intermittent error. That then results in textual errors like those below, which can only be resolved by exiting/re-entering the screen, or in some cases by refreshing the page completely. This change should prevent the vast majority of those cases. If a request succeeds first time, the current behaviour is preserved.
Retries are backed off exponentially up to a limit of 60 seconds between retries, and by default a request is retried a total of 10 times. If no successful response is received after 10 retries, the function will stop retrying.
This is the console log output and network requests for a request that has failed 10 times:
And this is the output for a …
> Improvement: Adds retry logic to CommonGet

- BondageClub/Scripts/Drawing.js
When a chat room has two rows, fall letters in names (g,j,p,q,y) get cut off at the bottom. This often makes them quite hard to read, for instance trying to distinguish v from y or i from j.
This change will move the names up enough to make the letters readable, tested across various fonts. It will only apply in this two-row-room situation, since in every other instance there's already space for the name.
> Chatroom Cut-off Name

- BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
- BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
- BondageClub/Screens/Inventory/ItemArms/Web/Web.js
- BondageClub/Screens/Inventory/ItemFeet/HempRope/HempRope.js
- BondageClub/Scripts/ExtendedItem.js
Web and hemp hope on feet both have a custom validation function to work around cases where the item is blocking itself from being changed by failing the prerequisite check of the new type.
This moves the remove-validate-reapply process into the general ExtendedItem script and adds a new property that calls it, and only to the item types that need it.
Also added the setting to hemp rope and chains for arms to fix that same issue for them.
> Extended Item Self-Blocking Validation

- BondageClub/Assets/Female3DCG/Female3DCG.js
Raises the wooden sign to priority 57 so that is displayed in front of the display frame.
> Fix: Raise wooden sign priority

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Last one for today! This PR makes some simple optimisations to the chatroom code to reduce the amount of work done when just idling in a chatroom. I selected the optimisations based on running a CPU profiler over the chatroom, and identifying optimisations to functions (outside of the draw functions) that took a notable amount of time. They aren't huge performance improvements, but they're a couple of simple "easy wins" to reduce the game's overhead in chatrooms, and might benefit those with slower devices.
The changes that were made are:
* Reduces duplicated use of `Player.GetGagLevel()` and `Player.IsSlow()` by calculating once and assigning to a variable
* Reduces the overhead of the `ChatRoomTarget()` function - this gets called every frame and was accounting for about 7% of CPU time …
> Improvement: Simple chatroom optimisations

- BondageClub/Scripts/Dialog.js
Aligns the "Up" button's height to the other buttons of the left hand side (namely face and pose changes).
Before:
After:
This is solely UI-design related, so no extensive testing was done. The button still works as intended...
> Fix: Aligns the Up-Button with the left hand side ones

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
This fixes a few issues with the handling of hidden chat messages, probably largely as a result of bad merge resolutions. This PR:
* Removes duplicated handling of `MaidDrinkPick`, `PayQuest` and `OwnerRule` messages
* Changes remaining `if` statements into `else if` statements for efficiency
* Removes the blanket `return` at the end of the hidden message handling block - this was causing owner & lover rules to not show up in the chat (their type gets modified when the hidden message is handled, and the type is no longer `Hidden` after modification)
> Bugfix: Fixes for hidden chat message handling

- BondageClub/Tools/Node/AssetCheck_Types.js
This adds asset property definitions to the asset type check script for the new asset properties that were added as part of #1936 (I was going to update that PR, but it got merged before I could).
> Bugfix: Adds type definitions for the new asset properties

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Screens/Character/Appearance/Text_Appearance.csv
This refactors the appearance/clothing code so that the row of buttons at the top are built dynamically, similar to the menu buttons in the inventory items screen.
This will mean better use of space, make it easier to add new buttons, and reduces the work in the Run function.
The behaviour is all the same as before except in the Wardrobe and Permissions subscreens, which now use the green tick/accept button to jump back one screen instead of having unique "dress manually" and "reset" exit buttons, to make them more consistent with the rest of the appearance subscreens.
> Appearance Dynamic Menu Buttons

- BondageClub/Screens/Character/Login/Login.js
- BondageClub/Screens/Character/OnlineProfile/OnlineProfile.js
- BondageClub/Screens/Character/OnlineProfile/Text_OnlineProfile.csv
- BondageClub/Screens/Character/OnlineProfile/Text_OnlineProfile_DE.txt
- BondageClub/Screens/Character/OnlineProfile/Text_OnlineProfile_FR.txt
- BondageClub/Screens/Character/OnlineProfile/Text_OnlineProfile_RU.txt
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Character.js
Extension of #1956 by @Shiranui-Izayoi 
> Lengthened the Chat Messages to 1000 characters so 4 times the original length because honestly 250 is way to short for more detailed RP.
> 
> Lengthed the max length of Bios to 10,000 characters as it is crazy hard to explain yourself in 1000 characters. While most likely won't use it, it is nice for those that do.
> 
> If there is a reason that it is limited like this then please let me know. But to my knowledge there is no reason for it to be like this. Since it only hurts those that want to go into more detail. Like myself.
Additionally the Bio is compressed (if it is efficient or required) on update and decompressed on character load.
**Breaking changes:**
Current version users will see beta user's description as `╬` + lots of random …
> Longer messages & bio (with bio compression)

- BondageClub/Scripts/Dialog.js
Fixed a bug were SpankingToys were replicated infinetely in the ItemHands slot, when this slot was blocked for items but not for activities.
> Bugfix: Infinite Replication of SpankingToys

- BondageClub/Screens/Inventory/ItemFeet/HempRope/HempRope.js
The ItemFeet ropes which tie the legs to the bed were blocking the character from interacting with anything, as if their arms were bound.
> Bed Rope access fix

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
- BondageClub/Screens/Online/GameLARP/GameLARP.js
- BondageClub/Screens/Room/Shop/Shop.js
- BondageClub/Scripts/Dialog.js
- BondageClub/Scripts/Drawing.js
- BondageClub/Scripts/ExtendedItem.js
- BondageClub/Scripts/VibratorMode.js
The game uses asset previews in several locations, and despite the existence of a `DrawItemPreview` function, it is only used in a couple of places. This made it a lot harder to chase down all of the preview images when reworking for #1936.
This PR reworks the `DrawItemPreview` function into two new functions: `DrawAssetPreview` and `DrawPreviewBox`, and changes all preview images across the core game to use them. It also breaks the horrible ternary operator in `Appearance.js` for determining the preview color into its own slightly more efficient and much more readable `AppearanceGetPreviewImageColor` function.
After this, the `DrawAssetPreview` and `DrawPreviewBox` functions could be used across most extended item screens, but I've not done that here to keep the scope of this PR down. …
> Refactor: DrawAssetPreview

- BondageClub/Screens/Character/Appearance/Appearance.js
This fixes an issue with the `AppearanceClick` function that would cause an extra click to appear to be registered when transitioning between the default mode and the cloth selection mode. It changes the handling of each appearance mode to be in its own `else if` block, so click handling should only happen for one mode per click. 
Previously, the click handler for the default `""` appearance mode contained this line:
```js
CharacterAppearanceMode = "Cloth";
```
However, the click handler would then proceed into the `if (CharacterAppearanceMode == "Cloth")` statement, causing the `"Cloth"` mode handling code to be run.
1. Enter the appearance screen
2. Click one of the appearance groups
3. This takes you into the item submenu as usual, but also seems to register a click on whichever item …
> Bugfix: Fixes double clicks on the appearance screen

- BondageClub/Screens/Character/Appearance/Appearance.js
Follow-up to #1999 - the addition of `else if`s in that PR causes an issue with the `ItemColor` click handler not being called for clicks in the top menu. This increases the priority of the click handling for color mode, which fixes the issue.
> Bugfix: Fixes a click handler ordering issue in the appearance menu

- BondageClub/Scripts/Dialog.js
A function in the dialog leave was not renamed properly. Probably due to merge conflicts.
> Height Function Fix

- BondageClub/Screens/Character/Appearance/Appearance.js
I haven't quite traced back to exactly what caused this, but it was a while ago (before Nina's appearance menu changes at least). When the appearance screen is in the `Cloth` subscreen, clicking on an item no longer displays that item in pink as the first item in the list. This adds a call to `DialogInventoryBuild` after selecting an item, which restores that functionality.
> Bugfix: Rebuilds appearance inventory when selecting an item

- BondageClub/Scripts/Inventory.js
This fixes an issue with limited permission checks against handheld toys. the `InventoryCheckLimitedPermission` function wasn't using the dynamic asset/group names when running the check for whether an item's permission was limited.
1. On character A, set an individual spanking toy's item permission to limited (e.g. the cane)
2. Set character A's global item permission to "Everyone, no exceptions", "Everyone, except blacklist", or "Owner, Lover, whitelist & Dominants"
3. On character B (who should not be on character A's whitelist, or their lover/owner), equip the spanking toy selected in step 1
4. Note that character B can still use the spanking toy on character A
> Bugfix: Fixed limited permission check for individual spanking toys

- BondageClub/Screens/Character/Creation/Creation.js
- BondageClub/Screens/Character/Login/Login.js
- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Character.js
No functional change (but maybe fixes some edge-case bugs)
Moves things around in `PreferenceInit`, making it more clear and removes unnecessary or temporary parts.
Tested with both new and existing accounts.
~~Will create conflict with #1669 and #1985 ; I recommend merging those before this as my changes are easier to fix.~~
> Refactor: Unify Preference Init

- BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
Makes it so you need to be able to unlock the collar in order to toggle whether or not permissions are open on the collar. This is to prevent trolling where someone changes your settings and leaves you stuck with them until your owner helps you.
> Futuristic Collar Permission

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Adds a new immersion setting to hide messages from others such as adding restraints and activities.
Also fixes a bug (in the same block of code) with stimulation messages where the sender would stimulate herself instead of the target. Now both the sender and the recipient will be stimulated~
> Sensory deprivation messages

- BondageClub/Scripts/Drawing.js
In #1507, the `DrawRun` function would not get properly refreshed if a screen change happened at the same time as a `CharacterSetCurrent` call, resulting in a stale `DrawRun` function being used - this was only an issue for minigames where leaving the minigame would return the player into dialogue.
> Bugfix: Ensures that the DrawRun function always gets refreshed properly

- BondageClub/Scripts/Drawing.js
Draws a grey background if background image isn't ready, preventing things like this from happening:
> Improvement: Draw empty background

- BondageClub/Scripts/Drawing.js
This change seems very minor, but in places with lots of buttons without text (only using images, like MainHall) I measured almost 20% improvement in performance
> Improvement: Don't draw empty text

- BondageClub/Scripts/Character.js
Added code so that the properties of the saved outfits in the wardrobe are compressed and decompress.
Currently when saving an outfit the properties of an outfit will be saved such as if a Latex Corset has garters or not. But upon logging out and logging back in, as the properties are not compressed or decompressed when loading that same outfit it will default to it's default state.
I believe that this is unintended and just slipt through the cracks due to the low amount of clothing items with properties. I did do some testing and it did seem to work fine with no adverse effects.
> Wardrobe Compresses & Decompresses Properties (FIX)

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
With "Hide others messages" and "Sensory Deprivation: Total" enabled in the immersion options, being totally blind and deaf will now outright hide all chat messages and emotes from other players, unless the emote has the player's name in it (not case sensitive).
This means that unless someone physically interacts with you or whispers to you, you have no way of knowing that someone is in the room with you.
> Increased sensory deprivation level

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
E.g.
"Ada laughs at Bob"
becomes "Someone laughs at Someone"
This does not replace the player's name, however, so "Charlie tickles Ada" becomes "Someone tickles Ada," assuming I am Ada.
This may be an issue if someone's name is a common word, like slave. For now, it only works if the first letter of the name is capitalized, so if someone types "Charlie tickles slave" and slave is in the room, then slave will not get replaced.
> In Sensory deprivation, player names in emotes get replaced with Someone

- BondageClub/Screens/Character/FriendList/FriendList.js
- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
- BondageClub/Scripts/Common.js
- BondageClub/Scripts/Drawing.js
- BondageClub/Scripts/Notifications.js
- BondageClub/Scripts/Server.js
- BondageClub/index.html
Changes:
- A new option has been added to raise a notification when someone enters the chat room while the player is not focused on the window, which can be restricted to owners and/or lovers and/or friends only.
- An option to trigger the 'beep' sound on receiving a notification has been added. This setting is available in the Audio preferences screen as well. The sound will only occur for the first instance of a notification type. For example one chat message and one player entrance will prompt two beeps, whereas two chat messages will only prompt a beep on the first message. This won't occur for Beep notifications since player beeps already have a dedicated sound setting.
- The notifications code has been moved into its own file instead of cluttering up Common.
- The code to create a …
> Notifications Enhancements

- BondageClub/Scripts/GLDraw.js
A new `u_alpha` uniform was added to most of the shaders in `GLDraw.js` as part of #1931, where most of the time it could have just been added to the `u_color` uniform vector. This PR reworks that to remove the unneeded variable. Thanks to @NoneNoname for pointing that out!
> Improvement: Removes unneeded uniforms from GLDraw shaders

- BondageClub/Scripts/Dialog.js
With the introduction of the color picker to the expression menu, and the modification to the reset button, the reset button now removes players' lip color, which was something of an oversight - it seems logical to have the reset button only reset colors on groups that aren't body parts. This PR prevents the button from resetting a player's mouth color.
> Bugfix: Prevents expression reset from removing lip color

- BondageClub/Screens/Inventory/ItemMisc/HighSecurityPadlock/HighSecurityPadlock.js
- BondageClub/Scripts/Inventory.js
- BondageClub/Scripts/Server.js
This makes several small fixes to certain lock functionality. ~~I'd be grateful if @Ada18980 could cast an eye over this to ensure that I've not inadvertently broken anything about lockpicking or the high security padlock (although I've tested it, and it seems to work fine)~~ (Ada has confirmed that this shouldn't cause any issues).
Fixes:
* Fixes an issue where `MemberNumberList` was being incorrectly set to a string in `InventoryLock`, rather than an array, which broke use of `MemberNumberList` in timer padlocks
* Fixes an issue where people were unable to add/remove timer from owner timer padlocks
* Fixes a problem where the "Append owner" feature of the high security padlock was appending the owner's name rather than their member number
* Fixes an issue where the "Append lovers" …
> Bugfix: Several lock-related fixes

- BondageClub/Scripts/Dialog.js
##
This fixes an error when viewing an equipped item via the dialog screen which intrinsically has the `Lock` effect (e.g. the metal cuffs or the four limbs shackles). The code was erroring because `InventoryGetLock` was returning `null`.
> Bugfix: DialogHasKey error fix

- BondageClub/Scripts/Drawing.js
The hover text for the back/next arrows for clothes groups in the Appearance screen were the wrong way around.
Thanks to @elliesec for spotting it!
> Clothes Back/Next Fix

- BondageClub/Scripts/ExtendedItem.js
This ensures that any cleanup on items that have extra features (e.g. input boxes) in their extended menus gets executed in single player areas.
> Bugfix: Ensures an extended item's exit function is called on extended item type selection

- BondageClub/Screens/Character/Login/Login.js
This fixes disappearing owner/lover locks on relog by changing the `LoginResponse` function to report that the appearance bundle originated from the player themselves. I'm not exactly sure why this wasn't already an issue, but this should fix it.
> Bugfix: Fix for disappearing lover/owner locks on relog

- BondageClub/Screens/Character/Appearance/Appearance.js
After the menu button refactor, the wardrobe only had an Accept button which jumped back up to the main appearance screen, maintaining the 'Dress manually' behaviour from before. Having to then Cancel from that screen in order to not save the wardrobe change was counterintuitive and was reported as an issue by users.
Now the wardrobe screen has a Cancel button of its own that restores the appearance from before entering the wardrobe, and jumps back up to the main appearance screen to stay consistent with other subscreen accept/cancel button behaviour.
> Wardrobe Cancel Button

- BondageClub/Screens/Inventory/ItemVulva/ClitAndDildoVibratorbelt/ClitAndDildoVibratorbelt.js
Back in #2004, I removed some duplicated click handler logic for some vibrator items which had invisible exit "buttons" independent of their actual exit buttons. In the case of the Clit & Dildo Vibrator Belt, I accidentally deleted the wrong click handler, so you can only exit the extended item screen by clicking 200px lower than the actual button. This fixes that.
> Bugfix: Fixes the click handler for the clit & dildo vibrator belt

- BondageClub/Scripts/Dialog.js
Lovers couldn't unlock high security or intricate padlocks, which seems incorrect given that game has always followed the general rule of owner > lovers > everyone else.
> Bugfix: Ensures lovers can unlock intricate/high security locks

- BondageClub/Scripts/Server.js
This fixes _another_ issue with disappearing owner/lover locks on full appearance updates. This prevents that (and actually makes the `ServerAppearanceLoadFromBundle` function very slightly more efficient). The issue was caused by the `Property` object being assigned to the `NA` object referencing the same object as the original property. The lock then got removed from the `NA` item, but the asset wasn't pushed to the `Appearance` array due to an existing item. I've accordingly moved the `CanPush` logic up to before the asset is recreated, and the code now skips the creation of the `NA` item completely if it's never going to push it to the `Appearance array.
I've tested everything I can think of to make sure owner/lover locks are now behaving as expected:
* Fixes to owner timer locks in …
> Bugfix: More disappearing locks

- BondageClub/Scripts/GLDraw.js
Fixes following warning in console: `RENDER WARNING: texture bound to texture unit 0 is not renderable.`
The reason for this warning is attempt to render not yet loaded texture.
The fix works by assigning empty, 1px transparent texture, that is replaced when image loads
> Fix: Render warning

- BondageClub/Scripts/ExtendedItem.js
- BondageClub/Scripts/ModularItem.js
This restores previous behaviour on the High Security Straitjacket where it was not possible to modify a locked straitjacket without being able to unlock it. It also fixes an error that occurs in the extended item script for the validation of extended item options that have no `Property` (which wasn't an issue until modular items).
> Bugfix: Modular item framework fixes

- BondageClub/Screens/Character/Appearance/Appearance.js
For assets that had both Item and Clothes versions, the button background was not properly set to red in permissions-mode when the item is blocked.
> Item Permissions Colour fix

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Scripts/CommonDraw.js
Hands were removed as a separate appearance option relatively recently and will always take the colour Default which lets them inherit the BodyUpper colour. However saved wardrobe slots from before that time will have Hands saved with a non-Default colour. Trying to change the body colour after loading a slot will leave the hands at the old colour with no way to change them. This forces hand colours to always be Default.
> Hands Colour Fix

- BondageClub/Screens/Room/MainHall/MainHall.js
Since the High-Security lock can only be unlocked by owners/lovers and the equipper (plus anyone the equipper delegates) but can be applied by anyone, someone without an owner/lover could be permanently locked into a corset or other non-restraint item by a stranger.
Adding the lock to the 'strong lock' list alongside others like the password locks to prevent this.
> Add High Security Lock to Strong Locks

- BondageClub/Screens/Inventory/ItemMisc/PasswordPadlock/PasswordPadlock.js
Not exactly a beta fix - this just prevents the hints on password locks from overflowing for particularly long hints by using `DrawTextWrap` instead of `DrawText`.
Before:
After
> Bugfix: Stops long password lock hints from overflowing

- BondageClub/Scripts/Dialog.js
Whenever anyone successfully picked a lock on themselves, the screen would freeze.
> Self Lockpick Fix

- BondageClub/Screens/Room/MainHall/MainHall.js
When the player automatically enters a chatroom on logging in, then later talks to the main hall maid, the dialog functions don't work. In particular trying to get released doesn't work and returns an error of 
> Trying to launch invalid function: MainHallChatSearchMaidReleasePlayer
This is because by the time the dialog functions are being created, `CommonScreen` is "ChatSearch" instead of "MainHall" as required. This error predates this release.
Now the loading of the NPC is delayed until the player loads the main hall when not about to jump into a chatroom.
> Main Hall Maid Release fix

- BondageClub/Assets/Female3DCG/Female3DCG.js
The `HairAccessory1` version of the halo was missing an `AllowType` array, causing selection of the "Broken" type not to persist properly.
> Bugfix: Adds a missing AllowType to the Halo in HairAccessory1

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
This has actually been broken since #1387 got merged. In that change, `ChatRoomSyncItem` stopped using the `ChatRoomAllowChangeLockedItem` check, which meant that items with the `AllowRemoveExclusive` property (i.e. the Lovers Vibrator) could no longer be properly removed by people that weren't lovers/owners. This reworks the `ChatRoomSyncItem` function slightly to use `ChatRoomAllowChangeLockedItem` again, which should re-enable the `AllowRemoveExclusive` property, whilst also blocking other changes from non-lovers/owners. As this is (kind of) another lock validation change, I've checked:
* Non-lovers/owners are unable to add/remove lover/owner only items unless they have the `AllowRemoveExclusive` property, even through the console
* Non-lovers/owners can't remove lover/owner-locked …
> Bugfix: Re-enables removal of assets with the AllowRemoveExclusive property

- BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
This causes the futuristic vibrator to use the default triggers when it is first equipped, without the need for someone to visit its extended item menu first. If no triggers have been set, the vibrator will respond to the default triggers in `ItemVulvaFuturisticVibratorTriggers`.
> Bugfix: Ensures Futuristic Vibrator works with the default triggers on first equip

- BondageClub/Assets/Female3DCG/Female3DCG.js
This removes a few `LockLayer: true` properties from the Lock Necklace, Love Chastity belt and High Security Straitjacket that were accidentally added by #2070, which were causing the items' `Lock` layers not to display.
> Bugfix: Removes incorrect LockLayer properties

- BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor.csv
- BondageClub/Screens/Room/Shop/Shop.js
This fixes an infinite loop in the shop job that can occurs if the player is wearing a gag that doesn't muffle their speech (e.g. the futuristic gags in padded mode). I've removed the `while (true)` altogether and replaced it with a safer alternative, and added dialogue lines to the shopkeeper to handle this case
1. Equip arm, ankle and leg cuffs, but don't connect them
2. Equip a futuristic gag and set it to padded mode
3. Start the shop job. The shopkeeper should give you a blindfold (the issue only occurs if the blindfold doesn't also gag the player)
4. After completing the job (either successfully or unsuccessfully), ask to try again
5. The game will freeze in an infinite loop, as all demo groups are occupied, so the `while` loop in `ShopJobRestrain` will never terminate
> Bugfix: Fix for an infinite loop in the shop job

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
This will avoid mistresses having to whitelist their subs to allow subs to hand over their keys~
> Remove AllowItem from security action prerequisites

- BondageClub/Screens/Online/GameLARP/GameLARP.js
Fixes an issue which causes a crash in LARP when a player tries to select an item, caused by accidentally mistaking the `Item` variable for an item rather than an asset back when I made the preview image changes in #1989.
> Bugfix: Fixes a crash in LARP item selection

- BondageClub/Assets/Female3DCG/Female3DCG.js
Some of the corsets in ItemTorso that were converted to copy the Corset versions were no longer being hidden in the AllFours pose, resulting in them hanging below in midair.
> AllFours ItemTorso fixes

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
The chat room Kneel button would always make the player stand on the first press if they had any pose other than kneeling. Even if that pose was already standing in some form, e.g. legs closed or arms in any pose. 
Now it should always make the player kneel or stand as expected and will no longer remove the arms pose.
> Kneel Button Fix

- BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
- BondageClub/Scripts/Element.js
This fixes an issue where the Futuristic Vibrator's extended item menu would crash if the vulva zone was blocked. If the zone was blocked, the inputs were not being added, and subsequently calling `ElementPosition` in the draw function would crash. I've put in a fix to the `ElementPosition` to ensure it logs a warning in such situations, and I've modified the extended item screen for the vibrator the vibrator now functions properly regardless of whether or not the zone is blocked.
> Bugfix: Futuristic vibrator crash

- BondageClub/Screens/Room/Shop/Shop.js
- BondageClub/Scripts/Inventory.js
Because the new handheld vibrator remote is in the same buy group as the existing vibrator remotes, it can be purchased in the shop to bypass the "cannot buy remotes" owner rule, and is not confiscated at the same time as other remotes, causing them to appear in the player's inventory on their next login. This PR fixes these issues.
> Bugfix: Prevents the handheld remote from bypassing remote owner rules

- BondageClub/Screens/Character/InformationSheet/InformationSheet.js
With the addition of the lockpicking skill, the skill modifiers in the information sheet can now overlap with the skill list if the player has every skill in the game (see image). Luckily, there's still (just about) space to move the skill modifiers down a line.
> Bugfix: Stops skill modifiers from overlapping skills in the information sheet

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Scripts/Inventory.js
This adds the floor shackles to the list of "leg spreader" items in the `NoFeetSpreader` prerequisite, as they have incompatibilities with several arm items that would usually force the legs closed (see pictures). It also adds the `CanKneel` prerequisite to the strict leather pet crawler in line with the pet suits.
> Bugfix: Compatibility fixes for the floor shackles

- BondageClub/Scripts/Server.js
This adds an additional check to `ServerValidateProperties` to check if Item.Property.Effect is an array.
This missing check actually was abused by a player to purposefully crash other player's clients.
This very same bug could be abused to enter chat rooms invisible under other circumstances
> Fix for crash if character with invalid effect enters the chat room

- BondageClub/Screens/Room/MainHall/MainHall.js
- BondageClub/Screens/Room/MainHall/Text_MainHall.csv
It's been requested a few times to make it harder to hit the Main Hall's exit button and accidentally log out. Now it shows a popup to confirm the exit and give a chance to cancel.
> Exit Club Confirm

- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
When a player 1) has the rejoin chatroom setting on, 2) does not have the room recreate setting on, and 3) tries to rejoin a room that no longer exists, then they're greeted with an empty search screen and the "No chat room found" message which doesn't really communicate what happened.
Now in such cases the "Room doesn't exist anymore" or "This room is already full" messages will appear in the bottom left as they normally would if the user clicked on a room button. The Search button will now reset the message as well.
> Rejoin Failed Message

- BondageClub/Screens/Room/AsylumMeeting/AsylumMeeting.js
- BondageClub/Screens/Room/AsylumMeeting/Dialog_NPC_AsylumMeeting_PatientLeft.csv
Adds lockpicks to the list of items you can buy from the asylum patient in the meeting hall. Allows subs to get lockpicks even if their owner doesn't let them. The owner can still confiscate them though.
I think this is acceptable because you can already be given lockpicks by other players and it adds a bit of a puzzle to subs stuck in intricate locks.
> Lockpick Dealer

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Inventory/ItemDevices/Coffin/Coffin.js
- BondageClub/Screens/Inventory/ItemDevices/CryoCapsule/CryoCapsule.js
This changes the behaviour of the Cryogenic Capsule and the Vampire Coffin so that they are easy to escape from when open, even if locked. Previously when locked, they would have an effective base difficulty of 48 when open, and 54 when closed. Now they have a base difficulty of -20 when open, and 30 when closed.
> Change: Modifies the difficulties of the cryo capsule & coffin

- BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
Due to a bug, a collar on the wearer was required for futuristic item settings to be locked out if a player cannot unlock it. Now the player is locked out if they don't have a collar either.
> Collar no longer needed for futuristic items to be locked out

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
- BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js
- BondageClub/Scripts/Activity.js
There is a list of keywords in emotes that trigger a shock or inflation, and the activities one can do while gagged also cause the items to trigger.
> Futuristic panel gag and shock collar now trigger on activity and emote

- BondageClub/Screens/Character/Login/Login.js
- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Scripts/Inventory.js
- BondageClub/Scripts/Server.js
**Requires [Bondage-Club-Server#68](https://github.com/Ben987/Bondage-Club-Server/pull/68)**
Otherwise blocked and limited items are not correctly updated in some cases
**Includes #2137**
**Should only be merged the release after #2137 is fully deployed to stable version!**
Otherwise players would loose their inventory and blocked items as well as others would be unable to correctly interpret this player's!
Changes the format in which `Inventory`, `BlockItems` and `LimitedItems` are saved with focus on smallest size transferred over network, expecting per-message-deflate
> Improvement: Item save format

- BondageClub/Scripts/Common.js
- BondageClub/index.html
`R66Alpha` is not valid version.
The version **needs** to be in format `R[0-9]+(Beta[0-9]+)?`, otherwise code cannot tell which version is newer.
If alpha version is really desired, `R66Beta0` can also be used
> Fix: Game version

- BondageClub/Scripts/Asset.js
Correcting the buiding of the asset description list, since it included line breaks resulting in chat messages like this:
> (Player uses a ball gag
on her mouth
.)
> Asset description line break fix

- BondageClub/Scripts/Struggle.js
Some people have been making scripted rooms with very high bondage levels on applied stuff. This is making players stuck, so I am adding a cap for the difficulty in lockpicking so it can't be set to something ridiculous like 100.
> Fix lockpicking impossible for locks placed in scripted rooms

- BondageClub/Scripts/Struggle.js
This should solve issues of things like handheld toys bringing up the minigame choices.
> Removes the struggle options when not restrained and the item is unlock

- BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
- BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
- BondageClub/Screens/Room/MainHall/MainHall.js
- BondageClub/Scripts/Audio.js
- BondageClub/Scripts/Server.js
Certain audio playing cases (futuristic items and maid bell) were mistakenly treating a 0% volume setting as missing and ironically playing the sound at full volume instead. The function has been tweaked to fix such cases.
This also includes a fix for the futuristic chastity belt's audio trigger which wasn't checking whether the player was in a chat room properly.
> Audio Volume Fix

- BondageClub/Scripts/Struggle.js
2 fixes
1) Fixes the pin being unset when arousal ticks being a real set pin
2) Fixes arousal-related effects during lock picking not being disabled when the meter is disabled
> Lock picking arousal fixes

- BondageClub/Scripts/Struggle.js
Anytime when DialogProgressAuto >= 0, it will use the strength minigame to save time from picking a struggle option.
> Fix having struggle options for things like the bed

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Scripts/Dialog.js
A followup change for #2185: the preview character canvases will only be rebuilt when necessary. For example they won't be when selecting one of the items, since that just shuffles the inventory order.
> Character in Previews - Performance Improvement

- BondageClub/Screens/Online/Game/OnlineGameDictionary.csv
Matron will no longer detrain her target. She will detain her instead as she should.
> larp typo fix

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
In the last release, the "(Security actions.)" and "(Have a photo taken.)" dialog options for other online players were both added. Both have the potential to push the displayed options over the limit of 8 and make the "(Leave this menu.)" option disappear.
Now both have been moved inside the "(Character actions.)" option's page.
> Online Dialog overflow fix

- BondageClub/Screens/Character/Appearance/Appearance.js
When the player loads a wardrobe slot, its name is now loaded into the name input text box. And when the player leaves the wardrobe screen using the Accept button, the text in the box is remembered and reloaded on returning to this screen (unless the appearance screens are exited altogether).
This makes it much easier to load a wardrobe slot and make changes to it, since the name no longer needs to be re-typed when saving back down.
> Wardrobe Name Persistence

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
This rearranges the chat-hiding sensory deprivation change from #2042 so that it happens earlier and skips notifications for messages that won't appear, along with any other message-prompted steps we may add in future.
> Sensory Deprivation Message Hiding fix

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
If a player is in a chatroom subscreen and then is forced out of the room for any reason (kicked, leashed, etc) then various bugs can occur depending on the screen. 
I've corrected a few that I found. Namely: missing elements when re-entering the preferences or appearance screens if kicked when viewing them, and the text getting stuck aligned left instead of center if kicked from certain preference screens.
> Chatroom Subscreen Kicked Fix

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Increases chance from 10% to 30%, since gagged people dont have much to say anyway.
> Increase gag stimulation messages frequency

- BondageClub/Assets/Female3DCG/Female3DCG.js
The casing of the background name on the VR headset didn't match the casing of the checked in background file, causing 404s.
> Bugfix: Fixes incorrect synthwave background name casing

- BondageClub/Assets/Female3DCG/Female3DCG.js
Adding the Groups settings from MistressBoots into DeluxeBoots so that they don't cut rectangular chunks out of other items such as beds.
> Deluxe Mistress Boots alpha groups

- BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js
This fixes an incorrect reference in the collar auto shock unit where it was referencing `GagTriggerPunish` rather than `ShockTriggerPunish`, causing errors as below:
> Bugfix: Incorrect variable reference in collar auto shock unit

- BondageClub/Screens/Character/Creation/Creation.js
- BondageClub/Screens/Character/FriendList/FriendList.js
- BondageClub/Screens/Character/Relog/Relog.js
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Screens/Online/GameLARP/GameLARP.js
- BondageClub/Scripts/Notification.js
Some notifications were resetting and disappearing too quickly, before the user even refocused back on the game. 
This is because I assumed those functions that called the reset step only ran while the screen was active, but this is not true for all browsers.
Notifications broke after creating a new character rather than logging in. They will now be loaded properly. Also added safety checks to the raise/reset.
> Notification Fixes

- BondageClub/Screens/Character/Player/Dialog_Player.csv
- BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
Fixes the remote blocking being changeable on the futuristic collar when locked out, even if the open permissions setting is blocked.
Also adds a text message to make it clear to the user that they can't change the setting because the collar is locked.
> Futuristic collar permissions fix

- BondageClub/Scripts/Dialog.js
I encountered a rather weird crash with the handcuffs in front pose.
It turned out that this was a unhandled special case when adding an extended item with default "Lock" effect to an unowned lover which never occured until now since all default locked extended items until now were owner only.
However, this PR fixes this.
> Fixes crash when applying prelocked extended item to unowned lover

- BondageClub/Assets/Female3DCG/Female3DCG.js
Rearranging AllowPose for socks and shoes so that when a player has both the Hogtied and Spread poses applied (now possible due to the SpreaderMetal Wide option), the Hogtied image is used.
> Spread vs Hogtie fix

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Character.js
- BondageClub/Scripts/Drawing.js
This refactors the steps that draw the chatroom background into a separate function so it can be reused for the top and bottom rows, to help prevent mistakes like the recent case of the custom background being missing for the bottom row.
This also enhances the blindless level determination so that it can check for eye openness only. This fixes the issue of the VR headset's custom background always appearing, even when the character closes their eyes.
> Chatroom Background Drawing Refactors

- BondageClub/Screens/Inventory/ItemFeet/Chains/Chains.js
- BondageClub/Screens/Inventory/ItemFeet/HempRope/HempRope.js
When suspended by the feet, the kneel button is available which can result in kneeling in mid-air.
This adds empty `AllowActivePose` to the options so that they override the assets' `AllowActivePose: ["Kneel"]` and prevents kneeling.
> Suspension Kneel Fix

- BondageClub/Screens/MiniGame/Chess/BondageChess.js
- BondageClub/Screens/MiniGame/Chess/chess.js
- BondageClub/Screens/Room/CollegeChess/CollegeChess.js
The process to calculate the total major and minor values on both sides (`CollegeChessGameProgress`) was running every frame, but it miscalculated and undervalued black's value at some point during their move. This means when their move ended and the value went back up, it thought white lost pieces and punished the player even though no pieces had been taken.
This PR changes this calculation to only occur after a move has completed via an event instead. This avoids unnecessary recalculations and seems to have corrected the miscalculations.
> Chess Progress Change

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Correction to the background darkening which was causing the top row of a two-row chatroom to be darkened twice instead of once.
> Background Darkening Fix

- BondageClub/Screens/Character/Appearance/Appearance.js
Fix to prevent crashing on changing the option of extended clothes on other characters.
> Extended clothes on others fix

- BondageClub/Screens/Inventory/Glasses/EyePatch1/EyePatch1.js
This is somewhat related to #2241 (and also fixes the same issue for the eyepatch, although it makes sense to include both, as they fix slightly different things) - this adds the `IsCloth` argument to the extended item function calls in the eyepatch's extended item script. This ensures that the options are drawn in the correct place, and prevents the game from sending an appearance update every time the player modifies the eyepatch whilst inside their wardrobe.
> Bugfix: Corrects extended item arguments for the eyepatch

- BondageClub/Screens/Character/Appearance/Appearance.js
Opening an appearance category in the appearance menu then exiting using the Escape key instead of the Accept/Cancel buttons was not setting the character's FocusGroup to null. This meant that when clicking on the character later, it immediately opened the inventory screen showing clothes options in a 3x4 grid instead of starting the expected dialog.
> Appearance Esc Fix

- BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor.csv
- BondageClub/Screens/Room/Shop/Shop.js
- BondageClub/Screens/Room/Shop/Text_Shop.csv
This allows the player to sell items they own back to the shop for half of the purchase price (rounded up).
When selling, the dialog option for each item category will only appear when the player actually has an item in it to sell. Certain items will not be sellable if they can be obtained in the club for free. E.g. nylon ropes from the introduction room.
The dialog text for the item categories has been simplified so it makes sense for both purchases and sales.
The general page structure of the shopkeeper's dialog has been rearranged a bit for ease of navigation. Before, the first page was a list of the top-level item categories plus the "I'd like to ask you some questions." line linking to a second page with all the other questions/activities. Now the first page will instead cover all …
> Sell Items in the Shop

- BondageClub/Screens/Inventory/ItemHands/PaddedMittens/PaddedMittens.js
- BondageClub/Screens/Inventory/ItemHands/PawMittens/PawMittens.js
- BondageClub/Scripts/Validation.js
All items that were actually using the `Restrain` property have now been moved to use the extended item script. I've therefore removed handling of `Restrain` from the validation code, and have removed the property from the padded mittens and paw mittens, where it was not being used.
> Refactor: Removes handling of the unused Restrain property

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Screens/Character/Login/Login.js
- BondageClub/Screens/Room/Private/Private.js
- BondageClub/Scripts/Character.js
- BondageClub/Scripts/Server.js
- BondageClub/Scripts/Validation.js
This PR fixes errors that occur in the new appearance validation script with private room NPCs. Once I'd fixed the issue, it turned out that there was a minor issue with the definition for the `Nipples` asset group which means that NPCs are actually never populated with nipple assets, due to the group having `Default: false` set. I've accordingly fixed that issue, and added some additional logic into `PrivateLoadCharacter` to update the appearance of any existing private room NPCs whose appearance is invalid. I also added some JSDoc to `Server.js` that I intended to add in the original PR, but forgot about.
> Bugfix: Fixes issues with new validation script when run on private room NPCs

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Scripts/NPC.js
This moves the preferences-initialisation step that constructs the Zone, Activity and Fetish lists in ArousalSettings from `PreferenceInitPlayer` which is only run for players, into `PreferenceInit` which is run for both players and NPCs.
> NPC Missing Arousal Settings fix

- BondageClub/Scripts/Validation.js
I noticed that #2255 introduced an issue with validation where asset validation would not get properly run on appearance updates due to a refactoring error. This also fixes a bug with the validation of lockpick seeds for locks that define the `LockPickSeed` property.
> Bugfix: Validation typo fixes

- BondageClub/Screens/Room/MainHall/MainHall.js
Just a small fix so that the tooltip for the Cafe now renders above the icon for the Arcade in the main hall, rather than underneath it.
> Bugfix: Cafe hover text rendering underneath Arcade icon

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Tools/Node/AssetCheck_Types.js
Removes a duplicated `DefaultColor` property from `Female3DCG.js` that was probably missed when #2258 went in. Also adjusts the type of the `Bonus` property in the asset check script so that the script no longer fails, as noted by @jomshir98.
> Bugfix: Removes duplicated DefaultColor property

- BondageClub/Screens/Character/Login/Login.js
- BondageClub/Screens/Character/Login/Text_Login.csv
- BondageClub/Screens/Character/Relog/Text_Relog.csv
- BondageClub/Scripts/Server.js
Improvement for: [Server#78](https://github.com/Ben987/Bondage-Club-Server/pull/78)
Small change to display on which position the player is at the time the login was pressed. The position doesn't update and is meant mainly to notify players, that something is going on while they wait - that they are in queue.
> Feature: Display login queue position

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Character/Preference/ActivityDictionary.csv
This is something I've been asked about a few times by various people, and was a simple addition. This allows players to use the "Wiggle" activity on their nose and ears.
> Feature: Adds support for the Wiggle activity to ItemNose and ItemEars

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Even though this PR includes all the functions introduced in #2253, it does not enable them for usage yet. For this purpose, seperate pull requests will be opened. This is to make testing the individual functions easier as requested by @Ben987.
The same has been done with the related Server PR [#76](https://github.com/Ben987/Bondage-Club-Server/pull/76), which got split as described in [#79](https://github.com/Ben987/Bondage-Club-Server/pull/79).
The usage of each function can be enabled with it's respective Client and Server PR:
- **ChatRoomSyncCharacter** - Client: #2273 Server: [#80](https://github.com/Ben987/Bondage-Club-Server/pull/80)
- **ChatRoomSyncMemberJoin** - Client: #2274 Server: [#81](https://github.com/Ben987/Bondage-Club-Server/pull/81)
- **ChatRoomSyncMemberLeave** - …
> ChatRoomSync-Split: Replacement functions only

- BondageClub/Screens/MiniGame/GetUp/GetUp.js
May potentially fix an issue where the minigame return function is called, causing TextGet calls later on to fail.
> Prevents MiniGameReturnFunction from being called until drawing is done

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Current behavior: Being on Light sensory deprivation settings causes you to be able to see the whole chat room. There is a bug where you can't see anyone but those wearing VR headsets even if you are on Light, which goes against the purpose of Light mode.
Fix: Make it so that all players get drawn regardless of VR status when player is in Light sensory deprivation mode
> Virtual reality fix with light sensory deprivation

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Drawing.js
Changes items with custom backgrounds (for now just the VR headset) to still replace the background in Light sensory deprivation mode. This also allows items that do not have BlindHeavy to use a custom background.
The current behavior is to override DarkFactor only when DarkFactor is 0 (pure black). In the future this can be changed once there is some clarity in how blindfolds should interact with custom backgrounds from something other than a blindfold (which do not exist yet)
> Custom backgrounds updates

- BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
- BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
- BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
- BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonItem.js
- BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
The Kinky Dungeon was using `Minigame` instead of `MiniGame` in asset paths, resulting in 404 errors when trying to load assets.
> Bugfix: Fixes casing for asset paths in the Kinky Dungeon minigame

- BondageClub/Scripts/Validation.js
There was an error in `Validation.js` where item colors were being compared incorrectly, resulting in rollbacks for valid appearance updates (see screenshot), especially when cosplay/body items were multi-colored. This uses a more complete comparison for item colors which should prevent these false alarms.
> Bugfix: Fixes incorrect appearance update rollbacks

- BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag.js/CustomCollarTag.js
When the text of a Custom Collar Tag or Electronic Tag was checked for invalid characters, the lastIndex property was updated to the end of the string since the global flag was unnecessarily included. This made the next test fail and revert the text to the default "Tag" even though the custom text was unchanged and still valid.
> Custom Tag Regex Fix

- BondageClub/Scripts/Validation.js
Timer locks were dropping the "Time left" property and displaying null/NaN due to an error in the lock validation.
I also changed the max-time-exceeded correction to apply the lock's max time instead of its default time, since normal non-consoled time additions managed to occasionally exceed this max time.
> Lock Timer Validation Fix

- BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
The kidnap game's function to process a selected upper move wasn't updated to account for the new move list. The only move that was actually affected was UndoCloth (Dress Back Up) which was doing nothing when selected.
> Kidnap Dress Up Fix

- BondageClub/Scripts/Server.js
If a player was playing the Kinky Dungeon minigame in a chat room and got kicked by an admin, on finishing their game they would still be in the room from their viewpoint but couldn't interact with anything. 
They will now be interrupted and immediately exit to the chat search screen as normal.
> Kicked during Kinky Dungeon fix

- BondageClub/Screens/Character/Login/Login.js
- BondageClub/Screens/Room/Private/Private.js
- BondageClub/Scripts/Character.js
- BondageClub/Scripts/Server.js
This was something I'd intended to implement in the original validation change, but it's come to my attention that there was an issue with the way it was implemented. For the most part, this issue should only affect those using console, but there may be some edge cases where it causes unexpected behaviour in the standard game.
Currently, when an invalid appearance bundle is received, the character's full appearance is rolled back, rather than just the items that were invalid. Additionally, I'd intended for partial rollbacks to work on a per-item basis - for example, if an item is added with a lock that is blocked on the player in a single update, I'd intended to only roll back the lock part of that update, and permit the item to be equipped without a lock, but this isn't what happens …
> Bugfix: Properly enables partial appearance rollbacks

- BondageClub/Scripts/Character.js
This makes a few refinements to clumsiness calculation for the combination lock. In particular, it now ensures that hand items have the `Block` effect, so that the Futuristic Mittens in glove mode don't trigger clumsiness.
> Bugfix: Improves character clumsiness calculation

- BondageClub/Screens/Character/Player/Dialog_Player.csv
- BondageClub/Screens/Inventory/ItemDevices/PetBed/PetBed.js
The pet bed would previously not display chatroom messages when changing type, despite messages existing in `Dialog_Player.csv`. This was due to a typo in the function name. I also made some slight edits to the chat messages themselves to ensure that the tags worked correctly, and to make the wording flow a little better.
> Bugfix: Chatroom messages for the pet bed

- BondageClub/Scripts/Validation.js
This includes a handful of fixes and refinements to the validation code:
* Fixes an issue where property sanitization would sometimes short-circuit out of the method before fully sanitizing all properties
* Fixes a long-standing issue that's been around since #1387 was merged, where players' expressions wouldn't reset after a temporary change (e.g. item-triggered expression changes)
* Sanitization now validates the `Expression` property of items according to the asset/group's `AllowExpression` array
* Sanitization now allows effects and block entries that are in the asset's `Effect` and `Block` arrays as well as their `AllowEffect` and `AllowBlock` arrays
* Adds a few more warning log statements to make it clear what is causing appearance updates to be invalid
> Bugfix: Validation refinements

- BondageClub/Screens/Inventory/ItemPelvis/SciFiPleasurePanties/SciFiPleasurePanties.js
Interacting with the Sci-Fi Pleasure Panties when they're locked with an unopenable lock shows the usual futuristic item's "Enter Password" screen. However clicking 'Log in' and exiting this screen was not removing the input field.
> Pleasure Panties Password Fail fix

- BondageClub/Screens/Character/FriendList/FriendList.js
In #2299 I fixed friendlist sorting, so it works as it was originally intended. This change removes the sort altogether.
Players however seem to prefer old way the friendlist was sorted (in order it was created on server - lovers&submissives first, everyone else in order they were added into friendlist)
This is temporary fix, until more stable sorting using actual friend types will be done.
> Beta-fix: Remove Friendlist sorting

- BondageClub/Scripts/Character.js
This is something that gets flagged by the new validation. If an expression is set with a `RemoveTimer`, but the player then manually changes their expression back to default, the remove timer isn't removed, which causes validation errors.
This PR modifies the `CharacterSetFacialExpression` function so that whenever an expression is changed, any existing `RemoveTimer` is deleted before changing the expression (and if a new `RemoveTimer` should be set, that still happens). This should prevent these validation warnings, and also fix a bug where manually setting an expression whilst a `RemoveTimer` is in effect causes the new expression to reset when the `RemoveTimer` expires.
> Bugfix: Ensures expression remove timers get removed when the expression is

- BondageClub/Scripts/Validation.js
This fixes an issue where extended items whose `null` type has properties would get rolled back when the `null` type is selected. This happens on a handful of items (e.g. the metal cuffs), and as far as I can tell has happened since before the recent validation changes, but the properties would get silently deleted previously, meaning that these items probably did not work entirely as intended.
Eventually, I want to replace this particular block with slightly more rigid validation, but for now this doesn't really open the game up to any issues that weren't already available before (e.g. the ability to hide arbitrary items).
> Bugfix: Allows the null type to have properties

- BondageClub/Scripts/Inventory.js
- BondageClub/Scripts/Timer.js
- BondageClub/Scripts/Validation.js
This fixes a couple of things:
* There was an error in lock modification validation where the `RemoveItem` and `ShowTimer` lock properties were being reverted even if the player had permission to modify the lock. This resulted in some of the timer lock buttons not working properly
* When locks were removed via `InventoryUnlock` and `TimerInventoryRemove`, the `EnableRandomInput`, `RemoveItem` and `ShowTimer` properties weren't being removed, which resulted in the validation code flagging the update as invalid. These two functions now make calls to `ValidationDeleteLock`, to ensure that all lock properties are being properly deleted.
> Bugfix: Lock validation fixes

- BondageClub/Scripts/Validation.js
MemberNumberListKeys (used for High Security Padlocks) was listed as a basic lock property meaning it couldn't be changed after being initially set, which should actually be possible.
> Lock Key-List change fix

- BondageClub/Assets/Female3DCG/Female3DCG.js
Altered access to the nose when a blindfold is on, so it makes more sense visually.
This will allow the changing of items on the nose when most blindfolds are on. This does not change the blindfolds that visually cover the nose.
> Nose access change for blindfolds

- BondageClub/Scripts/Validation.js
Fixes an issue which allowed players to incorrectly remove owner/lover locks from others. I'm not quite sure how this slipped through the net when I was testing previously, as I'm pretty sure I had a test case for this situation, but apparently it did.
> Bugfix: Fixes an owner/lover lock validation issue

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Notification.js
- In the chat messages notification settings players can now separately select Normal Messages, Whispers and Items/Activities to be included or excluded.
- If a popup notification is expected but isn't available for some reason, the "(1) in title" notification will now occur in its place. This covers situations like a user switching from a device that supports popups to one that doesn't.
- If the user was prompted by their browser to allow or block notifications, the particular popup that triggered this request would not appear. Now it will appear after the permissions request is completed (if the user selected Allow).
- Added steps to the popup's onclick to ensure that it refocuses on the game on all OS's.
> Notifications Improvements

- BondageClub/Scripts/Server.js
This PR enables the use of function `ChatRoomSyncReorderPlayers` added by PR #2272 on which it depends. It requires Server PR [#86](https://github.com/Ben987/Bondage-Club-Server/pull/86) to work.
> ChatRoomSync-Split: Enable ChatRoomSyncReorderPlayers

- BondageClub/Screens/Character/FriendList/FriendList.js
- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
- BondageClub/Scripts/Character.js
- BondageClub/Scripts/Speech.js
Adds a new immersion option, allowing chat room names and descriptions (plus the names of friends in them) to be garbled.
This required a refactoring of SpeechGarble. I have split SpeechGarble into two functions, one containing the base functionality based on a level of GagEffect, and one that assigns GagEffect based on either deafness (if the character is another player) or gagged level of the player.
> Immersion: Chat room names and descriptions are garbled while blind

- BondageClub/Screens/Inventory/ItemHood/OldGasMask/OldGasMask.js
- BondageClub/Screens/Inventory/ItemMisc/HighSecurityPadlock/HighSecurityPadlock.js
- BondageClub/Screens/Inventory/ItemMisc/PasswordPadlock/PasswordPadlock.js
- BondageClub/Screens/Inventory/ItemMisc/SafewordPadlock/SafewordPadlock.js
- BondageClub/Screens/Inventory/ItemMisc/TimerPasswordPadlock/TimerPasswordPadlock.js
- BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js
- BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTag/CollarNameTag.js
- BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTagLivestock/CollarNameTagLivestock.js
- BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTagLover/CollarNameTagLover.js
- BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTagOval/CollarNameTagOval.js
- BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTagPet/CollarNameTagPet.js
- BondageClub/Screens/Inventory/ItemNeckAccessories/CollarShockUnit/CollarShockUnit.js
- BondageClub/Screens/Inventory/ItemPelvis/SciFiPleasurePanties/SciFiPleasurePanties.js
To keep this cleanup small, this part only focuses on files in `Screens/Inventory/` and only on files not handled before
> Cleanup: Scripts formatting (Part 9 - `Screens/Inventory/*` - rest)

- BondageClub/Screens/Inventory/ItemArms/FuturisticCuffs/FuturisticCuffs.js
- BondageClub/Screens/Inventory/ItemBoots/FuturisticHeels/FuturisticHeels.js
- BondageClub/Screens/Inventory/ItemBreast/FuturisticBra/FuturisticBra.js
- BondageClub/Screens/Inventory/ItemBreast/FuturisticBra2/FuturisticBra2.js
- BondageClub/Screens/Inventory/ItemHands/FuturisticMittens/FuturisticMittens.js
- BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessBallGag/FuturisticHarnessBallGag.js
- BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
- BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
- BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
- BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt2/FuturisticChastityBelt2.js
- BondageClub/Screens/Inventory/ItemTorso/FuturisticHarness/FuturisticHarness.js
- BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
To keep this cleanup small, this part only focuses on files in `Screens/Inventory/` and only on futuristic items.
> Cleanup: Scripts formatting (Part 8 - `Screens/Inventory/*` - Futuristic items)

- BondageClub/Scripts/Dialog.js
To keep this cleanup small, this part only focuses on file `Scripts/Dialog.js`
> Cleanup: Scripts formatting (Part 4 - `Scripts/Dialog.js`)

- BondageClub/Scripts/Character.js
- Formats functions inside `CharacterReset` to be more readable without changing them
To keep this cleanup small, this part only focuses on file `Scripts/Character.js`
> Cleanup: Scripts formatting (Part 3 - `Scripts/Character.js`)

- BondageClub/Scripts/Animation.js
To keep this cleanup small, this part only focuses on file `Scripts/Animation.js`
> Cleanup: Scripts formatting (Part 2 - `Scripts/Animation.js`)

- BondageClub/Scripts/Activity.js
- BondageClub/Scripts/AfkTimer.js
- BondageClub/Scripts/Asset.js
- BondageClub/Scripts/Audio.js
- BondageClub/Scripts/ColorPicker.js
- BondageClub/Scripts/Common.js
- BondageClub/Scripts/CommonDraw.js
- BondageClub/Scripts/Drawing.js
- BondageClub/Scripts/Drawing3D.js
- BondageClub/Scripts/Element.js
- BondageClub/Scripts/ExtendedItem.js
- BondageClub/Scripts/GLDraw.js
- BondageClub/Scripts/GameLog.js
- BondageClub/Scripts/Inventory.js
- BondageClub/Scripts/MiniGame.js
- BondageClub/Scripts/NPC.js
- BondageClub/Scripts/Notification.js
- BondageClub/Scripts/Reputation.js
- BondageClub/Scripts/Server.js
- BondageClub/Scripts/Skill.js
- BondageClub/Scripts/Speech.js
- BondageClub/Scripts/Timer.js
- BondageClub/Scripts/Translation.js
- BondageClub/Scripts/Validation.js
- BondageClub/Scripts/VibratorMode.js
- Changes missed `var` to `let` in `SpeechGarbleByGagLevel`
To keep this cleanup small, this part only focuses on files with less than 20 edits each.
> Cleanup: Scripts formatting (Part 1 - little edits)

- BondageClub/Screens/Character/Preference/Preference.js
When in a preferences subscreen, hitting the Esc key exited the preferences menus entirely whereas it's much more intuitive to jump back one screen to the preferences home page.
Also much of the subscreen exit logic was contained in Click functions, which meant that exiting via the Esc key found no Exit function and therefore didn't perform the proper cleanup. These steps have now all been extracted into `PreferenceSubscreen*Exit()` functions so they're always run.
Also also I refactored all MouseX and MouseY `if` statements in the file into MouseIns, and cleaned up indents/whitespaces/semicolons.
> Preference Subscreen Escaping

- BondageClub/CSS/Styles.css
- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Sometimes players complain that the text from binding someone takes over the whole chat log. This setting allows users to shrink anything that isn't chat or an emote in order to focus on RP if they wish to do so.
> Chat Setting: Shrink non-dialogue

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Figured there was no reason to block it out.
It still does not affect Light because in Light the player cannot enter total sensory deprivation due to the IsInSenseDep function.
> "Hide others' Messages" applies to Hide Names sensory deprivation option

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Assets/Female3DCG/Female3DCGExtended.js
- BondageClub/Scripts/Common.js
- BondageClub/Scripts/TypedItem.js
This modifies the typed item script slightly to automatically generate an asset's `AllowBlock` and `AllowEffect` entries based on its type configuration (very similar to what was done with modular items in #2333). This should mean that asset creators no longer need to worry about adding `AllowEffect` and `AllowBlock` to their items if using the archetype framework.
I've also tidied up the configuration for the ball and wiffle gags, as their configuration contained some unneeded `Effect` entries (which were just duplicating the item's base `Effect`).
This also modifies the chatroom publish functionality of the typed item script slightly to pass the character reference into `Config.Dialog.ChatPrefix` functions when they are called, which should enable conversion of the ceiling shackles as …
> Feature: Auto-generates `AllowEffect` and `AllowBlock` on typed items

- BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
- BondageClub/Scripts/Drawing.js
#2163 modified `Drawing.js` so that `DarkFactor` was no longer applied inside minigames. This resulted in a few visual issues in some minigames, for example the Asylum Therapy minigame, where the instruction text is shown against an almost-white background, making it almost impossible to read (see image below). This removes the minigame check, which fixes the issue for the Asylum Therapy and any other minigames that were trying to set `DarkFactor` to something other than 1.
I assume that the minigame check was added to support the Kinky Dungeon minigame (although that hadn't yet been fully introduced at the time of the above PR). That said, I've checked this change inside the Kinky Dungeon minigame, and have not seen any issues as a result. @Ada18980 - do you foresee this causing any …
> Bugfix: Re-enables `DarkFactor` inside minigames

- BondageClub/Scripts/Asset.js
- BondageClub/Scripts/ModularItem.js
- BondageClub/Scripts/Typedef.d.ts
- BondageClub/Tools/Node/AssetCheck_Types.js
This PR does a couple of things:
* Adds support to modular items for the `Effect` property (which wasn't supported until now, since no items needed it). This supports a request from @Ada18980 to extend the Kigurumi Mask's functionality
* Adds an `Archetype` property to assets, which is automatically populated for items which have an extended archetype - this is primarily a convenience property, but may be useful to scripters, or to support Ada's Kinky Dungeon functionality
* Fixes an issue with the modular item script where module changes were unintentionally getting assigned directly to the underlying asset's `Block`, `Hide` and `HideItem` arrays
> Feature: Modular item `Effect` support

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- BondageClub/Screens/Inventory/ItemMisc/HighSecurityPadlock/HighSecurityPadlock.js
- BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
- BondageClub/Scripts/Drawing.js
A few related changes:
- `DrawCheckbox`, `DrawCheckboxColor` and `DrawCheckboxDisabled` have been merged into one function. In addition to simplifying them, this fixes an error on the Restriction screen where one checkbox disappeared for non-Roleplay difficulties.
- The Immersion preference screen's 'Lock this screen' setting and 'maxed out under Extreme' message have been moved to the top.
- In Extreme difficulty, the Immersion preference controls are now all disabled instead of hidden.
- Other preference screen checkboxes that were hidden are now disabled instead (two in Immersion, one in Item Visibility).
- Repositioned the Online settings to be more vertically centered.
- A "Page x/y" button has been created to support multiple pages in preference subscreens. No screens use it at the …
> Preferences & Checkboxes tweaks

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Scripts/CommonDraw.js
- BondageClub/Scripts/Typedef.d.ts
This PR makes some improvements to the `HideForPose` property when used in conjunction with other asset properties. It moves the handling of `HideForPose` into the build stage of drawing, when sorting a character's appearance layers. 
* This means that it now works in conjunction with alpha masks (i.e. alpha masks won't be used if an item is hidden via `HideForPose`)
* This also fixes a bug where the pet bowl's dynamic text would still get drawn despite the bowl being hidden whilst the character was suspended
* Also includes a few improvements to the type definitions for asset layers and characters
> Bugfix/Improvement: Better compatibility for `HideForPose`

- BondageClub/Assets/Female3DCG/Female3DCG.js
> ⚠️ Depends on, _but does not include_ #2421 & #2422. Merging without these two PRs will result in bugs.
This removes the `Hide` entry for the `Spread` pose, meaning that by default items from the `ItemBoots` group will now be shown in the pose by default. Along with the changes in #2421 & #2422, this should enable the `Spread` pose for the Futuristic Heels, whilst not causing incompatibilities with the alpha masks of other boots.
> Improvement: `ItemBoots` is now shown in the `Spread` pose by default

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Since the current behavior is that if you are leashed, you keep getting dragged to whatever room the leashing player takes you to, this prevents the player from manually breaking the leash connection except by removing the leash. 
Tested to make sure leashing itself wasn't broken, and also verified the functionality and that it can be escaped by no longer being leashable.
> Prevent players that are leashed from leaving

- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
This should prevent players from being stuck in ChatSearch when the room they are forced to rejoin is full but they ignore full rooms.
> Prevents softlock from return to chat room when hiding full rooms

- BondageClub/Screens/Character/Appearance/Appearance.js
This fixes an issue introduced by the change to the `HideForPose` property in #2422 where items using the `HideAs` property would result in an error being thrown as the `ItemHidden` group no longer exists.
1. Equip an armbinder
2. Select one of the strap variations from the extended menu
3. Note that the menu does not exit properly, and an error is thrown in the console
> Bugfix: `HideForPose`/`HideAs` compatibility issue

- BondageClub/Screens/Room/Infiltration/Dialog_NPC_Infiltration_Supervisor.csv
- BondageClub/Screens/Room/Pandora/Pandora.js
A small change so that when the N/S/E/W arrow buttons are darkened and unavailable, they are set to disabled so that they aren't highlighted cyan when the cursor hovers over them.
The code snippet that determines this was wrapped up in a function just to make it a little more readable.
This also has a tweak to one of the NPC lines.
> Pandora Button Hover

- BondageClub/Screens/Inventory/ItemMisc/CombinationPadlock/CombinationPadlock.js
I'm not entirely sure on what caused the original problem (possibly a badly consoled-on combination lock), but if a combination padlocked item has no `LockMemberNumber` property, then it will cause an error in the combination padlock's extended item menu. This PR adds better null-safety to the extended item menu to catch this.
> Bugfix: Better null safety on combination padlock extended menu

- BondageClub/Scripts/Notification.js
A fix to ensure the screen doesn't freeze if a popup doesn't exist when the reset occurs.
> Notification Popup fix

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
This makes it so that if the player receives a message that her leasher disconnected, the leash will break and the player will be able to leave the room again. This is to prevent cases where the player is stuck for no discernable reason.
> If a leashing player disconnects, the leash is broken

- BondageClub/Scripts/GLDraw.js
This fixes an issue with alpha blending where source and destination alpha channels were not being interpolated properly when drawing an image with semi-transparent pixels onto a canvas. This could result in visual artifacts being displayed on some setups (see before/after comparison for this change below).
| Before fix | After Fix |
| --- | --- |
| ![alpha-before](https://user-images.githubusercontent.com/62729616/117960897-67144980-b315-11eb-96f2-74da2f33b823.png) | ![alpha-after](https://user-images.githubusercontent.com/62729616/117960916-6bd8fd80-b315-11eb-825a-5585a02e9709.png) |
> Bugfix: WebGL alpha blending

- BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
- BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
- BondageClub/Screens/Room/Arcade/Arcade.js
Dungeoneer is supposed to give the max level youve been to, but it instead just increases each level currently. This update fixes that and also adds a bit of cheat prevention (if it's higher than the max level it resets). This is to reset people's scores that are currently at 100 without theoretically penalizing anyone in the future because it is impossible to go above a certain level.
> Fixed Dungeoneer reputation

- BondageClub/Assets/Female3DCG/Female3DCGExtended.js
As part of #2388, I removed the `Property.Effect` arrays from a few gags where it was duplicating the asset's base `Effect` array. However, this causes the gag effects to stop working when a gag is locked, as locking it adds a `Property.Effect` array to the item which contains no gag effects. This reinstates the removed effects, and also adds effect arrays to the cupholder gag, which apparently has always suffered from this problem without anyone noticing.
For one of the modified gags (ball gag, wiffle gag, cupholder gag):
1. Equip the gag - note that the gag effect is properly applied
2. Optionally, change the gag's type
3. Lock the gag
4. Note that the gag no longer applies a gag effect in chat
> Bugfix: Locks breaking gag effects

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Speech.js
-Unaffected by deafness
-Gagged users have a hard time controlling it
Tested 3 cases: User saying Increase while gagged, someone else saying Increase, and someone else saying Increase while user is deafened.
> Fixes futuristic vibrator to work as it did before

- BondageClub/Screens/Character/Wardrobe/Wardrobe.js
This fixes an issue with the appearance screen that's probably been around for a while where the character's pose would not be refreshed after loading a wardrobe outfit. This would result in visual issues with clothing items that set poses (e.g. the pencil skirt) as the player's pose inside the wardrobe would not get updated. In addition, if the player was inside their private room, their pose would remain broken on leaving the appearance screen.
This fixes a few issues:
1. Enter the appearance screen from anywhere (player pose should be the default pose)
2. Load an outfit which includes the pencil skirt
3. Note that the player's pose does not update
And in the player's private room:
1. Enter the wardrobe screen
2. Note that an outfit which includes the pencil skirt is not rendered …
> Bugfix: Ensures pose refresh on loading wardrobe outfit

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
There was a rare bug where if two players opened an extended item's options screen at the same time, then one of them selected a new option, it was incorrectly changed to the default option. The other player did not receive this update and was desynced. This only seemed to happen for items where the default/first option was not the null type (i.e. arm ropes, chains and cuffs).
> Revert to Default Bugfix

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Hotfix based on a beta feature that was added. The ChatRoomCanBeLeashed function was being used inappropriately, I instead modified a function to bypass the lock check if there is no membernumber (signaling that the check is a general one).
> Fixes issue where owner/lover lock on a leash makes it impossible to use

- BondageClub/Screens/Inventory/ItemMisc/SafewordPadlock/SafewordPadlock.js
To prevent passwords that are too big to see the last letters of, inviting trolls.
Suggesting hotfix due to small size of change and troll potential.
> Increases size of text field for safeword padlock

- BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
- BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
2nd attempt at fixing targeting for mobile players.
Potential hotfix candidate. I see this as low-risk since the relevant function (KinkyDungeoSetMoveDirection) normally got called every draw frame.
> Kinky Dungeon Targeting Fix

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Scripts/Inventory.js
PR #1475 effectively removed the use for the `AccessVulvaSuitZip` prerequisite on items as it added `Expose` entries to all `SuitLower` items. However, the prerequisite itself was never removed, so when the stockings were copied to the `SuitLower` group in #2009, this meant that they were the only items in the group which block vulva access, which didn't really make sense (with the exception of the pantyhose item). Rather than adding `Expose` entries to the stockings, I've entirely removed the `AccessVulvaSuitZip` prerequisite and all `Expose` entries on items in the `SuitLower` group, as the prerequisite wasn't actually being used, so it didn't make much sense to keep around.
This PR therefore fixes an issue where stockings in the `SuitLower` group block vulva access, and doesn't change …
> Bugfix/Refactor: Removes `AccessVulvaSuitZip` prerequisite & `Expose` on `SuitLower`

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
This PR mitigates a longstanding issue with the handling of `ChatRoomCharacterItemUpdate` messages on the server. At the moment, whereas a `ChatRoomCharacterUpdate` call persists the character's new appearance to the DB, `ChatRoomCharacterItemUpdate` calls don't, which results in items and locks sometimes disappearing after a player relogs if no `CharacterRefresh` or `ChatRoomCharacterUpdate` calls are made before they log out.
This modifies the `ChatRoomSyncItem` function so that it syncs its `CharacterRefresh` call if the update is not invalid, which means that a player's appearance will be persisted to the DB on receiving a valid `ChatRoomSyncItem` message. While this issue isn't directly caused by this release, it might be a nice one to hotfix as it's relatively small and impacts …
> Bugfix: Item update rollback mitigation

- BondageClub/Scripts/Timer.js
The fix in #2341 meant that more properties were being removed from locked items on unlock than previously, including the `RemoveItem` property, which was later used in `Timer.js` to detect whether the locked item should be removed as well in the case of timer locks with a "Remove item when the lock timer runs out" checkbox, meaning that these locks would no longer remove the item upon expiry. This fixes that so that the redundant properties still get removed, but so does the item if the `RemoveItem` property was set.
1. Equip a lockable item and lock it with a Mistress, Lover or Owner Padlock
2. Inspect the lock and check the "Remove item when the lock timer runs out" checkbox
3. Wait for the lock timer to run out
4. Note that the lock gets removed, but the item does not
> Bugfix: Ensures items get removed with timer locks

- BondageClub/Scripts/Character.js
- BondageClub/Scripts/ExtendedItem.js
When a new extended item option could be blocked by other the current option, e.g. hemp rope on arms, a SelfBlockCheck setting temporarily removed then readded the item for validation. These changes are no longer pushed to the server unnecessarily, which also had the unwanted side-effect of resetting the memoization and rerunning the prerequisite checks constantly.
The steps to refresh character dialog during a character refresh have been moved into their own function and can now be skipped when not wanted.
> Extended Self-Block Validation Fix

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Scripts/Validation.js
It is currently possible to use console to set the `SetPose` array on an item's `Property` to a value other than an array, which can cause another player's game to crash when they click on the character with the offending property (or if the property is set on them). This adds a sanitization check in `Validation.js` which ensures that `SetPose` entries on an item's property are valid string arrays, whose entries are all valid pose names.
1. Equip an extended item on a character
2. Using console, set `Property = {SetPose: "Broken"}` on the item
3. Note that the game will crash for the player on whom the property was set, and for anyone else, clicking on that character will crash their game, with the following stack trace:
```
Character.js:720 Uncaught TypeError: SetPose.find is not a …
```
> Bugfix: `SetPose` property validation

- BondageClub/Screens/Inventory/ItemMisc/PasswordPadlock/PasswordPadlock.js
- BondageClub/Screens/Inventory/ItemMisc/SafewordPadlock/SafewordPadlock.js
- BondageClub/Screens/Inventory/ItemMisc/TimerPasswordPadlock/TimerPasswordPadlock.js
- BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Common.js
- BondageClub/Scripts/Drawing.js
- BondageClub/Scripts/Inventory.js
This was originally just going to be a slight UI fix to the password padlocks (password, safeword & timer password), but whilst I was in there, I noticed that there was a lot of code duplication and general inefficiencies in the code for the password padlocks, and ended up refactoring them. This PR does a bunch of things, but should not affect the behaviour of the padlocks themselves from a player perspective:
* Fixes an issue where the password inputs weren't wide enough to accommodate all possible passwords (passwords containing several wide letters like 'm' and 'w' could result in a letter or two getting cut off, which is particularly bothersome with the safeword padlock, as it prevents most players from being able to unlock it). This particular issue has now been fixed for the …
> Refactor/Bugfix: Password lock refactors & UI improvements

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Element.js
When resizing the window, this prevents your location in the TextAreaChatLog, in chat rooms, from changing.  It keeps you at the exact end of the chat log if you were there at the beginning of the resize event, or otherwise keeps you at about the same position in the chat log.  Triggered by a resize event listener, which is added and removed when the chat log is added and removed.
> Preserve scroll location in TextAreaChatLog on window resize

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Common.js
- BondageClub/Scripts/Server.js
- BondageClub/Scripts/Typedef.d.ts
Implements clientside `ChatRoomGetAllowItem` from server to allow for instantaneous resolving of access to target character, removing delay after clicking.
Original behaviour is still preserved, including aking server and if there is mismatch, server has final say.
> Improvement: Clientside GetAllowItem

- BondageClub/Screens/Character/ItemColor/ItemColor.js
- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- BondageClub/Screens/Inventory/HairAccessory1/Halo/Halo.js
- BondageClub/Screens/Inventory/ItemArms/HempRope/HempRopeSuspensionHogtied.js
- BondageClub/Screens/Inventory/ItemArms/TransportJacket/TransportJacket.js
- BondageClub/Screens/Inventory/ItemDevices/Locker/Locker.js
- BondageClub/Screens/Inventory/ItemDevices/WoodenBox/WoodenBox.js
- BondageClub/Scripts/Common.js
- BondageClub/Scripts/Typedef.d.ts
At the moment most functions that update the character appearance repeatedly are limited by debouncing (delaying updates until a set time has passed without change) with a wait interval of 100 ms.
This feature creates a new "Animation Quality" preference in the Graphics settings page to let users indirectly decide this limit themselves. The options are Low/Medium/High/Max corresponding to wait intervals of 200/100/50/0 milliseconds respectively. By default the setting will be Medium = 100 which is the current behaviour for most cases.
For Low and Medium these character refreshes will still be debounced, while for High and Max they'll be throttled instead (delaying updates until a set time has passed) which will provide a faster smoother response to appearance setting changes, provided the …
> Animation Quality Preference

- BondageClub/Assets/Female3DCG/Female3DCG.js
First PR so hopefully didn't break anything.  This should be a nearly invisible change and would allow the blackout lenses to work in a more logical fashion with glasses and masks. Resubmitting after adding a priority change after discussion with Nina and Ace__ on Discord.
> Reconfiguring blackout lenses to not hide mask or glasses

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
#2104 deferred the assignment of the main hall maid NPC. However, when calling the maids from the chatroom, the `DialogCallMaids` function would call `MainHallPunishFromChatroom` before setting the screen to the main hall. This could result in the game crashing under certain circumstances with the following stack trace (because `MainHallPunishFromChatroom` expects the main hall maid to have been created already). This fix modifies `DialogCallMaids` to ensure that the screen is set to the main hall before calling `MainHallPunishFromChatroom` in order to prevent this issue.
```
MainHall.js:498 Uncaught TypeError: Cannot set property 'Stage' of null
at MainHallPunishFromChatroom (MainHall.js:498)
at DialogCallMaids (ChatRoom.js:2564)
at CommonDynamicFunctionParams (Common.js:323)
at …
```
> Bugfix: Crash after calling the maids from a chatroom

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Implements a /bot command which does nothing except send a hidden message to all other players. This message will get ignored on the default client, but a modded client might be able to interpret the bot command. This specifically enables bots that work even if the player can't whisper due to immersion settings.
> Bot Command

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Scripts/Asset.js
- BondageClub/Scripts/Typedef.d.ts
- BondageClub/Tools/Node/AssetCheck_Types.js
This is the PoC of a new asset feature: The ability to hide items based on certain attributes.
Within this PR all skirts in the ClothLower group got the attribute "Skirt" now and the regular strait jacket and the leather strait jacket now hide all clothes with that attribute.
This way, there is no need to check all `HideItem` entries on all assets, if a new item is introduced, it just have to have the correct attribute and will be hidden automatically, without changes to other assets.
The main changes happened in the `Asset.js` and `Appearance.js`. 
In `Asset.js` the two new attributes `Attribute` and `HideItemAttribute` are introduced on asset level.
In `Appearance.js` a new check as added to `CharacterAppearanceVisible` where all items are hidden, if one of their attributes match with …
> Feature: Hide item based on attribute

- BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMultiplayer.js
- BondageClub/Scripts/Dialog.js
Fixes 2 bugs:
-Played as the wrong character when playing Kinky dungeon after spectating someone else
-Crash or desync when there are multiple players playing kinky dungeon in a room and you are spectating one of them
> Kinky Dungeon Spectator Fix

- BondageClub/Scripts/Dialog.js
Probably not strictly a beta fix, but this fixes an error that can occur when inspecting items using the `AllowLockType` property (currently only the Bondage Bench).
1. Player A equips a Bondage Bench on player B and immediately exits the extended menu
2. Player B clicks on themselves and selects the `ItemDevices` slot
3. The following error is thrown:
```
Dialog.js:733 Uncaught TypeError: Cannot read property 'Type' of undefined
at DialogMenuButtonBuild (Dialog.js:733)
at DialogInventoryBuild (Dialog.js:846)
at DialogClick (Dialog.js:1300)
at CommonClick (Common.js:258)
at Click ((index):385)
at HTMLCanvasElement.onclick ((index):467)
```
> Bugfix: Error thrown when inspecting the Bondage Bench

- BondageClub/index.html
The script reference for the web arms item was accidentally removed in #2542, which means that the extended menu for the web no longer works. This PR reinstates the script.
> Bugfix: Reinstates accidentally removed extended script for web

- BondageClub/Screens/Character/Appearance/Appearance.js
As part of #2548, some of the item-hiding logic was refactored to try to merge handling of `item.Property.Hide` and `item.Property.HideItem`. However, this would cause the `else if` block handling `item.Asset.HideItem` to be short-circuited incorrectly. This PR reverts that change, but maintains the new `HideItemAttribute` handling.
1. Equip a pair of Futuristic Earphones and exit the extended menu
2. Equip a gas mask (`OldGasMask`) on top
3. Note that the Futuristic Earphones are still visible, despite being listed in the gas mask's `HideItem` array
> Bugfix: Prevents `HideItem` declarations from being short-circuited

- BondageClub/Assets/Female3DCG/Female3DCGExtended.js
#2520 accidentally deleted the extended item configuration for the sturdy leather belts, presumably as a result of a merge conflict, meaning that the extended menu for the belts no longer works. This reinstates the missing configuration.
> Bugfix: Reinstates accidentally deleted sturdy leather belt configuration

- BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
There is a blacklist of words that will always get the player shocked even if the player does an emote. For example, writing "/me shouts into her gag" will still shock the player even if they aren't sending a normal chat message. This just adds a few extra keywords to catch clever subs.
> Adds a few keywords to the auto shock blacklist

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Inventory.js
This fixes an issue where single item updates could cause an item's difficulty to increase if the item's current difficulty is sent along with each update. I've also added some clarification to some of the JSDoc documentation regarding difficulty when adding items. Not strictly a beta fix, but would be good to include in this release.
1. Player A equips an extended item (with types) on player B
2. Player A leaves the room and re-enters (this ensures the difficulty value is synced properly between players, as it can go out of sync - this PR also fixes that)
3. Player A changes the type of the item on player B
4. Note that the difficulty of the item has increased by the base difficulty of the asset
5. Steps 2-4 can be repeated to increase the difficulty indefinitely
> Bugfix: Prevents difficulty from increasing when sending single item updates

- BondageClub/Scripts/ExtendedItem.js
On the Extreme difficulty, the button to switch to Permissions mode for extended items was accessible, allowing specific options to be blocked. These settings were at least reset on logging in again but could still be changed temporarily. Now the button will be hidden.
> Extended Item Type Permissions on Extreme Difficulty

- BondageClub/Assets/Female3DCG/Female3DCGExtended.js
Just adds the `CannotChangeWhenLocked` property to the dental gag.
> Fix: Dental gag cannot be changed when locked

- BondageClub/Screens/Character/Player/Dialog_Player.csv
- BondageClub/Screens/Character/Player/Dialog_Player_DE.txt
- BondageClub/Screens/Character/Player/Dialog_Player_RU.txt
- BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
- BondageClub/Screens/Online/ChatRoom/Dialog_Online_DE.txt
- BondageClub/Screens/Online/ChatRoom/Dialog_Online_RU.txt
- BondageClub/Screens/Room/AsylumEntrance/Dialog_NPC_AsylumEntrance_Nurse.csv
- BondageClub/Screens/Room/AsylumEntrance/Dialog_NPC_AsylumEntrance_Nurse_DE.txt
- BondageClub/Screens/Room/AsylumEntrance/Dialog_NPC_AsylumEntrance_Nurse_RU.txt
Fixes a couple of typos reported in the Discord:
* Changes "expresso" to "espresso" in drink-serving dialogues (should also fix some missing translations)
* Adds a missing "need" to the greeting dialogue for the Asylum entrance nurse
> Bugfix: Typo fixes

- BondageClub/Assets/Female3DCG/Female3DCG.js
This adjusts the alpha masks and `Hide` entries for the Seamless Open Crotch Strait Dress to fix an issue where some items like skirts would clip through it (see image below).
> Bugfix: Adjusts alpha masks & `Hide` entries on the seamless open crotch strait dress

- BondageClub/Screens/Room/AsylumEntrance/AsylumEntrance.js
Fixes a crash preventing login, when player with more than 50 patient reputation tries to login, while committed to asylum.
> Hotfix: Fix crash in `AsylumEntrancePlayerJacket`

- BondageClub/Scripts/ExtendedItem.js
Under some circumstances (that I've yet to reproduce), it appears to be possible to reach the extended item draw function in a state where the extended item script can't identify the currently selected extended option. This results in the following error being thrown:
I suspect this may happen when the item's `Property` ends up being `undefined` (generally due to the player leaving the extended menu immediately after equipping the item), although I've not managed to figure out how the game is hitting the `Draw` function without first hitting the load function immediately beforehand.
In any case, this adds a null check for `CurrentOption` inside the `ExtendedItemValidate`, which should fix this particular error, although I'm still unsure about the root cause.
> Bugfix: Adds a null check to extended item `ChangeWhenLocked` checks

- BondageClub/Screens/Character/Relog/Relog.js
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Server.js
When relogging, the contents of InputChat are saved in the same manner that the chat log is saved.
This pull request is motivated by having, multiple times, lost a paragraph I was typing because there was a disconnect to the server and I had to retype the entire thing.  Now, the text that was being entered wont get cleared and wont have to be retyped.
> Save input text when relogging in chat rooms.

- BondageClub/Assets/Female3DCG/Female3DCG.js
The Bed is being given an override height so that it isn't pushed offscreen in the petsuit, or moved around by things like heels.
> Bed Position

- BondageClub/Assets/Female3DCG/Female3DCG.js
A small but significant change to the Strait Leotard. I changed it so that the Strait Leotard has similar behaviour to the Futuristic Leotard.
That being that the suit itself is really low priority while the arms have a higher priority allowing items to be layered on top of the suit, but below the arms.
I chose to have them on layer 31 as this puts the arms over the top of most clothing items, giving a nice effect where they hug under the breasts.
Personally I think that some other strait jackets could have this behaviour. But I also think it might be a good idea to expand the `OverridePriority` system to allow manipulating of layers individually. Something like if it is in an array it applies each number to a layer but if it is a flat number then it applies to all. Either that or a …
> Strait Leotard Layer Priority Change

- BondageClub/Scripts/Common.js
- BondageClub/Scripts/ModularItem.js
This adds support for a few extra properties to modular items. These are things that are not currently used, but have been requested or discussed by other contributors. The newly supported properties are:
* `SetPose` - The `SetPose` array for each module will be merged into the final `SetPose` array. Asset contributors should take care not to create modular items where the `SetPose` properties might conflict or cause unpredictable results
* `OverridePriority` - The final merged `OverridePriority` will be the `OverridePriority` of the _last_ module that defines one. Again, asset contributors should take care not to create modular items where the `OverridePriority` properties might conflict or cause unpredictable results
* `HeightModifier` - The `HeightModifier` of each module will be …
> Feature: Extended modular item property support

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
- BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js
- BondageClub/Screens/Inventory/ItemNeckAccessories/CollarShockUnit/CollarShockUnit.js
- BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
- BondageClub/Screens/Inventory/ItemPelvis/SciFiPleasurePanties/SciFiPleasurePanties.js
- BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/ExtendedItem.js
- BondageClub/Scripts/Inventory.js
- BondageClub/Scripts/Struggle.js
- BondageClub/Scripts/Typedef.d.ts
This adds a new "Items can affect your facial expression" shared preference in the General settings menu, true by default. When disabled, changes to facial expression triggered by assets or extended item options will no longer occur. It also disables expression changes from struggling. This option has been requested a few times.
Also:
- Fixes made to expression-affecting shocks which weren't applying the blush.
- Fixed the extended option expressions to allow several changes like assets (though the currently existing cases only ever change one).
- Tweaked some General settings to appear on Extreme difficulty but disabled instead of being hidden.
> Item Expression Trigger Preference

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
The notification check for whenever a friend enters a chatroom had mistakes, making it always interpret the setting as off.
> Notifications Friend Join fix

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- BondageClub/Scripts/Validation.js
- BondageClub/Scripts/VibratorMode.js
Allows the player (if appearance is below Extreme) to block advanced vibrator modes in the arousal menu. If the player is extreme, it is forced off (because the player cannot block any items or types).
Also adds validation to prevent trolling.
> Advanced Vibrator Modes Disable

- BondageClub/CSS/Styles.css
- Fixed the newer chat styles (dark/light 2) on mobile.
Font-size was insanely huge on mobile, removing these keeps it on par with other styles and doesn't change much other than making it usable on mobile/small windows.
(Had Ellie's permission for this fix)
> fix light/dark 2 mobile

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Scripts/Typedef.d.ts
The appearance screen's "Show character in previews" button state is now saved to the player preferences so that it doesn't have to be re-selected after every login.
> Character In Previews Setting

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Typedef.d.ts
Adds a new chat preference for the font size of the chat log. Players can pick between "Small", "Medium" and "Large", with "Large" being the current chat font size. I also included a few small refactors to some of the chat preference subscreen, to hopefully improve the readability somewhat, along with some clean up of a couple of unused variables and missing type definitions for a few preferences.
> Feature: Chat font size preference

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
When the 'hide icon' button in the chatroom is changed, it should now only reset back to the default on entering a new chatroom, so that entering submenus such as wardrobes doesn't also reset the selection.
> Hide Icon State Persistence

- BondageClub/Screens/Room/Cafe/Cafe.js
- BondageClub/Scripts/TypedItem.js
Over the last release or two, several items have been migrated over to the archetype system. However, the Cafe room was making use of the options objects that were previously defined in the item scripts. This would cause the Cafe to crash on several of the Cafe maid's dialogue options. This updates the Cafe code to get the options objects out of the typed item data lookup, which restores the previous functionality.
> Bugfix: Cafe item fixes

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Screens/Character/Appearance/Text_Appearance.csv
- added a disabled wardrobe button when the wardrobe is not owned
It's been noticed that with the increased complexity of the club, many people aren't aware they can have a wardrobe/save outfits. This adds the information that they can buy a wardrobe and this info exists in a place where they cannot miss it.
> wardrobe info

- BondageClub/Scripts/CommonDraw.js
This PR adds support for `DefaultColor` to be set in an item's `Property`. If the colour of a layer (or the whole item) is set (implicitly or explicitly) to "Default", then `Property.DefaultColor` will be used, if it exists. `Property.DefaultColor` can be an array of colour strings, or a single colour string:
* If `Property.DefaultColor` is an array, the individual array items will be used when their corresponding layer's colour is set to "Default"
* If `Property.DefaultColor` is a string, then it will be used for any colourable layer whose colour is currently set to "Default"
This will allow typed items to have different default colour palettes per type, which may be useful as we start to see more extended clothing in the game (and this is something that will support an item that …
> Feature: Allows `DefaultColor` to be set in an item's `Property`

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Online/ChatSearch/ChatSearch.js
- BondageClub/Scripts/Drawing.js
`MainCanvas.measureText(Text)` is resource heavy, and is called multiple times every frame whenever we call `DrawTextFit`, causing screens like `ChatSearch` to take a lot of unnecessary script time while idling or doing other things.
I extracted the logic that finds the size and text to render into its on memoized function so that it would only do the necessary calculations once. The difference here is astronomical (see pics below).
The decision to clear the memo cache when leaving chatsearch is to prevent the cache from growing too big if someone stays in the club for a long time. 
during ~26s of idling, before ~80% of script time was in `DrawTextFit` for a total of ~4.9s, after it was ~61% with ~0.9s which is ~80% less
Before:
After:
> DrawTextFit Optimisation

- BondageClub/Screens/Character/Player/Dialog_Player.csv
- BondageClub/Scripts/ExtendedItem.js
- BondageClub/Scripts/Inventory.js
- BondageClub/Scripts/TypedItem.js
- BondageClub/Scripts/Typedef.d.ts
This is a follow-up to #2637, and adds support for random item extension to the `InventoryWearRandom` function. If the item has the correct archetype (only typed items are supported for now), and the `Extend` parameter is passed to the function, `InventoryWearRandom` will now randomly select an item type and apply it. This means that anywhere which was previously using `InventoryWearRandom` to bind the player will now also be able to randomly select item types, as applicable. As we move more items over to the archetypes system, this feature should automatically support those items. Typed item options also now support a `Random` flag just like assets to indicate whether or not they can be randomly selected.
The PR also modifies some of the functions added by #2637 so that they now respect …
> Feature: Adds extended item support to `InventoryWearRandom` (and NPCs!)

- BondageClub/Scripts/Drawing.js
- BondageClub/Scripts/GLDraw.js
In #1026, handling was added for when the WebGL context is lost and restored. Usually this is due to a lack of resources on the player's machine, but more often than not, it never seems to get restored when the issue occurs in real situations. This adds a timeout to the context lost listener so that if the context isn't successfully restored after 10 seconds, the game will forcefully remove the GLDraw canvas and recreate it, and rebuild the canvas of all characters currently on the screen, forcing them to be re-rendered.
If _another_ context loss then happens within a further 50 seconds (i.e. two context losses within a minute), the game will revert character rendering back to the original `CharacterAppearanceBuildCanvas` function, and no longer use `GLDraw` (thanks to @ace-1331 for that …
> Improvement: Force reset the canvas after a context loss if it is not restored after 10 seconds

- BondageClub/Scripts/Inventory.js
It came to my attention recently that ball gags (or, as it turns out any gags with the `GagUnique` prerequisite) were never being selected in the random item pool. The reason for this is that the `InventoryPrerequisiteMessage` function returns `null` rather than an empty string if `C.FocusGroup` isn't set, which meant it would fail this check in `InventoryAllow`:
```js
return (Msg == "");
```
This PR updates `InventoryPrerequisiteMessage` and `InventoryPrerequisiteConflictingGags` so that `C.FocusGroup` being set is no longer a hard requirement. However, the `GagUnique` prerequisite is slightly different from others in that it pulls some contextual information from the current focus group. Therefore, if no focus group is set, the prerequisite returns an error if _any_ of the mouth groups …
> Bugfix/Improvement: `GagUnique` prerequisite improvements

- BondageClub/Assets/Female3DCG/Female3DCG.csv
- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Assets/Female3DCG/LayerNames.csv
All other panel gags support layering on top of the gag and, more importantly, they can be used in slots 2 and 3.
This pull requests updates the **Foxy Harness Gag** to allow it to be used in slots 2 and 3. I want to stuff my gags!
I believe I've done everything required to support multiple slots, including putting the gag into a `BuyGroup`.
I've tested it and it seems to work as I expect.
Note: I believe this update also lowers the gag level from the default `GagNormal` to `GagEasy`. I'm not 100% sure there as I am not certain how this works, but this also brings it in line with the other panel gags, as I made sure to follow their configuration.
> Update FoxyHarnessPanelGag to support all slots

- BondageClub/Scripts/Inventory.js
Examining a gag in the first/leftmost gag slot was not showing the Remove button, since it thought the player was looking at a "4th" mouth slot rather than the 1st.
> Gag Removal Fix

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Tools/Node/AssetCheck.js
Items using "typed" archetype have these properties automatically generated from options, meaning they should *not* have them set manually.
This PR adds check to assetcheck for this case and fixes current errors.
> Improvement: Add check for auto-generated `AllowType`, `AllowBlock` and `AllowEffect`

- BondageClub/Scripts/Common.js
- BondageClub/Scripts/ControllerSupport.js
- BondageClub/Scripts/Drawing.js
- BondageClub/Scripts/Typedef.d.ts
- BondageClub/index.html
Updates per-screen functions to following:
- `Run(time: number)` Called each frame [change: add `time` parameter]
- `Click(event: MouseEvent|TouchEvent)`  Called when user clicks on the canvas [change: pass event]
- `Load()` Called when screen is loaded using `CommonSetScreen` [no change]
- `Unload()` Called when this screen is being replaced [change: new function]
- `Resize(load: boolean)` Called when screen size or position changes or after screen load [change: new function]
- `KeyDown(event: KeyboardEvent)` Called when user presses any key [change: pass event]
- `Exit()` Called when user presses Esc [no change]
Also changes the way these functions are called, improving the performance
Tested and fully compatible with existing screens
> Feature: New screen functions and optimisations

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Scripts/Dialog.js
- BondageClub/Scripts/Element.js
- fixed a crash occurring when leaving rooms after the recent addition of the resize manager.
- fixed chat resizes being applied while resizing when in a dialog
- improved the resize and element functions to be more robust
-  jomshir reworked it so DialogLeave no longer calls the resize function (instead it is kept track of inside the chatroom logic)
> resize crash fix

- BondageClub/Screens/Character/Appearance/Appearance.js
- BondageClub/Scripts/CommonDraw.js
- BondageClub/Scripts/Dialog.js
The up button could have strange behaviors in certain cases, some were accentuated by certain types of items, this aims to make it a bit more user friendly
- turned the up button into a toggle so it is possible to revert to normal height without losing focus on the character
- fixed the arrows being inverted while suspended
- fixed the character going back down on refreshes
- fixed the items with `FixedPosition: true` being rendered in a different position compared to the character, which can break most items that aren't just "decor"/ need to maintain consistency in height (like boxes, the kennel, etc.)
> Up button improvements

- BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
- BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
This pull requests does the following things:
**Update the FuturisticVibrator to escape user inputs rather than accepting raw regex**
This would confuse users, where characters like `.` would cause unintended side effects.
It is also a vector for attack, as it is possible to craft "evil regex" that would crash browsers.
Escaping avoids this issue.
**Update the FuturisticVibrator to accept \* wildcards**
As a result of the new changes (prior to this pull request), the belt now only triggers on full words.
This new change handles this by converting any `*` character into a wildcard that will match anything.
**Update the FuturisticVibrator to instantly respond to messages**
Previously, the vibrator would check the chat chat log for messages once every second.
This change has the script …
> Updates and fixes to the FuturisticVibrator (and minor change to FuturisticTrainingBelt)

- BondageClub/Scripts/Validation.js
- fixed the validation code to understand cases where items were not locked
Expression triggers were causing false errors and refreshes because of the property RemoveTimer which is common on both locks and expressions.
> validation lock check

- BondageClub/Scripts/TypedItem.js
A fix to prevent crashing for extended items with no Type in their config, such as the Kigurumi Mask.
> Modular Item Validation Fix

- BondageClub/Screens/Character/Appearance/Appearance.js
When an item cannot be used due to failed prerequisites but is a favorite of the character, the box background was white when it should be grey. Now fixed.
> Unusable Favorites Fix

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Not really a fix so much as an adjustment based on feedback in the beta errors channel. This adjusts the font size settings so that:
* Medium is now the same size as the old default font size (for the dark 1/light 1 themes)
* Large should now allow for a larger size on mobile devices and smaller screens as it did before in the light 2/dark 2 themes (although not to quite the same extreme on mobiles)
> Bugfix: Font size setting adjustments

- BondageClub/Scripts/ColorPicker.js
- BondageClub/Scripts/Dialog.js
When the colour in the colour picker screen was changed using certain methods, such as typing in a hex code or loading a saved colour using the new feature, the 'current colour' box (near the bottom beside an 'initial colour' box) didn't change.
When viewing another character but changing the colour for an object on yourself, some buttons such as Exit and Default did nothing.
> Color Picker Fixes

- BondageClub/Assets/Female3DCG/Female3DCG.js
- added missing AllowEffect on the wiredegg which caused the properties to be removed and cause unnecessary refreshes
> WiredEgg missing AllowEffect

- BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
-Fixes issue where the current mode as it appears in the access denied screen is wrong, and the setting won't apply
-Fixes a crash when the player is in a dialog when it triggers
> Fixes issues with the training belt

- BondageClub/Assets/Female3DCG/Female3DCG.js
- BondageClub/Assets/Female3DCG/Female3DCGExtended.js
- BondageClub/Screens/Inventory/ItemTorso/NylonRopeHarness/NylonRopeHarness.js
- BondageClub/index.html
`NylonRopeHarness` used `HempRopeHarness` functions, however `HempRopeHarness` was converted while `NylonRopeHarness` wasn't, this PR fixes that.
> Beta-fix: Convert ItemTorso:NylonRopeHarness to typed item

- BondageClub/Tools/Node/AssetCheck.js
Makes AssetCheck follow extended item's `CopyConfig`, so it can catch more errors
> Beta-fix: AssetCheck: respect CopyConfig

- BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor.csv
A small fix to ensure the two new groups appear in the shop's sell options in the rare case they're the only owned items on that page.
> Shop Sell Group Fix

- BondageClub/Scripts/ColorPicker.js
When typing in a hex code for a colour, the step to refresh everything with the selected colour always included the input box as well, which resulted in the player being interrupted halfway through with a "completed" value. Now when the change comes from the input box, the box's value will not be changed.
There was also an issue where the colour was converted from hex to HSV then back to hex which could change the value.
> Colour Entry Fix

- BondageClub/Screens/Character/Preference/Preference.js
In the Immersion preferences menu the 'Sensory deprivation' and 'Disable examining when blind' settings affect each other.
When the deprivation is at the minimum setting of Light, then activating the Disable setting does nothing because the player can never be fully blind and therefore never be unable to see others.
When the deprivation is at the maximum setting of Total, then deactivating the Disable setting does nothing because the player will be shown a 1-person room and can't select characters to examine them anyway.
The Disable checkbox will now be disabled and automatically set in these two cases to help let the player know that changing it would have no effect.
> Blind Examine setting change

- BondageClub/Scripts/Inventory.js
As part of #2649, the `InventoryWearRandom` function was changed such that calling it without a `Refresh` argument would result in the character not refreshing. This meant that a subset of `InventoryWearRandom` calls in the game would not refresh the character after an item had been applied when they should have, causing the added items not to render.
> Bugfix: Ensures characters refresh properly after calling `InventoryWearRandom`

- BondageClub/Scripts/Dialog.js
At the moment if the player is in item permissions mode in the inventory menu and clicks to change focus to a different zone, the inventory jumps back to normal mode. Now it will stay in permissions mode until the player exits or clicks the mode toggle button again.
> Permissions Mode Resetting

- BondageClub/Assets/Female3DCG/Female3DCGExtended.js
- BondageClub/Tools/Node/AssetCheck_Types.js
- fixed some typed item not having Random: false which caused problems in areas where npcs would apply a random type that blocks the player within the room (such as serving drinks in online rooms)
- fixed the asset check to include proper verification for the new Random property on typed items
This covers all hogtie + allfours + frogtie types currently available in the typed items which is in line with how normal items are blocked from being randomly applied.
> fix random typed items

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- fixed the chatroom name garble immersion setting not garbling the room name when a chatroom is being updated. 
Before it would show "ace updated the room. Name: test room. Limit: 10.  public.  unlocked."
Now it shows "ace updated the room. Name: mmmm mmmm. Limit: 10.  public.  unlocked."
To avoid "cheating/ruining the immersion" of that setting. Seems like that was the only case left of a room name not getting garbled
> fix chat room name garble

- BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
- BondageClub/Screens/Online/ChatBlockItem/ChatBlockItem.js
- fixed the block category UI menu toggle not being properly canceled
Currently, going in chatadmin to update room blocks will keep them the way you left them even if you cancel out, which can cause desyncs (for example, you have or dont have a room block others have). This was in part due to the fact that ChatRoomData.BlockCategory, ChatAdminBlockCategory and ChatBlockItemCategory were all referencing the same array so the "reset" logic wasnt working as intended (and was logically incorrect).
This fix properly instates the expected (and intended) behavior where the menu will always reflect the current state of the room when you first open the chatadmin screen, then will keep the last edits until you quit by saving or cancelling
> fix incorrect room blocks persistance

- BondageClub/Screens/Room/Private/Private.js
Fixes problem with dialog reported on Discord:
> Fix: Private ActivityTarget being replaced only once

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Changes total sensory deprivation so that if you can see the player in VR then their name shows up when doing actions/emotes/chat even in total sensedep.
Also makes it so if you have the immersion option enabled that hides non adjacent players, it will replace some names with "someone" if you can't see who's doing the action or receiving it.
NOT a hotfix, makes some significant changes so do not merge till beta.
> Sensory Deprivation Changes

- BondageClub/Screens/Character/Preference/Preference.js
- BondageClub/Screens/Character/Preference/Text_Preference.csv
- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
- BondageClub/Screens/Room/Private/Private.js
Adds two more options for the arousal screen filter (from the graphics menu):
1) Gradual filter (increases over time based on arousal, visible even at 50% arousal)
2) Strong Gradient (a very powerful visual effect with a gradient flowing from the edges of the screen and pulsating gently every 2s)
The old code was refactored to be compatible and reduce code waste. Applies in both Chatrooms and Private room. The original behavior (light glow at >90 arousal) is still available as the default option.
> Arousal Glow Options

- BondageClub/Screens/Room/Shop/Shop.js
This helps reduce some confusion with items that end with numbers, e.g. Swimsuit Type 3 35$ becomes Swimsuit Type 3 $35.
> Moves the $ sign to the beginning of the price rather than the end

- BondageClub/Screens/Room/Arcade/Arcade.js
You can resume the game in a chat room but not in the arcade. This fixes that.
> Fix kinky dungeon restarting game

- BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Shows the icon even if the target isn't bound.
> Fix $ icon over bounty-carrying player
