C000_Intro/ChapterSelect/Intro_CN.csv
C000_Intro/ChapterSelect/Stage_CN.csv
C000_Intro/ChapterSelect/Text_CN.csv
C000_Intro/Intro/Intro_CN.csv

Chinese translation test

---

C007_LunchBreak/Natalie/Intro_EN.csv
C007_LunchBreak/Natalie/Script.js
C007_LunchBreak/Natalie/Stage_EN.csv
C007_LunchBreak/Natalie/Text_EN.csv

That should do it for now. The drawing.js can wait for now (it will make sure there is a glitch for players to point out), trying to sync repositories has done my head in to the point of just deleting the old fork and making new one. Crude but it seems to have worked for now, unlike my previous attempts.

Corrected Natalie files.

---

C007_LunchBreak/Natalie/Intro_EN.csv
C007_LunchBreak/Natalie/Stage_EN.csv
C007_LunchBreak/Natalie/Text_EN.csv
Drawing.js

Fixed a few typos and added updated the Drawing.js to include the gags and blindfold.
I think I have got it now so the .js is has only LF line endings now.

Natalie .csv and Drawing.js

---

C007_LunchBreak/Natalie/Intro_EN.csv
C007_LunchBreak/Natalie/Script.js

That has the images working right for me now during evil end, plus attitude change from spank now works.
During stages where the images should only ever be determined by the script.js, should I have a just in case image in Intro.csv or leave those cells blank?

Natalie fixes for evil end and a spank error

---

Common.js

implement simple CSV caching

---

.gitignore
README.md

gitignore for my IDE and a simple description with useful links.

Add github goodies

---

C999_Common/Collar/Stage_CN.csv

Fix Bug and Update Translation.
And then..The first time I make some mistake but it has recovered.
If it works this time,I wanna continue translate more things.

Fix Bug and Update Translation on Stage_CN.csv

---

C004_ArtClass/HiddenEgg/Intro_DE.csv
C004_ArtClass/HiddenEgg/Stage_DE.csv
C004_ArtClass/HiddenEgg/Text_DE.csv
C004_ArtClass/Intro/Text_DE.csv
C004_ArtClass/Jennifer/Intro_DE.csv
C004_ArtClass/Jennifer/Stage_DE.csv
C004_ArtClass/Jennifer/Text_DE.csv
C004_ArtClass/Julia/Intro_DE.csv
C004_ArtClass/Julia/Stage_DE.csv
C004_ArtClass/Julia/Text_DE.csv
C004_ArtClass/Outro/Text_DE.csv
C004_ArtClass/Sarah/Intro_DE.csv
C004_ArtClass/Sarah/Stage_DE.csv
C004_ArtClass/Sarah/Text_DE.csv
C005_GymClass/GymFight/Text_DE.csv
C005_GymClass/Intro/Text_DE.csv
C005_GymClass/Jennifer/Intro_DE.csv
C005_GymClass/Jennifer/Stage_DE.csv
C005_GymClass/Jennifer/Text_DE.csv
C005_GymClass/LoseFight/Text_DE.csv
C005_GymClass/Outro/Text_DE.csv
C005_GymClass/WinFight/Text_DE.csv
Common.js

Had some free time today, so I was able to finish this one a bit sooner than expected. I hope this doesn't feel spammy, I could also do larger commits/PRs with more time between them if that would be better.
A few minor questions came up for me in this chapter:
1. Does the line "call me Julia" imply that Julia wants her students to be on a first-name-basis with her (if you can even call it that since nobody seems to have a last name)? For now I assumed that it does. It kind of matters because in german you adress people with different words depending on how formal your relationship is. (This is actually going to be a challenge when submissives call other characters "Miss" more often, because their way of adressing them would probably have to switch back and forth, but I guess that's …

German Chapters 4 & 5

---

C007_LunchBreak/Jennifer/Stage_DE.csv

Just a quick correction of those two Jennifer lines. I would have just included this with the next chapter, but maybe this way it can still make it into the upcoming release.

German Chapter 7 quick fix

---

BondageClub/Screens/Character/Cheat/Cheat.js
BondageClub/Screens/Character/Cheat/Text_Cheat_EN.csv
BondageClub/Screens/Room/MainHall/MainHall.js
BondageClub/Screens/Room/MainHall/Text_MainHall_EN.csv

look for trouble starts a random kidnap, new cheat disables the random kidnaps when moving from the mainhall

New Cheat + look for trouble

---

C003_MorningDetention/Sidney/Intro_DE.csv
C003_MorningDetention/Sidney/Stage_DE.csv
C003_MorningDetention/Yuki/Stage_DE.csv
C004_ArtClass/HiddenEgg/Stage_DE.csv
C004_ArtClass/Jennifer/Stage_DE.csv
C004_ArtClass/Jennifer/Text_DE.csv
C004_ArtClass/Julia/Intro_DE.csv
C004_ArtClass/Julia/Stage_DE.csv
C004_ArtClass/Julia/Text_DE.csv
C004_ArtClass/Sarah/Intro_DE.csv
C004_ArtClass/Sarah/Stage_DE.csv
C004_ArtClass/Sarah/Text_DE.csv
C005_GymClass/Jennifer/Stage_DE.csv
C006_Isolation/Mildred/Stage_DE.csv
C006_Isolation/Yuki/Stage_DE.csv
C012_AfterClass/Jennifer/Stage_DE.csv
C012_AfterClass/Sarah/Stage_DE.csv

Just those 2 recent fixes for the german version.
Edit: Plus a few more corrections and improvements for the early chapters.

German Chapter 12 fix

---

BondageClub/Screens/Character/Login/Text_Login_DE.txt
BondageClub/Screens/Cutscene/PlayerMistress/Text_PlayerMistress_DE.txt
BondageClub/Screens/Room/Introduction/Dialog_NPC_Introduction_Maid_DE.txt
BondageClub/Screens/Room/Introduction/Dialog_NPC_Introduction_Sub.csv
BondageClub/Screens/Room/Introduction/Dialog_NPC_Introduction_Sub_DE.txt
BondageClub/Screens/Room/MaidQuarters/Dialog_NPC_MaidQuarters_InitiationMaids_DE.txt
BondageClub/Screens/Room/MaidQuarters/Dialog_NPC_MaidQuarters_Maid_DE.txt
BondageClub/Screens/Room/MainHall/Dialog_NPC_MainHall_Maid_DE.txt
BondageClub/Screens/Room/MainHall/Text_MainHall_DE.txt
BondageClub/Screens/Room/Management/Dialog_NPC_Management_Mistress_DE.txt
BondageClub/Screens/Room/Management/Dialog_NPC_Management_RandomGirl_DE.txt
BondageClub/Screens/Room/Management/Dialog_NPC_Management_Sub_DE.txt
BondageClub/Screens/Room/Shibari/Dialog_NPC_Shibari_Student_DE.txt
BondageClub/Screens/Room/Shibari/Dialog_NPC_Shibari_Teacher_DE.txt
BondageClub/Scripts/Translation.js
BondageClub/_Translation/DE/Glossary.txt
BondageClub/_Translation/Tools/GenerateTranslationTemplate.html
BondageClub/_Translation/Tools/TranslationStatus.html

This contains the german translations for the Introduction Class, the Maid Quarters and the Main Hall. I also fixed a small formatting error in Dialog_NPC_Introduction_Sub.csv which would have affected the translation, hope that's ok.
I also included 2 HTML tools that I think might be useful for translators. The one to generate templates is the one I already showed you, I just changed it a bit to make it slightly more user-friendly. The other one is for checking if all the translation files are up to date. I plan to add some more features soon, but for now it should automatically detect if text gets added to a file that already has a translation, or if a line gets changed so the translation for that line will no longer work. This way it should be easier to keep track of everything as the …

German Bondage Club Beginnings + Translation Tools

---

BondageClub/Screens/Cutscene/NPCCollaring/Text_NPCCollaring_DE.txt
BondageClub/Screens/Cutscene/PlayerCollaring/Text_PlayerCollaring_DE.txt
BondageClub/Screens/Room/Introduction/Dialog_NPC_Introduction_Maid_DE.txt
BondageClub/Screens/Room/Introduction/Dialog_NPC_Introduction_Sub_DE.txt
BondageClub/Screens/Room/MaidQuarters/Dialog_NPC_MaidQuarters_Maid_DE.txt
BondageClub/Screens/Room/MainHall/Dialog_NPC_MainHall_Maid_DE.txt
BondageClub/Screens/Room/Management/Dialog_NPC_Management_Mistress_DE.txt
BondageClub/Screens/Room/Private/Dialog_NPC_Private_Custom_DE.txt
BondageClub/Screens/Room/Private/Dialog_NPC_Private_Vendor_DE.txt
BondageClub/Screens/Room/Shibari/Dialog_NPC_Shibari_Student_DE.txt
BondageClub/Screens/Room/Shibari/Dialog_NPC_Shibari_Teacher_DE.txt
BondageClub/Scripts/Translation.js
BondageClub/_Translation/Tools/GenerateTranslationTemplate.html
BondageClub/_Translation/Tools/TranslationStatus.html

Whew. After this big chunk of text, the rest should be a breeze. Almost up to speed. :D
I know you added some lines to these and some other files in the last few days, so I'll adjust those translations after this is merged.
I haven't really decided which parts to tackle next. I'm trying to stay away from the Shop and the Kidnapper's League for now, since Dallun511 said they wanted to do those, but there's still plenty of other stuff to translate.
PS: I'll probably need to revisit some lines, a few of them might be too long. I haven't found a good way to automatically check for that yet (there's the exit button to consider), but I'm working on it.
Edit: TranslationStatus.html now checks for line lengths (and indeed exposes a few lines that are longer than they should be, I'll take care of …

German Bondage Club: Private Room

---

BondageClub/Screens/Online/ChatCreate/Text_ChatCreate_DE.txt
BondageClub/Screens/Online/ChatSearch/Text_ChatSearch_DE.txt
BondageClub/Screens/Room/MainHall/Text_MainHall_DE.txt

Other than adding those few new lines, I also shortened some of the previous ones (because that last change you made allowed me to test locally again and I noticed they were too long). Good idea with those tooltips in the Main Hall by the way, I was actually about to suggest something like that. :D

German Bondage Club: new lines, some fixes

---

BondageClub/Assets/Female3DCG/Female3DCG_DE.txt
BondageClub/Screens/Character/Cheat/Text_Cheat_DE.txt
BondageClub/Screens/Cutscene/SarahIntro/Text_SarahIntro_DE.txt
BondageClub/Screens/Online/ChatCreate/Text_ChatCreate_DE.txt
BondageClub/Screens/Online/ChatRoom/Text_ChatRoom_DE.txt
BondageClub/Screens/Room/MainHall/Text_MainHall_DE.txt
BondageClub/Screens/Room/Stable/Dialog_NPC_Stable_Trainer_DE.txt

Not sure what rhythm to do these pull requests in, but here are the translations for the latest changes. (I ignored the magic theater for now, it'll be easier to do all at once when it's a bit more complete.)
Unfortunately I kind of had to revert back to the old style for the text messages, and do some minor tricks to make it work. Translating grammar is really complicated for dynamic strings like these^^'. I also had to leave out the body parts in the translation for now, having their names in their base form only just wouldn't work well. But the new system still allowed me to improve the word order, so it's definitely better than before in my opinion.

German Bondage Club: Updates to chat etc

---

BondageClub/Screens/Inventory/ItemNeck/ShockCollar/ShockCollar.js
BondageClub/Screens/Inventory/ItemNipples/VibeNippleClamp/VibeNippleClamp.js
BondageClub/Screens/Inventory/ItemVulva/VibratingEgg/VibratingEgg.js
BondageClub/Scripts/Dialog.js

A small fix for the shock collar that fixes the javascript issue caused by equipping a shock collar online and then using it without altering its intensity first. I've also fixed a few comment lines which I forgot to update when pulling code from the pump gag

Shock collar fix

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Character/Player/Dialog_Player.csv
BondageClub/Screens/Inventory/ItemNipples/VibeNippleClamp/VibeNippleClamp.js
BondageClub/Screens/Inventory/ItemVulva/VibratingEgg/VibratingEgg.js
BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Scripts/Dialog.js
BondageClub/Scripts/Inventory.js

In this package we have a few fixes and tweaks to the code:
- New InventoryItemHasEffect(Item, Effect) function in Inventory.js, which checks if an item has a specific effect. For this, it checks both the item's asset and property attribute. If no Effect is specified, it just checks if the item has any effects at all. The new function has been integrated into the code wherever applicable, replacing the old code.
- Fixes a bug for the shock collar that would cause a Javascript error when using the remote on a different type of collar
- Tweaks to the code of vibrating eggs. Now any item with the "vibrating" effect will shake in the inventory
- Tweaks to the vibrating nipple clamps, including some fixes with the dialog text
- Changed the priority of nipple items. This is due to them …

A few tweaks and fixes

---

BondageClub/Assets/Female3DCG/Female3DCG_DE.txt
BondageClub/Screens/Character/Creation/Text_Creation_DE.txt
BondageClub/Screens/Character/InformationSheet/Text_InformationSheet_DE.txt
BondageClub/Screens/Character/Player/Dialog_Player_DE.txt
BondageClub/Screens/Online/ChatRoom/Dialog_Online_DE.txt
BondageClub/Screens/Room/Sarah/Dialog_NPC_Amanda_DE.txt
BondageClub/Screens/Room/Sarah/Dialog_NPC_Sarah_DE.txt
BondageClub/Screens/Room/Sarah/Dialog_NPC_Sophie_DE.txt
BondageClub/Screens/Room/SlaveMarket/Dialog_NPC_SlaveMarket_Auctioneer_DE.txt
BondageClub/Screens/Room/SlaveMarket/Dialog_NPC_SlaveMarket_Trader_DE.txt
BondageClub/Scripts/Translation.js
BondageClub/_Translation/Tools/GenerateTranslationTemplate.html

Just to get the base translation up to date (mostly UI stuff), hopefully before the next release. The Sophie Chapter translatio unfortunately still isn't finished, but we might have another volunteer for that, as you probably saw.
**Edit:** I also tweaked the translation template generator a bit so it can now automatically fix translation files that are out of date, and used it for Sarah's and Amanda's dialogue to include their new lines (not translated yet), and then I also included my current progress on the Sophie file. This is mostly so that Drussler1 can start working on it, since they expressed interest.

German Bondage Club translation updates

---

BondageClub/Screens/Room/Sarah/Dialog_NPC_Amanda_DE.txt
BondageClub/Screens/Room/Sarah/Dialog_NPC_Sarah_DE.txt
BondageClub/Screens/Room/Sarah/Dialog_NPC_Sophie_DE.txt

Took way longer than it should have, but the Sophie scene is finally done! All of these parts that weren't there before were translated by @Drussler1 , not me. Thanks again for the help! All I did on this one was proofreading and making sure it's somewhat consistent with the rest of the translation in trems of style.
A few of the lines might still be too long, though I'm not sure if that's even still a concern with the new Dialog code anymore. I haven't really looked into its limits yet. If the remaining 8 lines are still too long, I'll change them as soon as I can. Next I'll also take care of the remaining new strings that were added to the game.

German Bondage Club: Sophie completion

---

BondageClub/Assets/Female3DCG/Female3DCG_DE.txt
BondageClub/Screens/Character/Appearance/Text_Appearance_DE.txt
BondageClub/Screens/Character/FriendList/Text_FriendList_DE.txt
BondageClub/Screens/Character/InformationSheet/Text_InformationSheet_DE.txt
BondageClub/Screens/Character/Player/Dialog_Player_DE.txt
BondageClub/Screens/Online/ChatRoom/Dialog_Online_DE.txt
BondageClub/Screens/Room/KidnapLeague/Dialog_NPC_KidnapLeague_RandomKidnapper_DE.txt
BondageClub/Screens/Room/MaidQuarters/Dialog_NPC_MaidQuarters_Maid_DE.txt
BondageClub/Screens/Room/MainHall/Dialog_NPC_MainHall_Maid_DE.txt
BondageClub/Screens/Room/Management/Dialog_NPC_Management_Mistress_DE.txt
BondageClub/Screens/Room/Private/Dialog_NPC_Private_Custom_DE.txt
BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor_DE.txt
BondageClub/Scripts/Translation.js

German translations for all the new strings since the last update, plus a few minor fixes.

German translation update

---

BondageClub/Assets/Female3DCG/Female3DCG_DE.txt
BondageClub/Screens/Character/Player/Dialog_Player_DE.txt
BondageClub/Screens/Room/MaidQuarters/Dialog_NPC_MaidQuarters_Maid_DE.txt
BondageClub/Screens/Room/MainHall/Dialog_NPC_MainHall_Maid_DE.txt
BondageClub/Screens/Room/Management/Dialog_NPC_Management_Mistress_DE.txt
BondageClub/Screens/Room/Private/Dialog_NPC_Private_Custom_DE.txt
BondageClub/Screens/Room/Private/Dialog_NPC_Private_Vendor_DE.txt
BondageClub/_Translation/Tools/GenerateTranslationTemplate.html
BondageClub/_Translation/Tools/TranslationStatus.html

Just a couple more translations for the new lines in the private room, as well as a few other places (this isn't 100% up to date, I'm mostly just doing this now to lessen the workload later, and to update the german version of the line discussed in #201 ).
(This also includes a fix for a minor formatting error in the translation updating tool, and I removed the length checking for NPC lines from the status tool, since overflow isn't really a concern anymore.)

German Translation Updates

---

BondageClub/Scripts/Inventory.js

noticed in the beta my code wasn't working right. I was missing a null check.

missing null check causing error

---

BondageClub/Screens/Inventory/ItemVulva/VibratingLatexPanties/VibratingLatexPanties.js

the panties had the lock code part missing to make them keep locked after using the remote

missing code

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Scripts/Character.js
BondageClub/Scripts/Speech.js

I now use the standard speech garble functions, although I had to create a function combining both.
I didn't feel confident to modify the normal SpeechGarble() functions since a lot of stuff seems to depend on them.
What do you think?

Added deafening effect to hood, number 2.

---

BondageClub/Assets/Female3DCG/Female3DCG.js

added priority to bra style 3 and bandeau to hide some the torso items due big-chested ladies was not right

quick fix to 2 bras

---

BondageClub/Screens/Inventory/ItemArms/DuctTape/DuctTape.js
BondageClub/Screens/Inventory/ItemArms/LeatherCuffs/LeatherCuffs.js
BondageClub/Screens/Inventory/ItemArms/PaddedMittens/PaddedMittens.js
BondageClub/Screens/Inventory/ItemArms/PaddedMittensHarness/PaddedMittensHarness.js
BondageClub/Screens/Inventory/ItemArms/PaddedMittensHarnessLocked/PaddedMittensHarnessLocked.js
BondageClub/Screens/Inventory/ItemArms/PaddedMittensLocked/PaddedMittensLocked.js
BondageClub/Screens/Inventory/ItemArms/StraitJacket/StraitJacket.js
BondageClub/Screens/Inventory/ItemButt/ButtPump/ButtPump.js
BondageClub/Screens/Inventory/ItemHands/PaddedMittens/PaddedMittens.js
BondageClub/Screens/Inventory/ItemHands/PawMittens/PawMittens.js
BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
BondageClub/Screens/Inventory/ItemHead/DuctTape/DuctTape.js
BondageClub/Screens/Inventory/ItemMisc/IntricatePadlock/IntricatePadlock.js
BondageClub/Screens/Inventory/ItemMisc/MetalPadlock/MetalPadlock.js
BondageClub/Screens/Inventory/ItemMisc/MistressPadlock/MistressPadlock.js
BondageClub/Screens/Inventory/ItemMisc/OwnerPadlock/OwnerPadlock.js
BondageClub/Screens/Inventory/ItemMisc/TimerPadlock/TimerPadlock.js
BondageClub/Screens/Inventory/ItemMouth/ClothGag/ClothGag.js
BondageClub/Screens/Inventory/ItemMouth/DuctTape/DuctTape.js
BondageClub/Screens/Inventory/ItemMouth/PlugGag/PlugGag.js
BondageClub/Screens/Inventory/ItemMouth/PumpGag/PumpGag.js
BondageClub/Screens/Inventory/ItemNeck/ShockCollar/ShockCollar.js
BondageClub/Screens/Inventory/ItemNeckAccessories/CollarShockUnit/CollarShockUnit.js
BondageClub/Screens/Inventory/ItemNipples/VibeNippleClamp/VibeNippleClamp.js
BondageClub/Screens/Inventory/ItemPelvis/LoveChastityBelt/LoveChastityBelt.js
BondageClub/Screens/Inventory/ItemTorso/HempRopeHarness/HempRopeHarness.js
BondageClub/Screens/Inventory/ItemVulva/VibratingEgg/VibratingEgg.js
BondageClub/Screens/Inventory/ItemVulva/VibratingLatexPanties/VibratingLatexPanties.js
BondageClub/Scripts/Dialog.js

removed occurrences of
DrawButton(1885, 25, 90, 90, "", "White", "Icons/Exit.png");
in all usable items.
Added exit button drawing in Dialog.js instead.

minor code cleanup: exit button for usable items

---

BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv

Buttons for corresponding actions. I just added them below the kick and ban options. I have no better idea where to put them

Added Buttons to RoomAdmin to moveLeft and moveRight

---

BondageClub/Screens/Character/Appearance/Appearance.js

when the body is hidden it still must be part of the appearance

CharacterAppearanceFullRandom fix AllowNone

---

BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv

This PR replaces #362 and is based on comments from that PR
This adds multiple menus to the chat room drinks menu and adds lots more options like non-alcoholic options and hot drinks

Adds multiple drink menus and lots of drinks

---

BondageClub/Screens/Character/Player/Dialog_Player.csv
BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTag/CollarNameTag.js

better text for CollarNameTag

---

BondageClub/CSS/Styles.css
BondageClub/Scripts/Element.js

Two small changes to the new chat styles, based on feedback from Discord:
- adjsuted the code a bit to make the non-default styles work in the Edge browser
- changed the color of whispers when using dark mode, to make them more distinguishable from regular chat

Chat Style Adjustments

---

BondageClub/Assets/Female3DCG/Female3DCG_DE.txt
BondageClub/Screens/Character/Player/Dialog_Player_DE.txt
BondageClub/Screens/Room/AsylumTherapy/Dialog_NPC_AsylumTherapy_Nurse_DE.txt
BondageClub/Screens/Room/AsylumTherapy/Dialog_NPC_AsylumTherapy_Patient_DE.txt

Just a small one this time, mostly to fix a few mistakes found by @Dallun511 in #437 .

German Translation Fixes

---

BondageClub/Screens/MiniGame/HorseWalk/Text_HorseWalk.csv

I don't think this requires much explanation.

Fix small spelling issues in the horse minigames

---

BondageClub/Screens/Character/InformationSheet/InformationSheet.js
BondageClub/Screens/Character/Login/Login.js
BondageClub/Screens/Character/OnlineProfile/OnlineProfile.js
BondageClub/Scripts/Character.js
BondageClub/Scripts/Common.js
BondageClub/Scripts/Element.js
BondageClub/index.html

A separate page for players info, currently only displaying a big text area for characters Description property.
requires change on server: https://github.com/Ben987/Bondage-Club-Server/pull/12

OnlineProfile page

---

BondageClub/Screens/Character/Appearance/Appearance.js
BondageClub/Screens/Room/Magic/Magic.js
BondageClub/Screens/Room/Private/Private.js
BondageClub/Scripts/Asset.js
BondageClub/Scripts/Character.js

in some cases the sort was done in three times
assets should never be invalid state there by AssetReload is pointless

reduce the CharacterAppearanceSort calls, remove AssetReload

---

BondageClub/Scripts/Speech.js

Now gag talk feature works for Cyrillic based languages.

Added russian (and cyrillic based) language support to gag talk feature

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Character/Player/Dialog_Player.csv

-fixed dialog error with wrist shackles
-fixed alpha mask of the boots cutting off the base of the One bar prison

wrist shackles and one bar prison fixes

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Character/Player/Dialog_Player.csv
BondageClub/Scripts/Inventory.js

- Prevented use of toe items on items that should otherwise keep your legs open

Fix For toe items

---

BondageClub/Assets/Female3DCG/Female3DCG.csv

Added line so leashes are now removed from "collar" instead of "itemneckrestraints"

Itemneckrestraints fix

---

BondageClub/Screens/Character/Appearance/Appearance.js
BondageClub/Screens/Character/Preference/Preference.js
BondageClub/Screens/Character/Preference/Text_Preference.csv
BondageClub/Scripts/Server.js

- Volume audio control, goes from 0% to 100% and increments by 10%
- Toggle to keep all restraints that would usually be removed at login because some people like to keep them.

Two new settings

---

BondageClub/Screens/Room/Management/Management.js
BondageClub/Scripts/Character.js
BondageClub/Scripts/Timer.js

- RemoveItem property is now being used properly
- mistress timer locks are added correctly when becoming mistress (yes I tested it properly this time... sorry ><)

some fixes for the timer locks

---

BondageClub/Screens/Character/Player/Dialog_Player.csv
BondageClub/Screens/Character/Player/Dialog_Player_DE.txt
BondageClub/Screens/Character/Player/Dialog_Player_FR.txt
BondageClub/Screens/Character/Player/Dialog_Player_RU.txt
BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
BondageClub/Screens/Inventory/ItemMisc/OwnerTimerPadlock/OwnerTimerPadlock.js
BondageClub/Screens/Inventory/ItemNipples/TapedVibeEggs/TapedVibeEggs.js
BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
BondageClub/Screens/Online/ChatRoom/Dialog_Online_DE.txt
BondageClub/Screens/Online/ChatRoom/Dialog_Online_FR.txt
BondageClub/Screens/Online/ChatRoom/Dialog_Online_RU.txt

- maid drink pick messages are handled through the dictionary
- taped nipple eggs tag corrected
- ungarbled move left-right
- fixed message add unknown amount of time on timer owner lock
- fixed spanking toys not sending the correct item in the chat

Dictionary fixes

---

BondageClub/Screens/Character/Login/Login.js

The pony bit gag was there for layer 2 and 3, but was never given to the players

Fix: Added pony bit gag to the stable check login function (layer2/layer3)

---

BondageClub/Screens/Character/FriendList/FriendList.js
BondageClub/Screens/Character/Player/Dialog_Player.csv
BondageClub/Scripts/Server.js

This pull request goes with the pull request of the same name for the server side.
-When a user is in the asylum, it will be shown in the beeps and the friends list to avoid confusion when trying to find a room. Will work if more "spaces" are added in the future. This is ignored if the user is in a private room
I have tested it locally with different languages and with characters in different public/private rooms and found no bugs thus far.
Since this is my first PR, please do let me know if I did anything wrong so I can correct it asap.

Show chatroom space in beeps and friends list

---

BondageClub/Screens/Character/Appearance/Appearance.js
BondageClub/Screens/Character/Player/Dialog_Player.csv

Just a simple message sent when clothes are changed in a chatroom.
might spam a little the chatbox though.
also possible to add a C.MemberNumber as a target to the message sent to avoid that side effect, but I'm not a big fan of that solution.

Message when changing clothes in chatrooms

---

BondageClub/Screens/Character/Player/Dialog_Player.csv
BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv

requires https://github.com/Ben987/Bondage-Club-Server/pull/20

ServerMove functionality

---

BondageClub/Scripts/Drawing.js

add DrawAssetGroupZone function;
add parameter Thickness in DrawEmptyRect

[Full Zone Grid on Character] improved

---

BondageClub/Screens/Character/BackgroundSelection/BackgroundSelection.js
BondageClub/Screens/Character/BackgroundSelection/Text_BackgroundSelection.csv

Since more backgrounds are coming I added a filter so users can search by name of the background,
Added few texts at the top like currently selected room and info about the filter

BackgroundSelection filter and texts

---

BondageClub/Scripts/Drawing.js
BondageClub/Scripts/Inventory.js

Pretty small improvement that highlights zones that have items equipped.

Highlight zones with items

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Scripts/Drawing.js

replace dark backgrounds with a transparent black rectangle
my tests have shown no performance hit on drawing the rectangle

Better dark factor for backgrounds

---

BondageClub/Screens/Character/InformationSheet/Text_InformationSheet.csv
BondageClub/Screens/Character/Title/Text_Title.csv
BondageClub/Screens/Character/Title/Title.js

- [Lady Luck](https://en.wikipedia.org/wiki/Lady_Luck) at reputation 100 for gambling
- [Nawashi](https://en.wikipedia.org/wiki/Nawashi) at skill 10 for bondage
- [Houdini](https://en.wikipedia.org/wiki/Harry_Houdini) at skill 10 for evasion

new titles

---

BondageClub/Scripts/Dialog.js

-struggle option appear only if player can't interact (Player.CanInteract() == false)

fixed struggle/remove/unlock menu buttons

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Room/MaidQuarters/MaidQuarters.js

Fixed a missing 1 in the maid apron name, and fixed a bug that made it invisible.

Maid Apron Fixes.

---

BondageClub/Screens/Character/Player/Dialog_Player.csv
BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
BondageClub/Scripts/Dialog.js

new owner rule to prevent the use of remote on oneself

New owner remote rule

---

BondageClub/Assets/Female3DCG/Female3DCG.js

added a few more things to hide, this stops clipping of items worn under the restraint

mermaid suit tweak

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js

reworked the size/position of the pink overlay near orgasm to avoid having it on top of dark background or UI elements.

modified pink overlay near orgasm

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Scripts/Server.js

add ChatRoomSyncSingle to update a single character in the room
requires https://github.com/Ben987/Bondage-Club-Server/pull/21

ChatRoomSyncSingle 

---

BondageClub/Scripts/Server.js

Remove impossible combinations of properties

Additional Property Check

---

BondageClub/Screens/Character/Player/Dialog_Player.csv
BondageClub/Scripts/Dialog.js

add option to reset all expression at once

Reset expression

---

BondageClub/Assets/Female3DCG/Female3DCG.js

TailStraps belong to the Appearance, Zone should only exist on Items

Remove Zone from TailStraps

---

BondageClub/Screens/Character/Preference/Preference.js
BondageClub/Screens/Character/Preference/Text_Preference.csv
BondageClub/Screens/Online/ChatRoom/ChatRoom.js

added a setting in the audio tab preferences to play sounds only if player is involved

setting : sounds are played only if player involved

---

BondageClub/Screens/Character/Preference/ActivityDictionary.csv

Just a couple of tiny fixes to the grammar of some of the sexual activity messages in chatroooms.

Bugfix: Grammar/typo fixes in sexual activity messages

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js

this is an old bug, but now you should not be able to soft lock someone when sending them to by a drink as all gags are removed.

Maid Soft Lock

---

BondageClub/Screens/Character/Wardrobe/Wardrobe.js

Expression no longer get reset upon WardrobeFastLoad

Expression fix

---

BondageClub/Screens/Character/Appearance/Appearance.js

rewrote the appearance sort function by using insertion sort
that will allow to have more than 50 layers of priority and finally get a proper layer system without any conflict if someone wants to work on it

insertion sort for appearance

---

BondageClub/Screens/Room/Prison/Dialog_NPC_Prison_Police.csv
BondageClub/Screens/Room/Prison/Prison.js

Fixing incorrect function references which froze the game when they were hit.

Prison Police fixes

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js

Fix for the Up button which still displayed feet for the all-fours pose, and wasn't blocking devices as intended for the hogtied & all-fours poses.

Up button fix

---

BondageClub/Scripts/Dialog.js
BondageClub/index.html

- fixed combination lock input fields not being removed when clicking on a zone to interact with

more fixes

---

BondageClub/Assets/Female3DCG/Female3DCG.js

fixed a missing pose which prevented one of the alternative chain style from being rendered

Fix: Arm chains pose

---

BondageClub/Screens/Character/InformationSheet/InformationSheet.js
BondageClub/Screens/Character/Login/Login.js
BondageClub/Screens/Room/Management/Management.js
BondageClub/Scripts/Character.js
BondageClub/Scripts/Server.js

hotfix to be applied to the current client (R57) to support multiple lovers once the server is updated with #[30](https://github.com/Ben987/Bondage-Club-Server/pull/30)
incompatible with the multiple lovers PR #834
Known issues : 
- players with that hotfix and the updated server could ask other players to have multiple lovers and accept (since it's all handled server side) but will not have any impact on their gameplay (except for permissions)

Multiple Lovers - Hotfix

---

BondageClub/Scripts/Character.js

A temporary fix that remove all superfluous data received from the server concerning lovership

temporary fix : superfluous lovership data from server

---

BondageClub/Scripts/Character.js

- fix for the crash with one Player and two NPCs as lovers and saying "I love you"

fixes : Multiple lovers

---

BondageClub/Screens/Character/Player/Dialog_Player.csv
BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Scripts/Dialog.js

Followup fix to #919 to properly call the dialog function that checks if the player is currently in a chat room.

Admin Actions on Self fix

---

BondageClub/Scripts/Character.js
BondageClub/Scripts/Server.js

Lover data is now always sent to server, allowing to break properly with Private Lovers
part of the fix for breaking with "clingy" private lovers

Lovers fix - clingy Private Lovers

---

BondageClub/Scripts/Inventory.js
BondageClub/Scripts/Server.js

as title says, fix owner/lovers lock resetting to player's number after struggling/wand/exiting the room

fix owner/lovers lock resetting to player number

---

BondageClub/Assets/Female3DCG/Female3DCG.js

This PR solves the following issues:
- Breast slot was accessible through vac bed [#877120](http://www.hostedredmine.com/issues/877120)
- Wired vibrating egg could be applied through panties [#877125](http://www.hostedredmine.com/issues/877125)

Fixed errors on vac bead and wired egg

---

BondageClub/Screens/Character/InformationSheet/InformationSheet.js

reworked how owner and lovers are displayed in the information sheet
- longer names will be properly displayed
- owners will be visible at all times
- removed some redundant lines

Info Sheet rework

---

BondageClub/Assets/Female3DCG/Female3DCG.js

added missing priority value to the corset shirt to make it work better with skirts

corset shirt fix

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Adding a prerequisite to have legs open to use the bed cuffs on the arms, as otherwise the leg cuffs connect to nothing in midair.

Bed Straps with Closed Legs fix

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Changed it so bunny plugs now behave like all other butt plugs.
These were the only two plugs you could use on someone with a zipped suit because they were missing the correct prerequisite

Change: bunny plugs

---

BondageClub/Scripts/AfkTimer.js

Added JSDoc comments to the functions in `AfkTimer.js` to help with further development.
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/AfkTimer)

Improvement: Added JSDoc comments to AfkTimer.js

---

BondageClub/Screens/Character/BackgroundSelection/BackgroundSelection.js

I added JSDoc comments to the functions in `BackgroundSelection.js` to help with further development.
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/BackgroundSelection)

Improvement: JSDoc comments added to BackgroundSelection.js

---

BondageClub/Screens/Character/Creation/Creation.js

I added JSDoc comments to the functions in `Creation.js` to help with further development.
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/Creation)

Improvement: JSDoc comments added to Creation.js

---

BondageClub/Scripts/Drawing3D.js

i've deleted the second light.

 set script back to origin 

---

BondageClub/Screens/Inventory/ItemFeet/HempRope/HempRope.js

Allows the suspension tie on the feet to be used on one's self, since we have the bondage skills, and we can suspend ourselves in a hogtie, this should only make sense.

Allow leg suspension on one's self

---

BondageClub/Scripts/Dialog.js

- fixed a bug where the owner rule to block the sub from using remotes on herself would persist after breaking the collar

Fix: owner rule persisting

---

BondageClub/Scripts/GameLog.js

- added JSDoc comments to GameLog.js
I was roaming around that page, figured I would add these since it didn't take too long.
Followed Sandrine's format for consistency. 
Let me know if you prefer certain comments to be longer/shorter/different. Of course, I went with my own understanding + tried to detail most of the functions' doings.

Improvement:JSDoc comments added to GameLog.js

---

BondageClub/Scripts/GameLog.js
BondageClub/Scripts/Speech.js

- added JSDoc comments to Speech.js
Followed Sandrine's format for consistency 
Let me know if you prefer certain comments to be longer/shorter/different. Of course, I went with my own understanding + tried to detail most of the functions' doings.

Improvement: JSDoc comments added to Speech.js

---

BondageClub/Screens/Character/InformationSheet/InformationSheet.js

I added JSDoc comments to the functions in `InformationSheet.js` to help with further development.
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/InformationSheet)

Improvement: JSDoc comments added to InformationSheet.js

---

BondageClub/Scripts/NPC.js

- added JSDoc comments to NPC.js
Let me know if any description can be improved.
I never really looked at them before, so I learned quite a bit about NPCs which was interesting.

Improvement: JSDoc comments added to NPC.js

---

BondageClub/Scripts/Reputation.js
BondageClub/Scripts/Translation.js

- added JSDoc comments to Translation.js
Let me know if any description can be improved.

Improvement: JSDoc comments added to Translation.js

---

BondageClub/Scripts/Element.js

- added JSDoc comments to Element.js
Let me know if any description can be improved. 
I also did a quick refactor of `ElementIsScrolledToEnd` to simplify it, we can return the value implicitly instead of a conditional return. It doesn't change the behavior as you can see in the diff.

Improvement: JSDoc comments added to Element.js

---

BondageClub/Assets/Female3DCG/Female3DCG.js

while testing, I found the bunny plugs could be used through zipped suits, so I added the extra prerequisite like the other plugs

Fix: new bunny plugs

---

BondageClub/Screens/Character/FriendList/FriendList.js

I added JSDoc comments to the functions in `FriendList.js` to help with further development.
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/FriendList)

Improvement: JSDoc comments added to FriendList.js

---

BondageClub/Scripts/Import.js
BondageClub/Scripts/Text.js

- JSDoc comments added to Text.js/Import.js
These two files are small, happily I found nothing odd to point out in these!
Hoping to have gotten through most of core script files soon, there are a few long ones left before that part will be done

Improvement: JSDoc comments added to Text.js/Import.js

---

BondageClub/Screens/Character/Preference/Preference.js

I added JSDoc comments to the functions in `Preferences.js` to help with further development.
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/Preferences)

JSDoc comments added to Preferences.js

---

BondageClub/Scripts/Audio.js
BondageClub/Scripts/MiniGame.js

- added JSDoc comments to Minigame.js/Audio.js
Another 2 small core files commented. Slowly but surely getting to something quite useful to help people get into the project.
My only comment on this one is:
All the sounds are hardcoded in Audio.js... I think it would be a lot nicer to have Asset properties and simply be able to name the sounds there so `AudioPlayContent` only has to dynamically trigger a given sound. This would also make it easier for item makers to add a sound to their items if they already don't know how to
Unless there are any objections to this, we'll probably get to it at some point, created a task for this on the board a few of us have been using

Improvement: JSDoc comments added to Minigame.js/Audio.js

---

BondageClub/Scripts/Activity.js

- added JSDoc comments to Activity.js
Nothing special to report about this one.
As always, let me know if any comment can be improved.

Improvement: JSDoc comments added to Activity.js

---

BondageClub/Scripts/Common.js

- added JSDoc to Common.js
other than CommonIsClickAt being severely under used, a few things look a bit odd in Common.js, biggest one is how `CommonDynamicFunctionParams` seems like it could break easily if we need more than 3 parameters or if a parameter contains a comma. 
I keep the PRs separate so they are smaller chunks, easier to keep track of/discuss and to make sure two people don't work on the same file. Also, sometimes there are small refactors so it's better to keep them separate in those cases. Let me know if you prefer bigger PRs for JSDoc instead of several small ones like this
And as always, let me know if any comment can be improved.

Improvement: JSDoc comments added to Common.js

---

BondageClub/Screens/Character/Title/Title.js

I added JSDoc comments to the functions in `Title.js` to help with further development.
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/Title)

Improvement: JSDoc comments added to Title.js

---

BondageClub/Screens/Character/Wardrobe/Wardrobe.js

I added JSDoc comments to the functions in `Wardrobe.js` to help with further development.
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/Wardrobe)

JSDoc comments added for Wardrobe.js

---

BondageClub/Scripts/ColorPicker.js

Nothing particular to say about this one ^^

Improvement: JSDoc comments added to ColorPicker.js

---

BondageClub/Scripts/Character.js

- added JSDoc comments to Character.js

Improvement: JSDoc comments added to Character.js

---

BondageClub/Scripts/Timer.js

- added JSDoc comments to Timer.js
I've found several unoptimal functions I was semi-aware of before, I've listed them in [#880890](http://www.hostedredmine.com/issues/880890?issue_count=57&issue_position=10&next_issue_id=880188&prev_issue_id=878339)
We'll have a look at ways to optimize these in order to improve performances (hopefully).
I was thinking we could merge the Time to String functions into one, then use an optional parameter for the least used formats
On that note, I noticed there was still a function that didn't use the newer `ItemUpdate` function. I tested and it seems to have no side effect other than being faster. (We don't need to sync the whole appearance of a character just to add a removal timer for a lock/expression)
There is also a huge technical debt involving the …

Improvement: JSDoc comments added to Timer.js

---

BondageClub/Screens/Room/MaidQuarters/MaidQuarters.js

I added JSDoc comments to the functions in `MaidQuarters.js` to help with further development and bug fixing.
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/MaidQuarters)

Improvement: JSDoc comments added to MaidQuarters.js

---

BondageClub/Screens/Online/Game/OnlineGame.js

- added JSDoc to OnlineGame.js

Improvement: JSDoc comments added to OnlineGame.js

---

BondageClub/Scripts/Server.js

Improvement: JSDoc comments added to Server.js

---

BondageClub/Scripts/GLDraw.js

Improvement: JSDoc comments added to GLDraw.js

---

BondageClub/Scripts/Drawing.js

- added JSDoc to Drawing.js
Unless I forgot one, all main modules in /Scripts should now be covered. Since they are the baseline for the whole club, it should help people understand things better if they have a look. I'm not too preoccupied by the rooms and such, so I'll probably just do them as I change or add things in those files.
I removed some unused parameters from certain functions.. However I believe the following functions are no longer used. I left them in just because, though we could probably get rid of them (most likely due to how suspension drawing was changed a little while back)
- `DrawImageZoomMirror`
- `DrawImageMirror`

Improvement: JSDoc comments added to Drawing.js 

---

BondageClub/Screens/Inventory/ItemArms/BitchSuit/BitchSuit.js

I added JSDoc comments to the functions in `BitchSuit.js ` to help with further development.
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/BitchSuit)

Improvement: JSDoc comments added to `BitchSuit.js`

---

BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js

Improvement: JSDoc comments added to ChatAdmin.js

---

BondageClub/Screens/Online/ChatCreate/ChatCreate.js

- added JSDoc to ChatCreate.js

Improvement: JSDoc comments added to ChatCreate.js

---

BondageClub/Screens/Online/ChatSearch/ChatSearch.js

- added JSDoc to ChatSearch.js

Improvement: JSDoc comments added to ChatSearch.js

---

BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js

I added JSDoc comments to the functions in `Chains.js ` to help with further development.
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/Chains)

Improvement: JSDoc comments added to 'Chains.js`

---

BondageClub/Screens/MiniGame/Tennis/Tennis.js

- added JSDoc to Tennis.js
I've identified the issue with the FPS, I'll test a fix and submit a different PR for it

Improvement: JSDoc comments added to Tennis.js

---

BondageClub/Screens/MiniGame/MaidCleaning/MaidCleaning.js

- added JSDoc to MaidCleaning.js

Improvement: JSDoc comments added to MaidCleaning.js

---

BondageClub/Screens/MiniGame/Therapy/Therapy.js

Improvement: JSDoc comments added to Therapy.js

---

BondageClub/Screens/MiniGame/DojoStruggle/DojoStruggle.js
BondageClub/Screens/MiniGame/PuppyWalker/PuppyWalker.js

- added JSDoc comments to PuppyWalker.js & DojoStruggle.js

Improvement: JSDoc comments added to PuppyWalker.js & DojoStruggle.js

---

BondageClub/Screens/Character/FriendList/FriendList.js
BondageClub/Scripts/Drawing.js
BondageClub/Scripts/Server.js

Corrected small typos in
* `Drawing.js`
* `FriendList.js`
* `Server.js`

Improvement: Corrected some typos in the JSDoc comments

---

BondageClub/Screens/MiniGame/HorseWalk/HorseWalk.js

Improvement: JSDoc comments added to HorseWalk.js

---

BondageClub/Screens/MiniGame/SlaveAuction/SlaveAuction.js

- added JSDoc to SlaveAuction.js

Improvement: JSDoc comments added to SlaveAuction.js

---

BondageClub/Screens/Room/Shop/Shop.js

- added JSDoc to Shop.js
We're getting somewhere! Most of the vital parts and many screens are now properly documented. We're still hunting for bugs, oddities and possible refactors as we go, so far it's been quite helpful.
We keep the output at http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki but we could keep the generated HTML output in a folder if people want to view it straight from the repo. Let me know what you think.

Improvement: JSDoc comments added to Shop.js

---

BondageClub/Screens/Room/MainHall/MainHall.js

Improvement: JSDoc comments added to MainHall.js

---

BondageClub/Screens/Room/Cell/Cell.js
BondageClub/Screens/Room/LARP/LARP.js

- added JSDoc to Cell.js & LARP.js
I also removed a button that is drawn twice on the Cell screen as well as simplifying the click checks to use MouseIn.
I still have the script to reformat all the checks automatically, but for now Ill do them manually while doing JSDoc while I come across them. It makes the code a lot easier to read and a lot shorter, it also gives me the opportunity to test the buttons file by file

Improvement: JSDoc comments added to Cell.js & LARP.js

---

BondageClub/Screens/Room/AsylumBedroom/AsylumBedroom.js

* I added JSDoc comments to the functions in `AsylumBedroom.js ` to help with further development.
* Changed AsylumBedroomClick() to use the `MouseIn` function
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/AsylumBedroom)

Improvement: JSDoc comments added to AsylumBedroom.js

---

BondageClub/Screens/Room/AsylumEntrance/AsylumEntrance.js

* I added JSDoc comments to the functions in `AsylumEntrance.js ` to help with further development.
* Changed AsylumEntranceClick() to use the `MouseIn` function
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/AsylumEntrance)

Improvement: JSDoc comments added to 'AsylumEntrance.js`

---

BondageClub/Screens/Room/AsylumMeeting/AsylumMeeting.js

* I added JSDoc comments to the functions in `AsylumMeeting.js ` to help with further development.
* Changed AsylumMeetingClick() to use the `MouseIn` function
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/AsylumMeeting)

Improvement: JSDoc comments added to `AsylumMeeting.js`

---

BondageClub/Screens/Room/AsylumTherapy/AsylumTherapy.js

* I added JSDoc comments to the functions in `AsylumTherapy.js ` to help with further development.
* Changed AsylumTherapyClick() to use the `MouseIn` function
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/AsylumTherapy)

Improvement: JSDoc comments added to `AsylumTherapy.js`

---

BondageClub/Screens/Room/Cafe/Cafe.js

* I added JSDoc comments to the functions in `Cafe.js ` to help with further development.
* Changed CafeClick() to use the `MouseIn` function
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/Cafe)

Improvement: JSDoc comments added to `Cafe.js`

---

BondageClub/Screens/Room/CollegeCafeteria/CollegeCafeteria.js

* I added JSDoc comments to the functions in `CollegeCafeteria.js ` to help with further development.
* Changed CollegeCafeteriaClick() to use the `MouseIn` function
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/CollegeCafeteria)

Improvement: JSDoc comments added to `CollegeCafeteria.js`

---

BondageClub/Screens/Cutscene/NPCCollaring/NPCCollaring.js

- added JSDoc to NPCCollaring.js

Improvement: JSDoc comments added to NPCCollaring.js

---

BondageClub/Screens/Cutscene/PlayerCollaring/PlayerCollaring.js

- added JSDoc to PlayerCollaring.js

Improvement: JSDoc comments added to PlayerCollaring.js

---

BondageClub/Screens/Cutscene/PlayerCollaring/PlayerCollaring.js
BondageClub/Screens/Cutscene/PlayerMistress/PlayerMistress.js

- added JSDoc to PlayerMistress.js

Improvement: JSDoc comments added to PlayerMistress.js

---

BondageClub/Screens/Room/CollegeDetention/CollegeDetention.js

* I added JSDoc comments to the functions in `CollegeDetention.js ` to help with further development.
* Changed CollegeDetentionClick() to use the `MouseIn` function
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/CollegeDetention)

Improvement: JSDoc comments added to `CollegeDetention.js`

---

BondageClub/Screens/Cutscene/SarahIntro/SarahIntro.js

- added JSDoc to SarahIntro.js

Improvement: JSDoc comments added to SarahIntro.js

---

BondageClub/Screens/Cutscene/NPCSlaveAuction/NPCSlaveAuction.js

- added JSDoc to NPCSlaveAuction.js

Improvement: JSDoc comments added to NPCSlaveAuction.js

---

BondageClub/Screens/Character/Cheat/Cheat.js

- added JSDoc to Cheat.js
- Swapped the click handler conditions to use MouseIn

Improvement: JSDoc comments added to Cheat.js

---

BondageClub/Screens/MiniGame/Kidnap/Kidnap.js

Improvement: JSDoc comments added to Kidnap.js

---

BondageClub/Screens/Room/Empty/Empty.js

Improvement: JSDoc comments added to Empty.js

---

BondageClub/Screens/Room/SlaveMarket/SlaveMarket.js

- added JSDoc to SlaveMarket.js
- replaced click checks for MouseIn (Tested to make sure everything is ok)

Improvement: JSDoc comments added to SlaveMarket.js 

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Unblocked the `ItemBreast` slot for the `BitchSuitExposed` so that the breasts of the wearer can be used for sexual abilities

Improvement: Unblocked breast slot for the bitch suit exposed

---

BondageClub/Screens/Room/CollegeTeacher/CollegeTeacher.js

* I added JSDoc comments to the functions in `CollegeTeacher.js ` to help with further development.
* Changed CollegeTeacherClick() to use the `MouseIn` function
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/CollegeTeacher)

Improvement: JSDoc comments added to `CollegeTeacher.js`

---

BondageClub/Screens/Room/DailyJob/DailyJob.js

Improvement: JSDoc comments added to DailyJob.js

---

BondageClub/Screens/Room/DailyJob/DailyJob.js
BondageClub/Screens/Room/Shibari/Shibari.js

Improvement: JSDoc comments added to Shibari.js

---

BondageClub/Screens/Room/CollegeEntrance/CollegeEntrance.js

- added JSDoc to CollegeEntrance.js

Improvement: JSDoc comments added to CollegeEntrance.js

---

BondageClub/Screens/Character/Preference/Preference.js
BondageClub/Screens/Room/CollegeTennis/CollegeTennis.js

- added JSDoc to CollegeTennis.js
- fixed 2 jsdoc comments error in Preference.js

Improvement: JSDoc comments added to CollegeTennis.js

---

BondageClub/Screens/Room/CollegeTheater/CollegeTheater.js

- added JSDoc to CollegeTheater.js

Improvement: JSDoc comments added to CollegeTheater.js

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Scripts/Audio.js

- added some assets to the rope sound trigger
- added some fetish to a few asset and changed mislabeled ones
Had a deeper look and fixed a few inconsistencies.
My other question, the chopstick clamps/gag and bamboo gag are labelled as rope which I find odd. I assume its because its Shibari dojo themed?
In case you did not read discord, that was also my comment after your last post in #programming : [discord message link](https://discord.com/channels/554377975714414605/557728347468070912/738945545493807154)

Improvement: Sound and fetish adjustments

---

BondageClub/Screens/Room/Introduction/Introduction.js

- added JSDoc to Introduction.js

Improvement: JSDoc comments added to Introduction.js

---

BondageClub/Screens/Room/Gambling/Gambling.js

* I added JSDoc comments to the functions in `Gambling.js ` to help with further development.
* Changed GamblingClick() to use the `MouseIn` function
The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/Gambling)

Improvement: JSDoc comments added to `Gambling.js`

---

BondageClub/Screens/Online/GameLARP/GameLARP.js

- added JSDoc to GameLARP.js
I found several major bugs when people leave, especially the host. I'm going to try to have a look at minimizing those issues.
On a slightly more positive note, we have 8 files left to go through!

Improvement: JSDoc comments added to GameLARP.js

---

BondageClub/Screens/MiniGame/RhythmGame/RhythmGame.js

- added JSDoc to RhythmGame.js

Improvement: JSDoc comments added to RhythmGame.js

---

BondageClub/Screens/Room/KidnapLeague/KidnapLeague.js

- added JSDoc to KidnapLeague.js
- changed the click handlers to use MouseIn

Improvement: JSDoc comments added to KidnapLeague.js

---

BondageClub/Scripts/Character.js

This is the fix you need for the let tests and it is a good example of how var+hoisting can cause silent scope issues in other places. This was not an issue with var but it could have been in another context

Fix: scope issue line 255

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Scripts/Inventory.js

- fixed the door phasing out of existence while slow and stuck
The exit icon was not being drawn while wearing an item that ties you to a room and a slowing item (ball and chain and long chain for example)

Fix: exit icon in chatroom

---

BondageClub/Screens/Inventory/ItemMisc/OwnerTimerPadlock/OwnerTimerPadlock.js
BondageClub/Scripts/Inventory.js

**just in case we werent sure locks were utterly broken**
- fixed the click handler for owner timer locks
The click handler was different than the draw check, so you could click the button even if you added time once. This follows the pattern of the lover lock and the pattern of the buttons to work as intended

Fix: yes, a lock, again

---

BondageClub/Screens/Character/Appearance/Appearance.js

the x or check mark is now properly disabled in that mode

Fix: permission mode click handlers

---

BondageClub/Screens/Character/Player/Dialog_Player.csv
BondageClub/Screens/Inventory/ItemVulva/LoversVibrator/LoversVibrator.js
BondageClub/Scripts/Audio.js

The chatroom messages for the lovers vibrator referred to it as an egg. This adds new chatroom messages (that other vibrating items could use in the future to reduce the need for specific chatroom messages for every vibrating item) that address this, and hook the new messages up with the audio system.

Beta Bugfix: Incorrect chatroom messages for the lovers vibrator

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Added `ArousalZone = "ItemVulva"` to the vibrating clit egg, so that this item can trigger an orgasm as well.

Fix: Added ArousalZone attribute to TapedClitEgg

---

BondageClub/Screens/Inventory/ItemArms/HighSecurityStraitJacket/HighSecurityStraitJacket.js
BondageClub/Scripts/CommonDraw.js

Removes array destructuring from new code files, as this may be causing problems for users on outdated browser versions (Chrome 49 on Windows XP).
[Start of relevant discord discussion](https://discordapp.com/channels/554377975714414605/554378725916147722/745279687303102504).

Bugfix: Removes array destructuring from the code

---

BondageClub/Assets/Female3DCG/Female3DCG.js

- changed it so the milk wouldn't be taken as a restraint
To better replicate the previous behavior of the milk, and to keep it as a modifier more than an item, I changed it so it doesn't get removed when a NPC releases the character. This way people don't have to reapply it every time and it doesn't create soft locks since that was never counted as "gagging"

Improvement: nursery milk

---

BondageClub/Scripts/Server.js

This reverts commit a40c2121fb1388a9d477b731721195f4f24e3952.

Revert "Update Server.js (#1357)"

---

BondageClub/Screens/Online/ChatSearch/ChatSearch.js
BondageClub/Screens/Online/ChatSearch/Text_ChatSearch.csv
BondageClub/Screens/Online/ChatSearch/Text_ChatSearch_FR.txt

- added hovering text to all buttons for consistency

Improvement: Chat search hovering text

---

BondageClub/Screens/Online/ChatSearch/ChatSearch.js

- fixed a small oversight that made it impossible to clear a filtered room

Beta fix: clear filter

---

BondageClub/Screens/Inventory/ItemEars/HeadphoneEarPlugs/HeadphoneEarPlugs.js

- fixed an issue where the headphone volume was not changeable while outside of chatroom
The if statement was not closed where it had to be

Fix: headphone volume

---

BondageClub/Assets/Female3DCG/Female3DCG.js

- fixed one of the two variants of the bunny suit that did not properly expose the breast area like its counterpart

Fix: reverse bunny suit

---

BondageClub/Screens/Room/Private/Dialog_NPC_Private_Custom.csv
BondageClub/Screens/Room/Private/Private.js

- added jsdoc to private.js
- removed an unused variable
- corrected a few typos in function names and calls
- changed some click handlers to use MouseIn
One more big file to go before we are done! So from now on we can have JSDoc added to all the new stuff and not have to worry about backtracking,

Improvement: JSDoc comments added to Private.js

---

BondageClub/Screens/Room/Management/Management.js

- changed click handlers to use MouseIn
- added jsdoc comments

Improvement: JSDoc comments added to Management.js

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js

- added JSDoc comments to chatroom.js
- changed click handlers to use MouseIn
Here goes the last file! Catching up on jsdoc is a thing of the past now!

Improvement: JSDoc comments added to Chatroom.js 

---

BondageClub/Screens/Inventory/ItemArms/DuctTape/DuctTape.js
BondageClub/Scripts/ExtendedItem.js

I refactored the asset `ItemArms/DuctTape` to use the extended item script for better maintainability.

Refactor: Duct tape on arms to use ExtendedItem

---

BondageClub/Screens/Character/Login/Login.js
BondageClub/Screens/Character/Preference/Preference.js

- fixed a problem where exiting did not save the settings

Online settings fix

---

BondageClub/Screens/Character/Player/Dialog_Player.csv

- fixed a small text oversight for one of the attachments

Fix: gas mask text

---

BondageClub/Screens/Inventory/ItemLegs/DuctTape/DuctTape.js
BondageClub/Scripts/ExtendedItem.js

Refactored ItemLegs DuctTape
I added co-ordinates for a 1-option-per-page possibility as I noticed there are mittens that have that.

Refactor: Duct Tape for Legs

---

BondageClub/Screens/Inventory/ItemBoots/ToeTape/ToeTape.js

Refactored the toe tape to use the extended item script

Refactor Toe tape to extended item

---

BondageClub/Screens/Inventory/ItemMouth/PlugGag/PlugGag.js

Refactored the plug gag to use the extended script

Refactor: Plug gag

---

BondageClub/Screens/Online/ChatSearch/ChatSearch.js

- fixed the room color to be grey when the room size was changed but the room is still full (3/2 for example)

Fix: Grey rooms

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Just realized these changes got lost somewhere along the line of merges and stuff, but leg items almost all need the new AllowActivePose, this will make them work as they should.

Fix for leg and active poses

---

BondageClub/Screens/Inventory/ItemMouth/ClothGag/ClothGag.js
BondageClub/Screens/Inventory/ItemMouth2/ClothGag/ClothGag.js
BondageClub/Screens/Inventory/ItemMouth3/ClothGag/ClothGag.js

- converted all 3 cloth gags to the extended item script
- fixed an inconsistency with the initial load of the cloth gag
- the 2nd and 3rd now just refer to cloth gag 1 for simplicity

Refactor: cloth gag conversion

---

BondageClub/Screens/Inventory/ItemButt/AnalHook/AnalHook.js

Refactored the anal hook to the extended item script.

Refactor: Anal hook to extended item script

---

BondageClub/Screens/Inventory/ItemMouth/MilkBottle/MilkBottle.js

- refactored the milk bottle to use the extended script

Refactor: Bottle

---

BondageClub/Screens/Inventory/ItemDevices/Crib/Crib.js

- refactored the crib to use the extended script

Refactor: Crib

---

BondageClub/Assets/Female3DCG/Female3DCG.js

- fixes the ghost problem when wearing a suit hiding item + a lower suit
The suit is layered on top anyway, I couldn't find any reason why it would hide the body.
See -> https://discord.com/channels/554377975714414605/554378725916147722/754133691864711238

Fix: lower suit

---

BondageClub/Screens/Inventory/ItemFeet/DuctTape/DuctTape.js

- refactored the itemfeet duct tape to use the extended script

Refactor: Tape (ItemFeet)

---

BondageClub/Screens/Room/CollegeCafeteria/CollegeCafeteria.js
BondageClub/Screens/Room/CollegeDetention/CollegeDetention.js
BondageClub/Screens/Room/CollegeTeacher/CollegeTeacher.js
BondageClub/Screens/Room/CollegeTennis/CollegeTennis.js
BondageClub/Screens/Room/CollegeTheater/CollegeTheater.js
BondageClub/Screens/Room/Sarah/Sarah.js

Fixes an issue where NPC head colours for named Bondage College NPCs would have random head colours (pretty sure I got all of the NPCs where this is an issue).

Bugdix: Fixes head colour for Bondage College NPCs

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Scripts/Character.js
BondageClub/Scripts/Dialog.js

- Items that allow a pose will no longer block the pose menu (such as closing legs + using cuffs)

Improvement: Pose behavior

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Inventory/ItemNose/NoseRing/NoseRing.js

This PR refactors the nose ring to use the extended item script.

Refactor: Nose ring to use extended items

---

BondageClub/Screens/Inventory/ItemFeet/Chains/Chains.js

- refactored the itemfeet chains to use the extended script

Refactor: Chains (ItemFeet)

---

BondageClub/Screens/Character/Login/Login.js
BondageClub/Scripts/Activity.js

- Enabled proper text building for each language as well as the rebuild when toggling between languages.
Required for #1488
Fixes #1489

Activity translation

---

BondageClub/Scripts/Text.js

Removes the hardcoded `Text_` from TextCache translation filenames.

Bugfix: Ensures the correct translation files are used by the TextCache

---

BondageClub/Assets/Female3DCG/Female3DCG.js

- fixed the spreader dildo bars to actually prevent kneeling to avoid killing anyone
to test, wear dildo bar then use a short chain (before it worked when it shouldnt have)
I'm going to go through items to update some of them with all the new tech (aka removing weirdness, improving behavior, etc.) so I might add more to this PR with time if I find a lot

Kneeling with spreader bars

---

BondageClub/Screens/Character/Login/Login.js

- added extra precautions around the collar release to prevent console griefing
This will prevent people from console'ing a slave collar onto others which would lock them out of their normal behavior till they see their owner again.

Slave collar, extra precautions

---

BondageClub/Screens/Character/Appearance/Appearance.js

- fixed a bug where the wardrobe screen looked funky if you were in picker mode while someone changed their appearance in a way that made you target an empty group.

Fix color picker

---

BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
BondageClub/Screens/Inventory/ItemPelvis/MetalChastityBelt/MetalChastityBelt.js
BondageClub/Screens/Inventory/ItemPelvis/OrnateChastityBelt/OrnateChastityBelt.js
BondageClub/Screens/Inventory/ItemPelvis/PolishedChastityBelt/PolishedChastityBelt.js
BondageClub/Screens/Inventory/ItemPelvis/StuddedChastityBelt/StuddedChastityBelt.js

- fixed being able to change the belt types while they were locked

locked belt

---

BondageClub/Scripts/Text.js

Removes the use of public class fields due to incompatibility issues with older browsers.

Beta bugfix: Removes public class fields

---

BondageClub/Screens/Character/Appearance/Appearance.js

This fixes a check that would prevent skin colour from being changed in the appearance screen so that skin colour is changeable again.

Bugfix: Skin colour change fix

---

BondageClub/Assets/Female3DCG/Female3DCG.js

* Removes a duplicate `Fetish` property on fox ears 1
* Removes an additional `Fetish` property on the cow bell
* Removes a redundant `DefaultColor` property on the prison lockdown suit
* Corrects the audio on the rope toe tie

Bugfix: Various minor asset fixes

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Fixed and added gag difficulties...

Fixed and added gag difficulties

---

BondageClub/Assets/Female3DCG/Female3DCG.csv

I changed 4 names... Wildjs approved of it as well I can show the discord convo if you require that.

Removed the "Baby" from the dress names

---

BondageClub/Screens/Room/MainHall/MainHall.js

A fix/change to the maid system as follows:
- If you ring the maid button, the maid will continue to come even if you free yourself before she arrives (the purpose of the maid button is to be able to call a maid even if the maid normally wouldn't come)
- If you did not ring the maid button, but AutoMaids is turned on, and a maid starts coming but you free yourself first, the maid should stop coming.

Automatic Maids Change

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Makes the vibrating dildo's default color pink.

Vibrating Dildo Default color

---

BondageClub/Screens/Character/Preference/Preference.js

Adds a default value for returning players, and defaults to the temporary animation

Vibe VFX Default value

---

BondageClub/CHANGELOG.md
BondageClub/changelog.html

Updates the changelog with the most recent changes.

Changelog Update

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js

Fixes bug causing gag auto punishment to trigger

Fix: Automatic OOC whisper history

---

BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js

Changes the automatic gags (shock unit and futuristic) to not trigger on messages with no numbers all the time
Also snuck in a change to have it trigger on using exclamation points, since not everyone uses all caps

Auto gag fixes

---

BondageClub/Assets/Female3DCG/Female3DCG.js

To prevent it from hiding tails

Pilot suit no longer hides butt

---

BondageClub/Screens/Character/Appearance/Appearance.js

A long standing bug is hidden items still being able to hide other items, causing graphical oddities. Two examples:
- Latex Strait Leotard > hides Wedding Dress > hides BodyLower => results in the lower legs disappearing
- Latex Blindfold > hides Open Face Hood (mask version) > hides HairFront => results in the hair disappearing
The visible check has now been extended to only let another item's hide properties take effect if that item is itself visible. 
A safeguard has been included to prevent the (unlikely) possibility of two items somehow hiding each other and getting stuck in an infinite loop.

Hidden Item Hiding fix

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Tweaking the alpha to avoid cutting off clothes over larger boobs, the same exact fix as the Bolero from #1611.

Box Tie Armbinder Alpha Fix

---

BondageClub/CHANGELOG.md
BondageClub/changelog.html

Updates the changelog with the latest changes.

Updates the changelog

---

BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js

This is because it's confusing to other people when it happens

Auto shock collar and futuristic panel gag do not trigger on whispers

---

BondageClub/Screens/Character/Player/Dialog_Player.csv
BondageClub/Screens/Character/Preference/Text_Preference.csv
BondageClub/Screens/Online/ChatRoom/ChatRoom.js

Short fix that makes it so that whispers are blocked if you have disabled OOC while gagged. This is because garbled whispers have been reverted

if OOC disabled, also block whispers while gagged

---

BondageClub/Scripts/Dialog.js

Creates new facial expression menu, where instead of scrolling endlessly through emotes user first picks category and than expression.
Should there be more emotes than can fit, I will create pagination. But for that at least seven more symbols would have to be added into emoticon category

New facial expression menu

---

BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js

Futuristic Collar Crash

---

BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js

By popular request, I made the gag deflate one level at a time instead of all at once.

Futuristic gag deflation speed

---

BondageClub/Scripts/Dialog.js

Removes the hover trigger for the facial expression menu categories

New facial expression menu: remove hover trigger

---

BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js

Makes the item a bit more interesting in singleplayer. NPCs wont put it on, though, since they cant configure it.

Tweak: Futuristic Chastity belt triggers outside of chatrooms

---

BondageClub/Screens/Inventory/ItemBreast/FuturisticBra/FuturisticBra.js

I was told the heartrate seems quite low on the Futuristic Chastity Bra, so I increased the scaling so it's higher at max arousal.

Increased max heartrate on Futuristic Chastity Bra

---

BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js

Some bugfixes for the futuristic collar, including being able to put a mistress lock on someone without having one yourself.

Futuristic collar fixes

---

BondageClub/Screens/Character/Player/Dialog_Player.csv
BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Scripts/Server.js
BondageClub/index.html

Fixes the following bugs:
1) Having to hold someone's leash twice the first time before it would work
2) Being unable to leash people that don't have you on your friendlist; requires server PR: https://github.com/Ben987/Bondage-Club-Server/pull/57
3) 404 on chat room when leashed; can crash the chat room
4) Fixes being unable to leash someone to a private room
5) Fixes chat room inputs remaining on screen when leashed (and failed)

Fixes chat room text 404 error and also fixes leash bugs

---

BondageClub/Screens/Character/Login/Login.js

Instead of blocking them outright. Owners and players on the whitelist will be able to put them on.

Extreme Mode - Automatically limit combination and password padlocks

---

BondageClub/Assets/Female3DCG/Female3DCG.js

As discussed with Ayesha, just some basic default colors for the bed and the covers/blanket since most players probably don't always want a pure white experience, and the number of clicks to give it a wooden frame and some simple colors was quite large.

Default colors for Bed and Covers

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Scripts/Server.js

Fixes an issue where players that did not open their options menu couldnt be leashed

Leash hotfix

---

BondageClub/Assets/Female3DCG/Female3DCG.js

removed the pose from the pose menu as it was enabled by mistake.

Fix: removed allfours from the pose menu

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js

Fix leashing with lover and owner locks

---

BondageClub/Assets/Female3DCG/Female3DCG.js

fixed some properties to make it work with various head items a little better

Fix hood properties

---

BondageClub/Assets/Female3DCG/Female3DCG.js

uses masks instead of hide for better compatibility, this should be the final adjustments, I hope haha

Gwen hood adjustments

---

BondageClub/Screens/Character/InformationSheet/InformationSheet.js
BondageClub/Scripts/Drawing.js

- Improved draw text fit to allow the option for a background like draw text
- Made it so the first column of a profile wouldn't overlap with the second

Text fit profile screen

---

BondageClub/Assets/Female3DCG/Female3DCG.js

At the moment the band anklets are appearing on every NPC. Changing the group settings to be more in line with other clothing accessories such as hats and necklaces.
Note: There does seem to be issues with how these group settings are used in general which I'm going to look at later.

Anklets in Random Clothes

---

BondageClub/Assets/Female3DCG/Female3DCG.js

- Enabled access to ear and neck slots while wearing the GP-9 gas mask

GP-9 Gas Mask fixes

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Scripts/Server.js

Adds a ChatRoomClearAllElements function which is called when leaving the chat room

Clears friendlist, room admin, and other inputs when leashed out

---

BondageClub/Screens/Room/Photographic/Dialog_NPC_Photographic_Sub.csv
BondageClub/Screens/Room/Photographic/Photographic.js

Expanding the 'Please change your pose' dialog branch for the NPC in the Photographic room from only toggling kneeling to instead allow all the same upper & lower body poses that the player has in the pose menu.

Photography Room - NPC Poses

---

BondageClub/Screens/Character/Preference/Preference.js
BondageClub/Screens/Online/ChatRoom/ChatRoom.js

made it so the settings are synced on login if they were changed due to default settings (happens when there are new settings in update and such)
This caused desync problems online

Improvement: Preference init inconsistencies

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Inventory/ItemNeck/SlaveCollar/SlaveCollar.js
BondageClub/Scripts/Activity.js

New effect to block moving your head, which influences the new wiggle and nod activity.
Currently only applied to posture collars

New FixedHead effect

---

BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js

It's still possible to struggle out of a lot of items this way, I wanted to make it harder for any item with a challenge rating of 5 or so and probably impossible for challenge rating 6~

Lowers cooldown of futuristic chastity belt after attempting to struggle

---

BondageClub/Screens/Character/Preference/Preference.js
BondageClub/Screens/Character/Preference/Text_Preference.csv

Fixes the preference menu looking wrong and defaults not being set correctly

Return to chatroom fixes

---

BondageClub/Screens/Room/MainHall/MainHall.js

Would cause the maid rescue to fail due to the maid not being initialized properly at the start of the game. Added a 1 frame delay before it sends you

Fixed a bug in returning to chatrooms while being club mistress

---

BondageClub/Screens/Room/Stable/Stable.js

Bugfix for the removal of pony-exam items in the stable.

Stable Exam End Fix

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Room/Magic/Magic.js

Tweaking the Water Cell used in the magic show so that the bottom (which is no longer cut off) always touches the ground regardless of the character height.
Also added alpha masks for the sides.

Water Cell improvement

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Making tails visible for Suspension Hogties same as regular ones.

Suspension Hogtie Tails Visible

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Screens/Online/ChatSearch/ChatSearch.js

Fixes this by creating a new chatroom and adding the player's member number to the end.
It also fixes a bug with a newly created room being the wrong size

Fixes player being trapped on relog if the room they rejoin is full

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Not really a fix, but a simple addition to the vac-cube, now that we have the `AllowActivityOn` property. Opens up several zones to activities when in the vac-cube.

Beta Improvement: Adds AllowActivityOn to the Vac-Cube

---

BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv

Fixes incorrect function calls when an owner tries to add/remove a sub's slave collar.
Two characters:
* Character A
* Character B - owner of Character A
1. Character B attempts to add/remove Character A's slave collar through chatroom dialog
2. Observe that the collar is not added/removed

Beta Fix: Slave Collar

---

BondageClub/Screens/Character/Player/Dialog_Player.csv
BondageClub/Screens/Online/ChatRoom/ChatRoom.js

Because players were surprised that they would lose 40 dom rep. Also fixes a bug that players won't leave on other players' screens.

Confirmation dialog for calling maids to leave the room

---

BondageClub/Screens/Room/CollegeEntrance/CollegeEntrance.js

It's possible for the college uniform to have a Color value of "Default" instead of the more typical ["Default","#202020","Default"] which was not allowing the player inside the college despite being the right colours. Now fixed.

College Entrance Uniform Colour fix

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Stops the upper pilot suit from hiding the butt and vulva...

Pilot suit fix

---

BondageClub/Assets/Female3DCG/Female3DCG.js

The medical restraints weren't removed from the random pool, which could lead to some strange issues.

Bugfix: Removes the medical restraints from the random pool

---

BondageClub/Screens/Inventory/ItemFeet/Chains/Chains.js

The chains on feet options weren't changing the pose to close the legs like they should have.

Chains Feet LegsClosed fix

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Inventory/ItemVulva/FullLatexSuitWand/FullLatexSuitWand.js

Refactors the full latex lockdown suit's wand to the extended vibrator script

Refactor: Full latex lockdown suit wand

---

BondageClub/Scripts/Server.js

There is currently a loophole in the validation for appearance bundles which allows non-owners/non-lovers add owner/lover locks through the console. This PR addresses that. I've also refactored the code for deleting invalid locks into a single `ServerDeleteLock` function, as it was getting repeated a lot.
Two characters required: Character A & Character B. Character B should not be Character A's owner
1. Apply a lockable item to Character A
2. As Character B, run the following in the console (assuming `ChatRoomCharacter[1]` refers to Character A, the item is in the `ItemArms` group, and `2` is the member number of Character A's owner):
```js
InventoryLock(ChatRoomCharacter[1], "ItemArms", "OwnerPadlock", 2);
ChatRoomCharacterUpdate(ChatRoomCharacter[1])
```
3. Note that an owner lock has …

Bugfix: Prevents non-owners/lovers from adding owner/lover locks

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Simple default colors for the collars to give them their original look back.

Default Colors for collars

---

BondageClub/Scripts/Dialog.js

Fix crash when swapping items

---

BondageClub/Scripts/Dialog.js

Replaces InventoryGroupIsBlocked(C, null, false) with InventoryGroupIsBlocked(C, null, true)  in dialog.js in two places where it should have been. (merge error)

 InventoryGroupIsBlocked(C, null, true) 

---

BondageClub/Screens/Character/Appearance/Appearance.js
BondageClub/Screens/Character/Appearance/Text_Appearance.csv

This adds a colour-picker button into the top menu for the Cloth Appearance subscreen, i.e. the individual clothes group selections.

Clothes Group Colour Button

---

BondageClub/Scripts/Timer.js

The pink glowing meter is now more responsive, without changing overall speed of arousal gain while vibed

More responsive vibrator visual effects

---

BondageClub/Scripts/Drawing.js

The final suggestion from #1979 for button fills on mobile screens hadn't actually been commited.

Appearance Group buttons - mobile

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
BondageClub/Screens/Inventory/ItemTorso/FuturisticHarness/FuturisticHarness.js
BondageClub/Screens/Inventory/ItemTorso/FuturisticHarness2/FuturisticHarness2.js
BondageClub/index.html

3 changes:
1 - fixed crash with futuristic chastity belt shocks
2 - Made futuristic chastity belt have a low cooldown for the shocks for struggling. I don't see a need to limit the shock time. However, the orgasm timer is still there.
3 - Added the copy colors feature to the futuristic harness, per request from players. Lots of people already wear collars, so the feature is pretty useful to have on a non-collar item.

Some futuristic item changes

---

BondageClub/CSS/Chess.css
BondageClub/Screens/MiniGame/Chess/BondageChess.js
BondageClub/Screens/MiniGame/Chess/OLD/chessAIOLD.js
BondageClub/Screens/MiniGame/Chess/chess.js
BondageClub/Screens/MiniGame/Chess/chessboard-0.3.0.js
BondageClub/Scripts/Server.js

fixes: Uncaught TypeError: Cannot read property 'toString' of undefined at MiniGameChessResize (chess.js:338)

fix: chess with css

---

BondageClub/Screens/Inventory/ItemArms/TightJacket/TightJacket.js
BondageClub/Screens/Inventory/ItemArms/TightJacketCrotch/TightJacketCrotch.js

Corrects chatroom messages like 'adds all addons to DestinationCharacter tightjacket'.

TightJacket Message Fix

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js

Refactors `ChatRoomDrawCharacter` function to be more readable and more easily extendable.
Functional changes: Player can now always click self or current whisper target to stop whispering
Technical changes:
Separates character overlay icons drawing into `ChatRoomDrawCharacterOverlay`
Separates character click handling into `ChatRoomClickCharacter`
All clicking tested carefully

Refactor: ChatRoomDrawCharacter

---

BondageClub/Scripts/Drawing.js

Restoring a change from #2014 that got lost in a merge.

Photo Blink Fix

---

BondageClub/Screens/Inventory/ItemDevices/TransportWoodenBox/TransportWoodenBox.js

Linking the exit function so controls are properly removed.

Transport Box Exit fix

---

BondageClub/Scripts/Dialog.js

Fixes 2 things with lock picking:
-People getting tired a lot less than they should be due 
-Chat room messages not being published properly

Lock picking fixes

---

BondageClub/Assets/Female3DCG/Female3DCG.js

A few changes to my pet bed item, these reflect and are meant to compliment PR #2085 with more fixes unrelated to those relied in PR #2084 
It does not need either of the PRs listed above to work and function as intended, it just refines code from the base item such as removing Item hides and getting the effects right

Item Tweak: Pet Bed

---

BondageClub/CSS/Styles.css
BondageClub/Scripts/Drawing.js
BondageClub/Scripts/Element.js

Fixes Canvas css position and replaces logic for positioning elements.
Tested on both mobile and desktop (both landscape and vertical)
There should be no change in look against earlier versions

Fix: Canvas and element positioning

---

BondageClub/Screens/Character/Preference/Preference.js

This is not intentional, not sure why it was set this way.

Fix "Disable picking locks on self" forced in hardcore

---

BondageClub/Assets/Female3DCG/Female3DCG.js

This is to prevent cases where the Edge and Deny modes won't work with those items.

Add Edged to AllowEffect of most vibrating toys

---

BondageClub/Assets/Female3DCG/Female3DCG.csv

Adding in the missing csv asset names for the newly added Suit Lower copies of Socks items.

Missing SuitLower Names

---

BondageClub/Assets/Female3DCG/Female3DCG.csv

Correcting the SuitLower name order so they appear on the right assets.

SuitLower Order Fix

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Removes the lock icon from the nodisplay type

Futuristic chastity bra no display lock icon

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js

Removes the .IsRestraint check from the key giving functions.

Giving keys is possible when wearing just collar/nonrestraint

---

BondageClub/Screens/Room/MainHall/MainHall.js

Also removes the wardrobe blocking since many players aren't comfortable with that.

Changes the punishment for calling the maids for help to a timer padlock

---

BondageClub/Scripts/Struggle.js

Tweaks the flexibility minigame to be more difficult, since it was easy to escape at challenge 6 compared to the button mashing game.

Flexibility Minigame Difficulty

---

BondageClub/Assets/Female3DCG/Female3DCG.csv
BondageClub/Screens/Character/Player/Dialog_Player.csv
BondageClub/Scripts/Asset.js
BondageClub/Scripts/Common.js
BondageClub/Tools/Node/AssetCheck.js

Changes how asset description is resolved, preventing the error of names being assigned to different items.
Tested, including translations

Fix/Refactor: Asset description

---

BondageClub/Scripts/Common.js
BondageClub/Scripts/Translation.js

This fixes root cause of one of the problems fixed in #2161 
Also fixes translation code.

Fix: CRLF problems

---

BondageClub/Scripts/Struggle.js

If the challenge level is 1 or 0 then it will be very easy to remove, and so the game goes directly to the brute force minigame.
Thanks @Nina-1474 for the suggestion!

Skips struggle minigame choice if the item will be easy to remove

---

BondageClub/Scripts/Drawing.js

Fixed an issue with a variable not being initialized properly

Fix dark BG when talking to characters

---

BondageClub/Screens/Inventory/ItemMisc/PasswordPadlock/PasswordPadlock.js
BondageClub/Screens/Inventory/ItemMisc/SafewordPadlock/SafewordPadlock.js
BondageClub/Screens/Inventory/ItemMisc/TimerPasswordPadlock/TimerPasswordPadlock.js

Fixes the tab order in password padlocks so that hint is before the password

Password padlock tab order

---

BondageClub/Scripts/Character.js

This prevents players from being slowed for wearing a skirt unless legs are bound or covered

Stop the player from being slowed by skirts

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js

Correcting/rewriting part of ChatRoomMenuDraw() which got mixed up during a recent merge.

Kneel Button Merge Fix

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Inventory/ItemArms/MetalCuffs/MetalCuffs.js

I accidentally added difficulty to to the behind back pose of the metal cuffs which causes them to be much harder to escape now. 
This PR fixes this by removing the additional difficulty completely.
Edit:
Also fixes the missing lock attribute in both variations

Metal Cuffs Behind Back option difficulty fix

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js

Seems like it should be harder to get up than to get down

Increases the difficulty of the minigame to get up if you are kneeling

---

BondageClub/Assets/Female3DCG/Female3DCG.js

changes priority of camisole to prevent it appearing over some arm items
-change priority from 27 to 22

Beta Fix: Camisole

---

BondageClub/Screens/Character/Creation/Creation.js

Do not display changelog maid for new players

Fix: Changelog on account creation

---

BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js

Because "futuristic gag" fully ignoring saying with cyrilic

Added cyrilic for detect words to futuristic gag.

---

BondageClub/Assets/Female3DCG/Female3DCG.js

- Fixed respirator mask still gagging when applied in a certain slot

Respirator gag fix

---

BondageClub/CHANGELOG.md
BondageClub/changelog.html
BondageClub/index.html

Updates the changelog with beta 1 fixes and bumps the game version to `R66Beta2`.

Changelog Update: R66 Beta 2

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Scripts/Inventory.js

Improves `InventoryItemHasEffect` to properly detect empty effects and makes it check properties by default (because that is 99% wanted use case)

Fix: InventoryItemHasEffect

---

BondageClub/Screens/MiniGame/Chess/chess.js

It's possible to move your own chess pieces during the opponent's turn, which freezes the game.

Chess Simultaneous Move Fix

---

BondageClub/CHANGELOG.md
BondageClub/changelog.html
BondageClub/index.html

* Updates changelog with the latest changes
* Bumps game version to `R66Beta3`
* Also includes the currently unmerged #2230 in the changelog

Changelog: R66 Beta 3

---

BondageClub/CHANGELOG.md
BondageClub/changelog.html
BondageClub/index.html

Updates changelog and bumps game version to R66.

Changelog: Updates changelog for R66

---

BondageClub/Screens/MiniGame/Chess/BondageChess.js
BondageClub/Screens/MiniGame/Chess/chess.js
BondageClub/Screens/Room/CollegeChess/CollegeChess.js

In the chess minigame there's now a 50% chance that the player will play as the black pieces instead of the white pieces.

Chess - Play as Black

---

BondageClub/Screens/Inventory/ItemArms/TransportJacket/TransportJacket.js
BondageClub/Screens/Inventory/ItemDevices/PetBowl/PetBowl.js
BondageClub/Screens/Inventory/ItemDevices/WoodenBox/WoodenBox.js
BondageClub/Screens/Inventory/ItemHood/CanvasHood/CanvasHood.js
BondageClub/Screens/Inventory/ItemMisc/WoodenSign/WoodenSign.js
BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag.js/CustomCollarTag.js
BondageClub/Screens/Inventory/ItemNeckAccessories/ElectronicTag/ElectronicTag.js

Items tested to work and no longer crash

Fix: Possible crashes when text items have bad properties

---

BondageClub/Screens/Online/ChatAdmin/Text_ChatAdmin.csv
BondageClub/Screens/Online/ChatBlockItem/ChatBlockItem.js
BondageClub/Screens/Online/ChatBlockItem/Text_ChatBlockItem.csv
BondageClub/Screens/Online/ChatCreate/Text_ChatCreate.csv
BondageClub/Screens/Online/ChatSearch/Text_ChatSearch.csv
BondageClub/Scripts/Activity.js

Adding a new Block category for admins to set on their rooms which disables arousal activities and actions in that room.
Also tweaked some Block settings text a little to reflect that it's not only for blocking items now.

Block Arousal Activities in Room

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Just a little fix to remove some duplicate properties from two layers of the Futuristic Harness

Bugfix: Removes duplicate properties from Futuristic Harness layers

---

BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
BondageClub/Scripts/Drawing.js

Fixes issue with character being 100% black while blind and also added a null check for keybindings.

Kinky Dungeon fix

---

BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLoot.js
BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js

Restricts Devious Dungeon Challenge to only occur inside the arcade, to prevent weird situations with players getting bound in chat rooms.

Devious Dungeon Only happens in Arcade

---

BondageClub/Screens/Character/Player/Dialog_Player.csv

forgot to add chatroom dialog for the exposed tape

Fix: exposed tape missing dialog

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Scripts/Server.js

This PR enables the use of function `ChatRoomSyncMemberJoin` added by PR #2272 on which it depends. It requires Server PR [#81](https://github.com/Ben987/Bondage-Club-Server/pull/81) to work.

ChatRoomSync-Split: Enable ChatRoomSyncMemberJoin

---

BondageClub/Screens/Room/Private/Dialog_NPC_Private_Custom.csv

makes it so the custom characters from the private room react to one adding/removing a chastity belt

Fix: chastity belt response for private characters

---

BondageClub/Screens/Character/FriendList/FriendList.js
BondageClub/Scripts/Timer.js

- adds "Reply" button when reading beep message, opening send beep dialog
- If friendlist was opened from chat search screen, the names of rooms on list of friends and on beeps will be clickable, exiting the friendlist and searching for said room (only if friend is in same space as player)

Improvements: Friendlist

---

BondageClub/CHANGELOG.md
BondageClub/changelog.html
BondageClub/index.html

Updates the changelog with all changes for R67 Beta 1

Updates the changelog for R67 Beta 1

---

BondageClub/CHANGELOG.md
BondageClub/changelog.html
BondageClub/index.html

Updates the changelog with fixes from beta 1.

Feature: Changelog R67 Beta 2

---

BondageClub/Screens/Inventory/ItemPelvis/SciFiPleasurePanties/SciFiPleasurePanties.js

I messed up the click part for the show chat message box. By both including two versions of it AND also putting in the wrong XY values. Just found it out and fixed them. Needs to get in before next update.

Urgent Pleasure Panties js update

---

BondageClub/CHANGELOG.md
BondageClub/changelog.html

Also includes the currently-unmerged #2322.

Feature: Updates the changelog for beta 3

---

BondageClub/Screens/Character/Preference/Text_Preference.csv

Total -> Heavy
Total (No Whispers) -> Total

Rename sensory deprivation settings

---

BondageClub/Scripts/Validation.js

This fixes a few more cases where parts of the validation wouldn't get run under some conditions.

Bugfix: Additional validation fixes

---

BondageClub/CHANGELOG.md
BondageClub/changelog.html
BondageClub/index.html

Includes #2326, #2329, #2330, #2332, #2335.

Feature: Updates changelog for R67

---

BondageClub/Screens/Room/MovieStudio/MovieStudio.js

The "Wear the latex corset" option in the movie wasn't working because that item moved groups from Bra to Corset.

Movie Studio Corset fix

---

BondageClub/Screens/Character/FriendList/FriendList.js

Fixes crash, that happens when you open beep log from chat search screen, while you have received beep from someone, who isn't in room.

Fix: Crash during beep log rendering

---

BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js

Makes the kinky dungeon minigame persistent so you can leave the game and come back to it without resetting your progress. To start a new game you have to either lose or relog.

Kinky Dungeon Persistence

---

README.md

This adds a workflow status badge to the top of the readme file, to make it easier to identify if there are asset issues that need fixing on the current master branch (see [workflow status badges](https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge)). You can preview the badge by viewing the rich diff. That's all this PR does!

Feature: Adds a badge for the asset check to the readme

---

BondageClub/Scripts/Character.js

Fix mixed spaces and tabs

---

BondageClub/Scripts/Character.js

Format function `CharacterLoadCanvas` changed by #2342 to fix linting error

Fix: CharacterLoadCanvas Lint

---

BondageClub/Screens/Character/Player/Dialog_Player.csv

Just added a missing tag for ZipArmsSetZipWrist

Bug fix: Adding missing tag

---

BondageClub/Assets/Female3DCG/Female3DCG.js

To keep this cleanup small, this part only focuses on file `Assets/Female3DCG/Female3DCG.js`

Cleanup: Scripts formatting (Part 6 - `Assets/Female3DCG/Female3DCG.js`)

---

BondageClub/Scripts/Struggle.js

To keep this cleanup small, this part only focuses on file `Scripts/Struggle.js`

Cleanup: Scripts formatting (Part 5 - `Scripts/Struggle.js`)

---

BondageClub/Screens/Character/Preference/Preference.js
BondageClub/Screens/Character/Preference/Text_Preference.csv
BondageClub/Scripts/Drawing.js
BondageClub/Scripts/Notification.js
BondageClub/index.html

This adds a new alert option for notifications: "(1) in icon"
It draws a red circle onto the icon in the document/window header containing the incrimenting number of notifications, similar to the "(1) in title" option.

Icon Notification Option

---

BondageClub/Scripts/Reputation.js
BondageClub/Scripts/Skill.js

it also makes invalid skills not show up at all, **but they never get deleted**

Fix: allows one to login with invalid skills/reps

---

BondageClub/Screens/Character/Login/Login.js
BondageClub/Screens/Character/Preference/Preference.js
BondageClub/Screens/Character/Preference/Text_Preference.csv
BondageClub/Scripts/Drawing.js
BondageClub/Scripts/Inventory.js
BondageClub/Scripts/Timer.js

makes it hard to see after removing a blindfold.
this can be turned off in the preferences.

Feature: BlindFlash

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Inventory/ItemFeet/SpreaderVibratingDildoBar/SpreaderVibratingDildoBar.js

Does exactly that. Uses the (not so) new vibrator options for the vibrating dildo bar
Tested that on my local installation and all looked fine.

Refactor: VibratingDildoBar to extended vibrator script

---

BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonVision.js
BondageClub/Screens/Room/Pandora/Pandora.js

Fixes linting errors introduced in #2404 & fd09289b5baf8e7e5ae64b87ca43ffc1b0b7a141.

Bugfix: Fixes linting errors

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Currently it does not apply any gagging effect whatsoever. This should fix that?

Fix latex posture collar gag

---

BondageClub/Scripts/Inventory.js
BondageClub/Scripts/Typedef.d.ts

Fixes a handful of small type definitions and JSDoc inside `Inventory.js`. Has no impact on the game itself, but will make life easier for IDE users.

Bugfix: Type definition & JSDoc fixes

---

BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv

-fix locks not appearing on player
-fix missing text
-fix devious dungeon challenge not locking locks to the player
-fix harness grabbing not working when player is harnessed
-fixed harness grabbing not working when the player doesnt have any evasion buffs
-fix doors slowing down the game by the prompt coming up too often

kinky dungeon fixes

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Adding the usual default color schema options to ItemBoots.

ItemBoots Color Schema

---

BondageClub/Scripts/Audio.js

heh, forgot to trigger the sound when the shock happens. fixed.

Added sound to futuristic vibrator shock

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Prevents you from being able to put the clit ring on while wearing clothing items that should block it.

Beta fix for clit ring

---

BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js

-Sci fi panties should be recolored by it
-Fixed crash when applying colors to a futuristic muzzle whose color is not default

Fixes for futuristic collar

---

BondageClub/CHANGELOG.md
BondageClub/changelog.html
BondageClub/index.html

* Updates changelog with beta 1 changes
* Bumps version to R68Beta2

Changelog: R68 Beta 2

---

BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js

Makes it so the player cant just immediately unlock them after getting out of the game >.<

MemberNumber = null for locks on player

---

BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js

Adds in one last fix which should prevent crashes from the futuristic collar from happening

Futuristic Collar Crash Prevention

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Makes the ribbons in the breasts and pelvis slot not be able to be put on through clothes.

Fix for ribbon application

---

BondageClub/Assets/Female3DCG/Female3DCG.js

fixed for the metal leg spreader from being allowed to be applied when your are legs closed

fix: metal leg spreader

---

BondageClub/CHANGELOG.md
BondageClub/changelog.html
BondageClub/index.html

* Updates the changelog with remaining fixes
* Bumps game version to R68

Changelog: R68 Release

---

BondageClub/Screens/MiniGame/Chess/chess.js

Fix to an error that meant the NPC never makes any chess moves.

Chess Calculation Fix

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js

Fixed items that are not vibrators potentially applying a stimulation message that mentions vibration.

Stimulation Messages Fix

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Character/Preference/ActivityDictionary.csv

Extended the stepping activity to the Breasts, Butt, Neck, Head, and nose. Also includes a small change/fix for the Tennis ball.

More stepping activities

---

BondageClub/Assets/Female3DCG/Female3DCGExtended.js
BondageClub/Scripts/Common.js
BondageClub/Scripts/Dialog.js
BondageClub/Scripts/ExtendedItem.js
BondageClub/Scripts/ModularItem.js
BondageClub/Scripts/TypedItem.js
BondageClub/Scripts/Typedef.d.ts
BondageClub/Scripts/VibratorMode.js

This PR fixes many small problems with documentation around extended, typed and modular items

Extended items documentation & fixes

---

BondageClub/Scripts/Common.js
BondageClub/Tools/Node/AssetCheck.js
BondageClub/Tools/Node/AssetCheck_Types.js
BondageClub/Tools/Node/jsconfig.json

Updates asset check to keep up with latest extended item archetype changes.

Improvement/Fix: Asset check update for extended items

---

BondageClub/Scripts/Asset.js
BondageClub/Scripts/Character.js
BondageClub/Scripts/Drawing.js

Creates function `DrawImageEx` unifying functionality of most image drawing functions in more optimised way.
Also improves how inversion (suspension) and blindness is drawn.
Performance effect: Character drawing while bindfolded or inverted is ~40% faster.
There is no visible change, everything looks the same.
Tested with various combinations of inverted characters and blindfolds.

Improvement: Drawing optimisations

---

BondageClub/Assets/Female3DCG/Female3DCG.js

This PR corrects a copy/paste error that hid too many items on the short pencil skirt

Fix: Correct some wrongly hidden items on the short pencil skirt

---

BondageClub/Scripts/Server.js

@jomshir98 suggested small changes to the timing and a fix so the timer won't always reset

fix sync reset test

---

BondageClub/Screens/Room/Arcade/Arcade.js
BondageClub/Scripts/Dialog.js

Fixes persistence of kinky dungeon, which was broken in the last fix.

Fix kinky dungeon persistence

---

BondageClub/Screens/Inventory/ItemDevices/VacBedDeluxe/VacBedDeluxe.js

Cleans up and simplifies Vacuum Bed Deluxe's code. Done with @TessaTech's permission.

Cleanup: Vacuum Bed Deluxe code

---

BondageClub/CHANGELOG.md
BondageClub/changelog.html
BondageClub/index.html

* Updates changelog with fixes from beta 2
* Bumps game version to R69Beta3

Changelog: R69 Beta 3/Release

---

BondageClub/Scripts/Validation.js

There was a minor issue with lock validation where full character updates on characters wearing limited locks (often combination locks etc.) would trigger validation warning messages about invalid lock modification in the console, despite the lock not having been modified. This would trigger a lock rollback, although as the lock hadn't actually been modified, the rollback wouldn't do anything. This fix prevents the warning messages and the unnecessary rollbacks that were occurring.
1. On player 1, equip an item
2. Lock the item with a lock whose permissions have been set to limited
3. As a player that _doesn't_ have access to limited items on player 1, trigger a full appearance update on player 1 (e.g. change their clothes and hit the "accept" button in the wardrobe)
4. Note that the …

Bugfix: Prevents false lock modification warning messages in the console

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Added DrawLocks: false for PigNoseHook asset configuration.

fix for 404 on PigNoseHook_Lock.jpg

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js

Refactors the custom drawing list in ChatRoom.js in order to support features besides the VR headset. This is to fix an issue with the orgasm filter that's in release (and also beta), but I did a little more work to ensure the fix is not a special case but supports future features (like a new immersion option I am working on)

Fix pink orgasm filter + refactor chat room drawing

---

BondageClub/Screens/Character/Creation/Creation.js
BondageClub/Screens/Character/Creation/Text_Creation.csv

- made the signup more robust, adding validation for length in case the maxlength is bypassed for some reason.
example of how this can happen: https://discord.com/channels/554377975714414605/554378725916147722/858561603230498826

creation length validation

---

BondageClub/Screens/Character/Appearance/Appearance.js

- fixed a crash that makes it impossible to sign up because of the recent addition of the preview setting

creation crash

---

BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js

- fixed a few crashes with the automatic shock unit

auto shock unit fixes

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Character/Appearance/Appearance.js
BondageClub/Screens/Character/Login/Login.js
BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Screens/Room/Private/Private.js
BondageClub/Scripts/Activity.js
BondageClub/Scripts/Asset.js
BondageClub/Scripts/Audio.js
BondageClub/Scripts/Character.js
BondageClub/Scripts/ColorPicker.js
BondageClub/Scripts/Common.js
BondageClub/Scripts/CommonDraw.js
BondageClub/Scripts/Dialog.js
BondageClub/Scripts/Drawing.js
BondageClub/Scripts/DynamicDraw.js
BondageClub/Scripts/Element.js
BondageClub/Scripts/GLDraw.js
BondageClub/Scripts/GameLog.js
BondageClub/Scripts/Graph.js
BondageClub/Scripts/Inventory.js
BondageClub/Scripts/ModularItem.js
BondageClub/Scripts/Reputation.js
BondageClub/Scripts/Skill.js
BondageClub/Scripts/Speech.js
BondageClub/Scripts/TypedItem.js
BondageClub/Scripts/Typedef.d.ts
BondageClub/Scripts/Validation.js
BondageClub/Scripts/VibratorMode.js
BondageClub/index.html

This PR:
- Fixes possible crash in `LogQueryRemote`
- Fixes `GLDraw2DCanvasBlink` ignoring alphaMasks
- Fixes many mistakes in documentation
- Fixes many formatting errors

Fix/Improvement: Many small fixes, documentation and formatting

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Scripts/Dialog.js
BondageClub/Scripts/Typedef.d.ts

**Depends on #2665**
Uses new `Resize` screen function to optimise chatroom code, improving performance by ~15% (depending on device) by not having to reposition chat and input each frame.
Also cleans up the code and fixes small mistakes found inside

Improvement: Optimise and cleanup chatroom code

---

BondageClub/Screens/Character/ItemColor/ItemColor.js

- split the export/import color button logic to make sure they are both supported before enabling them (this prevents crashes when trying to import/export on browsers that only support one of these options, such as firefox)
- fixed a crash occurring after getting an error because of `console.err`
- modified return statement to avoid type errors

various color picker fixes

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Character/Preference/ActivityDictionary.csv

Adds activity to rest head on breasts.

New Rest Head activity

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Scripts/Typedef.d.ts

- corrected a line i improperly reverted in a previous pr
- added garters to the hide array to prevent them from floating when using the up button
Note: the check is not failing because of this PR, but because of one of the Pandora WIP commit from an hour ago

minor fixes

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js
BondageClub/Screens/Online/ChatSearch/ChatSearch.js

Fixes the following bugs:
1) Adds a small delay so that public rooms recreated have their admins changed properly - Tested as part of (2)
2) Changes the logic for new room creation to increment the number by 1 instead of setting it to a random number - Tested by creating a 3 person room, disconnecting one player, setting size to 2, then relogging as the 3rd character. Repeated twice to verify incrementation. Tested with 20 person room title.

Recreate chat room fixes

---

BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessBallGag/FuturisticHarnessBallGag.js
BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js
BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js

Adds logic similar to the new instant logic for the futuristic vibrator to the following items:
Auto Shock Collar
Auto Shock Unit
Futuristic Panel/Ball Gags
Futuristic Training Belt

Update timing on auto shock collar and futuristic items

---

BondageClub/Scripts/Struggle.js

This makes the game easier but the pick will still eventually break.

Allow more tries with a lent lockpick

---

BondageClub/Assets/Female3DCG/Female3DCG.js
BondageClub/Screens/Inventory/ItemDevices/Kennel/Kennel.js

- made it so the door can always be opened, especially useful when paired with items that block the devices slot
- fixed which sound is played when others perform an action

kennel changes

---

BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor.csv

- added a label for the garters group at the shop, under underwear
apparently more people than I do use this menu XD

garters shop

---

BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js

Should be -1 so that it doesn't arouse when off

Fix intensity = 0 in training belt

---

BondageClub/Assets/Female3DCG/Female3DCG.js

Fixed the issue with bracelets not being able to be interacted with by other players

[Asset] [Beta Fix] [Natsuki] R70 Bracelet fix

---

BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js

Fixes:
-Public mode not updating if another player changes it
-Crash when it triggers an orgasm

Fix bug with training belt not updating if another player changes it

---

BondageClub/CHANGELOG.md
BondageClub/changelog.html

Updates changelog for R70 Beta 3

Changelog: R70 Beta 3

---

BondageClub/Assets/Female3DCG/Female3DCGExtended.js

- fixed a missing property after converting the belts

lock change belts

---

BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js

- fixed an issue with the get type function of handhelds returning an improper type when wearing an item with a type in the ItemHands slot

Spanking toys get type issue

---

BondageClub/Scripts/Dialog.js

Fixed and tested. Forgot to push this commit last time. >.<

Fix crash when futuristic training belt triggers orgasm

---

BondageClub/CHANGELOG.md
BondageClub/changelog.html

* Updates changelog with fixes from beta 3
* Includes #2749

Changelog: R70

---

BondageClub/Scripts/Activity.js

Fixes ruined orgasms so it does not randomly fail when there are others in the room.

Fix ruined orgasms

---

BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js

The futuristic training belt took gags into account correctly but not stuttering. This fixes that.
Re-tested with vibrator and gag.

Futuristic Training Belt Punishment Fix

---

BondageClub/Screens/Inventory/ItemFeet/FuturisticAnkleCuffs/FuturisticAnkleCuffs.js
BondageClub/Screens/Inventory/ItemLegs/FuturisticLegCuffs/FuturisticLegCuffs.js

- replaced old references to dialog which no longer exists

fix missing dialog

---

BondageClub/Screens/Room/Cafe/Cafe.js
BondageClub/Screens/Room/Cafe/Dialog_NPC_Cafe_Maid.csv

- fixed a crash when getting tied in leather cuffs due to the recent refactor to the typed items. 
- Includes a text change for consistency + minor type fixes.

cafe crash fix

---

BondageClub/Screens/Character/Login/Login.js

Adds ignore to `LoginThankYouList`, after @Ben987 pushed commit with errors on master... again...

Priority fix: Fixes lint error

---

BondageClub/Assets/Female3DCG/Female3DCG.js

- removed many BuyGroup attributes that were unnecessary (only 1 item in the group)
- corrected improper/missing buygroups on some items (meaning you had to buy one too many of certain items)
this may conflict with the other cleanups, I'll resolve conflicts if necessary

Buygroups cleanup

---

BondageClub/Screens/Online/ChatRoom/ChatRoom.js

Would cause a crash otherwise.

Fix ChatRoomCarryingBounty

---

BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js

Increase cooldowns on futuristic training belt

---

BondageClub/Screens/Character/Player/Dialog_Player.csv

Fix 15 minutes duration for suitcase game

---

BondageClub/Screens/Character/Player/Dialog_Player.csv

Re-adds FuturisticChastityBeltSetGeneric after it was mistakenly deleted

Fix training belt dialogue

---

BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMultiplayer.js

Should hopefully fix a crash when spectating kinky dungeon by preventing bad data from going through.

Fixed crash when spectating kinky dungeon

---

BondageClub/Scripts/VibratorMode.js

From the kinky dungeon changes. Whoops!!

Revert accidental changes to VibratorMode.js

---

BondageClub/Screens/MiniGame/MagicBattle/MagicBattle.js
BondageClub/Screens/Online/ChatCreate/ChatCreate.js
BondageClub/Screens/Online/Game/OnlineGame.js
BondageClub/Screens/Online/GameLARP/GameLARP.js
BondageClub/Screens/Online/GameMagicBattle/GameMagicBattle.js
BondageClub/Screens/Room/AsylumGGTS/AsylumGGTS.js
BondageClub/Scripts/Typedef.d.ts

More tests - Reverts Ben987/Bondage-College#3211

Revert "Revert "Simplify online game status""

---

BondageClub/Scripts/Element.js

Reverts Ben987/Bondage-College#3358

Revert "Fix dereferencing null DOM elements"
